// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type {
  DevicePairData,
  DevicePairErrors,
  DevicePairResponses,
  HealthData,
  HealthResponses,
  MobileBootstrapData,
  MobileBootstrapErrors,
  MobileBootstrapResponses,
  MobileFinanceGetTransactionData,
  MobileFinanceGetTransactionErrors,
  MobileFinanceGetTransactionResponses,
  MobileFinanceListTransactionsData,
  MobileFinanceListTransactionsErrors,
  MobileFinanceListTransactionsResponses,
  OperatorIssuePairingCodeData,
  OperatorIssuePairingCodeErrors,
  OperatorIssuePairingCodeResponses,
  OperatorListDevicesData,
  OperatorListDevicesErrors,
  OperatorListDevicesResponses,
  OperatorRevokeDeviceData,
  OperatorRevokeDeviceErrors,
  OperatorRevokeDeviceResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Spend a pairing code for a device identity. The tokens are returned once
 */
export const devicePair = <ThrowOnError extends boolean = false>(
  options?: Options<DevicePairData, ThrowOnError>
): RequestResult<DevicePairResponses, DevicePairErrors, ThrowOnError> =>
  (options?.client ?? client).post<DevicePairResponses, DevicePairErrors, ThrowOnError>({
    url: '/devices/pair',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Liveness shape. Answers without a database round-trip
 */
export const health = <ThrowOnError extends boolean = false>(
  options?: Options<HealthData, ThrowOnError>
): RequestResult<HealthResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
    url: '/health',
    ...options,
  });

/**
 * What the app should render, and who the federation says it is talking to
 */
export const mobileBootstrap = <ThrowOnError extends boolean = false>(
  options?: Options<MobileBootstrapData, ThrowOnError>
): RequestResult<MobileBootstrapResponses, MobileBootstrapErrors, ThrowOnError> =>
  (options?.client ?? client).get<MobileBootstrapResponses, MobileBootstrapErrors, ThrowOnError>({
    url: '/mobile/bootstrap',
    ...options,
  });

/**
 * One cursor-paginated page of transaction list rows
 */
export const mobileFinanceListTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<MobileFinanceListTransactionsData, ThrowOnError>
): RequestResult<
  MobileFinanceListTransactionsResponses,
  MobileFinanceListTransactionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    MobileFinanceListTransactionsResponses,
    MobileFinanceListTransactionsErrors,
    ThrowOnError
  >({ url: '/mobile/finance/transactions', ...options });

/**
 * The fuller record behind one list row, for the detail screen
 */
export const mobileFinanceGetTransaction = <ThrowOnError extends boolean = false>(
  options: Options<MobileFinanceGetTransactionData, ThrowOnError>
): RequestResult<
  MobileFinanceGetTransactionResponses,
  MobileFinanceGetTransactionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileFinanceGetTransactionResponses,
    MobileFinanceGetTransactionErrors,
    ThrowOnError
  >({ url: '/mobile/finance/transactions/{id}', ...options });

/**
 * List paired devices, revoked ones included. Never returns a token or a key
 */
export const operatorListDevices = <ThrowOnError extends boolean = false>(
  options?: Options<OperatorListDevicesData, ThrowOnError>
): RequestResult<OperatorListDevicesResponses, OperatorListDevicesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    OperatorListDevicesResponses,
    OperatorListDevicesErrors,
    ThrowOnError
  >({ url: '/operator/devices', ...options });

/**
 * Soft-revoke a device and kill its refresh-token family in one transaction
 */
export const operatorRevokeDevice = <ThrowOnError extends boolean = false>(
  options: Options<OperatorRevokeDeviceData, ThrowOnError>
): RequestResult<OperatorRevokeDeviceResponses, OperatorRevokeDeviceErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    OperatorRevokeDeviceResponses,
    OperatorRevokeDeviceErrors,
    ThrowOnError
  >({ url: '/operator/devices/{id}', ...options });

/**
 * Mint a single-use pairing code. The plaintext is returned once and never again
 */
export const operatorIssuePairingCode = <ThrowOnError extends boolean = false>(
  options?: Options<OperatorIssuePairingCodeData, ThrowOnError>
): RequestResult<OperatorIssuePairingCodeResponses, OperatorIssuePairingCodeErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    OperatorIssuePairingCodeResponses,
    OperatorIssuePairingCodeErrors,
    ThrowOnError
  >({
    url: '/operator/pairing/codes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
