// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type {
  DeviceChallengeData,
  DeviceChallengeErrors,
  DeviceChallengeResponses,
  DevicePairData,
  DevicePairErrors,
  DevicePairResponses,
  DeviceRefreshData,
  DeviceRefreshErrors,
  DeviceRefreshResponses,
  HealthData,
  HealthResponses,
  MobileBarcodeLookupData,
  MobileBarcodeLookupErrors,
  MobileBarcodeLookupResponses,
  MobileBootstrapData,
  MobileBootstrapErrors,
  MobileBootstrapResponses,
  MobileContactsCreateMerchantAddressData,
  MobileContactsCreateMerchantAddressErrors,
  MobileContactsCreateMerchantAddressResponses,
  MobileContactsCreateMerchantData,
  MobileContactsCreateMerchantErrors,
  MobileContactsCreateMerchantResponses,
  MobileContactsGetMerchantAddressesData,
  MobileContactsGetMerchantAddressesErrors,
  MobileContactsGetMerchantAddressesResponses,
  MobileContactsGetMerchantData,
  MobileContactsGetMerchantErrors,
  MobileContactsGetMerchantResponses,
  MobileContactsSearchMerchantsData,
  MobileContactsSearchMerchantsErrors,
  MobileContactsSearchMerchantsResponses,
  MobileFinanceGetAccountData,
  MobileFinanceGetAccountErrors,
  MobileFinanceGetAccountResponses,
  MobileFinanceGetTransactionData,
  MobileFinanceGetTransactionErrors,
  MobileFinanceGetTransactionResponses,
  MobileFinanceListAccountsData,
  MobileFinanceListAccountsErrors,
  MobileFinanceListAccountsResponses,
  MobileFinanceListTransactionsData,
  MobileFinanceListTransactionsErrors,
  MobileFinanceListTransactionsResponses,
  MobileInventoryCatalogueData,
  MobileInventoryCatalogueErrors,
  MobileInventoryCatalogueResponses,
  MobileInventoryCatalogueRevisionData,
  MobileInventoryCatalogueRevisionErrors,
  MobileInventoryCatalogueRevisionResponses,
  MobileInventoryChangesData,
  MobileInventoryChangesErrors,
  MobileInventoryChangesResponses,
  MobileInventoryGetMediaData,
  MobileInventoryGetMediaErrors,
  MobileInventoryGetMediaResponses,
  MobileInventoryItemHistoryData,
  MobileInventoryItemHistoryErrors,
  MobileInventoryItemHistoryResponses,
  MobileInventoryMutationsData,
  MobileInventoryMutationsErrors,
  MobileInventoryMutationsResponses,
  MobileInventoryPutMediaData,
  MobileInventoryPutMediaErrors,
  MobileInventoryPutMediaResponses,
  MobileInventorySnapshotData,
  MobileInventorySnapshotErrors,
  MobileInventorySnapshotResponses,
  MobileInventorySuggestCodesData,
  MobileInventorySuggestCodesErrors,
  MobileInventorySuggestCodesResponses,
  MobilePurchasesCreateManualPurchaseData,
  MobilePurchasesCreateManualPurchaseErrors,
  MobilePurchasesCreateManualPurchaseResponses,
  MobilePurchasesExtractReceiptData,
  MobilePurchasesExtractReceiptErrors,
  MobilePurchasesExtractReceiptResponses,
  MobilePurchasesGetMonthSummaryData,
  MobilePurchasesGetMonthSummaryErrors,
  MobilePurchasesGetMonthSummaryResponses,
  MobilePurchasesGetPurchaseData,
  MobilePurchasesGetPurchaseErrors,
  MobilePurchasesGetPurchaseResponses,
  MobilePurchasesGetReceiptData,
  MobilePurchasesGetReceiptErrors,
  MobilePurchasesGetReceiptResponses,
  MobilePurchasesGetReceiptThumbnailData,
  MobilePurchasesGetReceiptThumbnailErrors,
  MobilePurchasesGetReceiptThumbnailResponses,
  MobilePurchasesListPurchasesData,
  MobilePurchasesListPurchasesErrors,
  MobilePurchasesListPurchasesResponses,
  MobilePurchasesPurchaseTagsData,
  MobilePurchasesPurchaseTagsErrors,
  MobilePurchasesPurchaseTagsResponses,
  MobilePurchasesSaveReceiptDraftData,
  MobilePurchasesSaveReceiptDraftErrors,
  MobilePurchasesSaveReceiptDraftResponses,
  MobilePurchasesSearchPurchasesData,
  MobilePurchasesSearchPurchasesErrors,
  MobilePurchasesSearchPurchasesResponses,
  MobilePurchasesUpdatePurchaseData,
  MobilePurchasesUpdatePurchaseErrors,
  MobilePurchasesUpdatePurchaseResponses,
  OperatorIssuePairingCodeData,
  OperatorIssuePairingCodeErrors,
  OperatorIssuePairingCodeResponses,
  OperatorListDevicesData,
  OperatorListDevicesErrors,
  OperatorListDevicesResponses,
  OperatorRevokeDeviceData,
  OperatorRevokeDeviceErrors,
  OperatorRevokeDeviceResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Mint a single-use nonce for a refresh. Carries no credential and needs none
 */
export const deviceChallenge = <ThrowOnError extends boolean = false>(
  options?: Options<DeviceChallengeData, ThrowOnError>
): RequestResult<DeviceChallengeResponses, DeviceChallengeErrors, ThrowOnError> =>
  (options?.client ?? client).post<DeviceChallengeResponses, DeviceChallengeErrors, ThrowOnError>({
    url: '/devices/challenge',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Spend a pairing code for a device identity. The tokens are returned once
 */
export const devicePair = <ThrowOnError extends boolean = false>(
  options?: Options<DevicePairData, ThrowOnError>
): RequestResult<DevicePairResponses, DevicePairErrors, ThrowOnError> =>
  (options?.client ?? client).post<DevicePairResponses, DevicePairErrors, ThrowOnError>({
    url: '/devices/pair',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Rotate a refresh token, proving possession of the device key. Detects reuse
 */
export const deviceRefresh = <ThrowOnError extends boolean = false>(
  options?: Options<DeviceRefreshData, ThrowOnError>
): RequestResult<DeviceRefreshResponses, DeviceRefreshErrors, ThrowOnError> =>
  (options?.client ?? client).post<DeviceRefreshResponses, DeviceRefreshErrors, ThrowOnError>({
    url: '/devices/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Liveness shape. Answers without a database round-trip
 */
export const health = <ThrowOnError extends boolean = false>(
  options?: Options<HealthData, ThrowOnError>
): RequestResult<HealthResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({
    url: '/health',
    ...options,
  });

/**
 * Look up book metadata for a scanned barcode
 */
export const mobileBarcodeLookup = <ThrowOnError extends boolean = false>(
  options: Options<MobileBarcodeLookupData, ThrowOnError>
): RequestResult<MobileBarcodeLookupResponses, MobileBarcodeLookupErrors, ThrowOnError> =>
  (options.client ?? client).get<
    MobileBarcodeLookupResponses,
    MobileBarcodeLookupErrors,
    ThrowOnError
  >({ url: '/mobile/barcode/lookup/{code}', ...options });

/**
 * What the app should render, and who the federation says it is talking to
 */
export const mobileBootstrap = <ThrowOnError extends boolean = false>(
  options?: Options<MobileBootstrapData, ThrowOnError>
): RequestResult<MobileBootstrapResponses, MobileBootstrapErrors, ThrowOnError> =>
  (options?.client ?? client).get<MobileBootstrapResponses, MobileBootstrapErrors, ThrowOnError>({
    url: '/mobile/bootstrap',
    ...options,
  });

/**
 * Record a new merchant from the reader's own wording. Idempotent by name: a repeated call with the same name answers the same id rather than a conflict
 */
export const mobileContactsCreateMerchant = <ThrowOnError extends boolean = false>(
  options?: Options<MobileContactsCreateMerchantData, ThrowOnError>
): RequestResult<
  MobileContactsCreateMerchantResponses,
  MobileContactsCreateMerchantErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    MobileContactsCreateMerchantResponses,
    MobileContactsCreateMerchantErrors,
    ThrowOnError
  >({
    url: '/mobile/contacts/merchants',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Merchants matching free text, for the review form's merchant picker — there are hundreds, so matching happens here, not on the phone
 */
export const mobileContactsSearchMerchants = <ThrowOnError extends boolean = false>(
  options: Options<MobileContactsSearchMerchantsData, ThrowOnError>
): RequestResult<
  MobileContactsSearchMerchantsResponses,
  MobileContactsSearchMerchantsErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileContactsSearchMerchantsResponses,
    MobileContactsSearchMerchantsErrors,
    ThrowOnError
  >({ url: '/mobile/contacts/merchants/search', ...options });

/**
 * One merchant by id, for a draft that arrives already matched
 */
export const mobileContactsGetMerchant = <ThrowOnError extends boolean = false>(
  options: Options<MobileContactsGetMerchantData, ThrowOnError>
): RequestResult<
  MobileContactsGetMerchantResponses,
  MobileContactsGetMerchantErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileContactsGetMerchantResponses,
    MobileContactsGetMerchantErrors,
    ThrowOnError
  >({ url: '/mobile/contacts/merchants/{id}', ...options });

/**
 * Every address recorded against one merchant, for the review screen's address picker
 */
export const mobileContactsGetMerchantAddresses = <ThrowOnError extends boolean = false>(
  options: Options<MobileContactsGetMerchantAddressesData, ThrowOnError>
): RequestResult<
  MobileContactsGetMerchantAddressesResponses,
  MobileContactsGetMerchantAddressesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileContactsGetMerchantAddressesResponses,
    MobileContactsGetMerchantAddressesErrors,
    ThrowOnError
  >({ url: '/mobile/contacts/merchants/{id}/addresses', ...options });

/**
 * Record a new address for one merchant, typed by the reviewer
 */
export const mobileContactsCreateMerchantAddress = <ThrowOnError extends boolean = false>(
  options: Options<MobileContactsCreateMerchantAddressData, ThrowOnError>
): RequestResult<
  MobileContactsCreateMerchantAddressResponses,
  MobileContactsCreateMerchantAddressErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    MobileContactsCreateMerchantAddressResponses,
    MobileContactsCreateMerchantAddressErrors,
    ThrowOnError
  >({
    url: '/mobile/contacts/merchants/{id}/addresses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Every account this device can read, active and archived alike
 */
export const mobileFinanceListAccounts = <ThrowOnError extends boolean = false>(
  options?: Options<MobileFinanceListAccountsData, ThrowOnError>
): RequestResult<
  MobileFinanceListAccountsResponses,
  MobileFinanceListAccountsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    MobileFinanceListAccountsResponses,
    MobileFinanceListAccountsErrors,
    ThrowOnError
  >({ url: '/mobile/finance/accounts', ...options });

/**
 * One account and its month-end balance history, for the dashboard screen
 */
export const mobileFinanceGetAccount = <ThrowOnError extends boolean = false>(
  options: Options<MobileFinanceGetAccountData, ThrowOnError>
): RequestResult<MobileFinanceGetAccountResponses, MobileFinanceGetAccountErrors, ThrowOnError> =>
  (options.client ?? client).get<
    MobileFinanceGetAccountResponses,
    MobileFinanceGetAccountErrors,
    ThrowOnError
  >({ url: '/mobile/finance/accounts/{id}', ...options });

/**
 * One cursor-paginated page of transaction list rows
 */
export const mobileFinanceListTransactions = <ThrowOnError extends boolean = false>(
  options?: Options<MobileFinanceListTransactionsData, ThrowOnError>
): RequestResult<
  MobileFinanceListTransactionsResponses,
  MobileFinanceListTransactionsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    MobileFinanceListTransactionsResponses,
    MobileFinanceListTransactionsErrors,
    ThrowOnError
  >({ url: '/mobile/finance/transactions', ...options });

/**
 * The fuller record behind one list row, for the detail screen
 */
export const mobileFinanceGetTransaction = <ThrowOnError extends boolean = false>(
  options: Options<MobileFinanceGetTransactionData, ThrowOnError>
): RequestResult<
  MobileFinanceGetTransactionResponses,
  MobileFinanceGetTransactionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileFinanceGetTransactionResponses,
    MobileFinanceGetTransactionErrors,
    ThrowOnError
  >({ url: '/mobile/finance/transactions/{id}', ...options });

/**
 * Free codes for a new item: a stem followed by the next unused numbers
 */
export const mobileInventorySuggestCodes = <ThrowOnError extends boolean = false>(
  options?: Options<MobileInventorySuggestCodesData, ThrowOnError>
): RequestResult<
  MobileInventorySuggestCodesResponses,
  MobileInventorySuggestCodesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    MobileInventorySuggestCodesResponses,
    MobileInventorySuggestCodesErrors,
    ThrowOnError
  >({
    url: '/mobile/inventory/codes/suggest',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * One item's history, newest first
 */
export const mobileInventoryItemHistory = <ThrowOnError extends boolean = false>(
  options: Options<MobileInventoryItemHistoryData, ThrowOnError>
): RequestResult<
  MobileInventoryItemHistoryResponses,
  MobileInventoryItemHistoryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileInventoryItemHistoryResponses,
    MobileInventoryItemHistoryErrors,
    ThrowOnError
  >({ url: '/mobile/inventory/items/{id}/history', ...options });

/**
 * A photo's bytes, base64, for a detail screen or a thumbnail row
 */
export const mobileInventoryGetMedia = <ThrowOnError extends boolean = false>(
  options: Options<MobileInventoryGetMediaData, ThrowOnError>
): RequestResult<MobileInventoryGetMediaResponses, MobileInventoryGetMediaErrors, ThrowOnError> =>
  (options.client ?? client).get<
    MobileInventoryGetMediaResponses,
    MobileInventoryGetMediaErrors,
    ThrowOnError
  >({ url: '/mobile/inventory/media/{sha256}', ...options });

/**
 * Store a photo's bytes, content-addressed by their own sha256
 */
export const mobileInventoryPutMedia = <ThrowOnError extends boolean = false>(
  options: Options<MobileInventoryPutMediaData, ThrowOnError>
): RequestResult<MobileInventoryPutMediaResponses, MobileInventoryPutMediaErrors, ThrowOnError> =>
  (options.client ?? client).put<
    MobileInventoryPutMediaResponses,
    MobileInventoryPutMediaErrors,
    ThrowOnError
  >({
    url: '/mobile/inventory/media/{sha256}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Apply up to 50 mutations in order, each in its own transaction, idempotently
 */
export const mobileInventoryMutations = <ThrowOnError extends boolean = false>(
  options?: Options<MobileInventoryMutationsData, ThrowOnError>
): RequestResult<MobileInventoryMutationsResponses, MobileInventoryMutationsErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    MobileInventoryMutationsResponses,
    MobileInventoryMutationsErrors,
    ThrowOnError
  >({
    url: '/mobile/inventory/mutations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Rows and events changed after `since`, tombstones included, in seq order
 */
export const mobileInventoryChanges = <ThrowOnError extends boolean = false>(
  options: Options<MobileInventoryChangesData, ThrowOnError>
): RequestResult<MobileInventoryChangesResponses, MobileInventoryChangesErrors, ThrowOnError> =>
  (options.client ?? client).get<
    MobileInventoryChangesResponses,
    MobileInventoryChangesErrors,
    ThrowOnError
  >({ url: '/mobile/inventory/sync/changes', ...options });

/**
 * One page of live items and locations; the first page fixes the high-water seq the feed resumes from
 */
export const mobileInventorySnapshot = <ThrowOnError extends boolean = false>(
  options?: Options<MobileInventorySnapshotData, ThrowOnError>
): RequestResult<MobileInventorySnapshotResponses, MobileInventorySnapshotErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    MobileInventorySnapshotResponses,
    MobileInventorySnapshotErrors,
    ThrowOnError
  >({ url: '/mobile/inventory/sync/snapshot', ...options });

/**
 * One exact immutable catalogue revision required by protocol-2 item rows
 */
export const mobileInventoryCatalogueRevision = <ThrowOnError extends boolean = false>(
  options: Options<MobileInventoryCatalogueRevisionData, ThrowOnError>
): RequestResult<
  MobileInventoryCatalogueRevisionResponses,
  MobileInventoryCatalogueRevisionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobileInventoryCatalogueRevisionResponses,
    MobileInventoryCatalogueRevisionErrors,
    ThrowOnError
  >({ url: '/mobile/inventory/type-catalogue', ...options });

/**
 * The type catalogue: every type, field and unit the app needs to render an item
 */
export const mobileInventoryCatalogue = <ThrowOnError extends boolean = false>(
  options?: Options<MobileInventoryCatalogueData, ThrowOnError>
): RequestResult<MobileInventoryCatalogueResponses, MobileInventoryCatalogueErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    MobileInventoryCatalogueResponses,
    MobileInventoryCatalogueErrors,
    ThrowOnError
  >({ url: '/mobile/inventory/types', ...options });

/**
 * One cursor-paginated page of purchase list rows
 */
export const mobilePurchasesListPurchases = <ThrowOnError extends boolean = false>(
  options?: Options<MobilePurchasesListPurchasesData, ThrowOnError>
): RequestResult<
  MobilePurchasesListPurchasesResponses,
  MobilePurchasesListPurchasesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    MobilePurchasesListPurchasesResponses,
    MobilePurchasesListPurchasesErrors,
    ThrowOnError
  >({ url: '/mobile/purchases', ...options });

/**
 * Create a purchase typed by hand, with no receipt
 */
export const mobilePurchasesCreateManualPurchase = <ThrowOnError extends boolean = false>(
  options?: Options<MobilePurchasesCreateManualPurchaseData, ThrowOnError>
): RequestResult<
  MobilePurchasesCreateManualPurchaseResponses,
  MobilePurchasesCreateManualPurchaseErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    MobilePurchasesCreateManualPurchaseResponses,
    MobilePurchasesCreateManualPurchaseErrors,
    ThrowOnError
  >({
    url: '/mobile/purchases/manual',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Save a reviewed, possibly corrected receipt-derived draft as a purchase
 */
export const mobilePurchasesSaveReceiptDraft = <ThrowOnError extends boolean = false>(
  options?: Options<MobilePurchasesSaveReceiptDraftData, ThrowOnError>
): RequestResult<
  MobilePurchasesSaveReceiptDraftResponses,
  MobilePurchasesSaveReceiptDraftErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    MobilePurchasesSaveReceiptDraftResponses,
    MobilePurchasesSaveReceiptDraftErrors,
    ThrowOnError
  >({
    url: '/mobile/purchases/receipts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Read a photographed, scanned or pasted receipt into an editable draft
 */
export const mobilePurchasesExtractReceipt = <ThrowOnError extends boolean = false>(
  options?: Options<MobilePurchasesExtractReceiptData, ThrowOnError>
): RequestResult<
  MobilePurchasesExtractReceiptResponses,
  MobilePurchasesExtractReceiptErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    MobilePurchasesExtractReceiptResponses,
    MobilePurchasesExtractReceiptErrors,
    ThrowOnError
  >({
    url: '/mobile/purchases/receipts/extract',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * The receipt itself, full size, for a detail screen
 */
export const mobilePurchasesGetReceipt = <ThrowOnError extends boolean = false>(
  options: Options<MobilePurchasesGetReceiptData, ThrowOnError>
): RequestResult<
  MobilePurchasesGetReceiptResponses,
  MobilePurchasesGetReceiptErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobilePurchasesGetReceiptResponses,
    MobilePurchasesGetReceiptErrors,
    ThrowOnError
  >({ url: '/mobile/purchases/receipts/{sha256}', ...options });

/**
 * The list-sized image behind a row’s receiptUri
 */
export const mobilePurchasesGetReceiptThumbnail = <ThrowOnError extends boolean = false>(
  options: Options<MobilePurchasesGetReceiptThumbnailData, ThrowOnError>
): RequestResult<
  MobilePurchasesGetReceiptThumbnailResponses,
  MobilePurchasesGetReceiptThumbnailErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobilePurchasesGetReceiptThumbnailResponses,
    MobilePurchasesGetReceiptThumbnailErrors,
    ThrowOnError
  >({ url: '/mobile/purchases/receipts/{sha256}/thumbnail', ...options });

/**
 * Search purchases and their line items by merchant, product name or item tag
 */
export const mobilePurchasesSearchPurchases = <ThrowOnError extends boolean = false>(
  options: Options<MobilePurchasesSearchPurchasesData, ThrowOnError>
): RequestResult<
  MobilePurchasesSearchPurchasesResponses,
  MobilePurchasesSearchPurchasesErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobilePurchasesSearchPurchasesResponses,
    MobilePurchasesSearchPurchasesErrors,
    ThrowOnError
  >({ url: '/mobile/purchases/search', ...options });

/**
 * The home screen figures for one calendar month
 */
export const mobilePurchasesGetMonthSummary = <ThrowOnError extends boolean = false>(
  options: Options<MobilePurchasesGetMonthSummaryData, ThrowOnError>
): RequestResult<
  MobilePurchasesGetMonthSummaryResponses,
  MobilePurchasesGetMonthSummaryErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobilePurchasesGetMonthSummaryResponses,
    MobilePurchasesGetMonthSummaryErrors,
    ThrowOnError
  >({ url: '/mobile/purchases/summary', ...options });

/**
 * The item tag vocabulary in use, most-used first, for the search filter sheet
 */
export const mobilePurchasesPurchaseTags = <ThrowOnError extends boolean = false>(
  options?: Options<MobilePurchasesPurchaseTagsData, ThrowOnError>
): RequestResult<
  MobilePurchasesPurchaseTagsResponses,
  MobilePurchasesPurchaseTagsErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    MobilePurchasesPurchaseTagsResponses,
    MobilePurchasesPurchaseTagsErrors,
    ThrowOnError
  >({ url: '/mobile/purchases/tags', ...options });

/**
 * The fuller record behind one list row, with its lines
 */
export const mobilePurchasesGetPurchase = <ThrowOnError extends boolean = false>(
  options: Options<MobilePurchasesGetPurchaseData, ThrowOnError>
): RequestResult<
  MobilePurchasesGetPurchaseResponses,
  MobilePurchasesGetPurchaseErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    MobilePurchasesGetPurchaseResponses,
    MobilePurchasesGetPurchaseErrors,
    ThrowOnError
  >({ url: '/mobile/purchases/{id}', ...options });

/**
 * Edit a saved purchase
 */
export const mobilePurchasesUpdatePurchase = <ThrowOnError extends boolean = false>(
  options: Options<MobilePurchasesUpdatePurchaseData, ThrowOnError>
): RequestResult<
  MobilePurchasesUpdatePurchaseResponses,
  MobilePurchasesUpdatePurchaseErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    MobilePurchasesUpdatePurchaseResponses,
    MobilePurchasesUpdatePurchaseErrors,
    ThrowOnError
  >({
    url: '/mobile/purchases/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List paired devices, revoked ones included. Never returns a token or a key
 */
export const operatorListDevices = <ThrowOnError extends boolean = false>(
  options?: Options<OperatorListDevicesData, ThrowOnError>
): RequestResult<OperatorListDevicesResponses, OperatorListDevicesErrors, ThrowOnError> =>
  (options?.client ?? client).get<
    OperatorListDevicesResponses,
    OperatorListDevicesErrors,
    ThrowOnError
  >({ url: '/operator/devices', ...options });

/**
 * Soft-revoke a device and kill its refresh-token family in one transaction
 */
export const operatorRevokeDevice = <ThrowOnError extends boolean = false>(
  options: Options<OperatorRevokeDeviceData, ThrowOnError>
): RequestResult<OperatorRevokeDeviceResponses, OperatorRevokeDeviceErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    OperatorRevokeDeviceResponses,
    OperatorRevokeDeviceErrors,
    ThrowOnError
  >({ url: '/operator/devices/{id}', ...options });

/**
 * Mint a single-use pairing code. The plaintext is returned once and never again
 */
export const operatorIssuePairingCode = <ThrowOnError extends boolean = false>(
  options?: Options<OperatorIssuePairingCodeData, ThrowOnError>
): RequestResult<OperatorIssuePairingCodeResponses, OperatorIssuePairingCodeErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    OperatorIssuePairingCodeResponses,
    OperatorIssuePairingCodeErrors,
    ThrowOnError
  >({
    url: '/operator/pairing/codes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
