// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type DeviceChallengeData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path?: never;
  query?: never;
  url: '/devices/challenge';
};

export type DeviceChallengeErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_request';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type DeviceChallengeError = DeviceChallengeErrors[keyof DeviceChallengeErrors];

export type DeviceChallengeResponses = {
  /**
   * 201
   */
  201: {
    expiresIn: number;
    nonce: string;
  };
};

export type DeviceChallengeResponse = DeviceChallengeResponses[keyof DeviceChallengeResponses];

export type DevicePairData = {
  /**
   * Body
   */
  body?: {
    code: string;
    deviceModel: string;
    deviceName: string;
    publicKey: string;
  };
  path?: never;
  query?: never;
  url: '/devices/pair';
};

export type DevicePairErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_request';
    message: string;
  };
  /**
   * 403
   */
  403: {
    code: 'pairing_rejected';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type DevicePairError = DevicePairErrors[keyof DevicePairErrors];

export type DevicePairResponses = {
  /**
   * 201
   */
  201: {
    accessToken: string;
    deviceId: string;
    expiresIn: number;
    refreshToken: string;
  };
};

export type DevicePairResponse = DevicePairResponses[keyof DevicePairResponses];

export type DeviceRefreshData = {
  /**
   * Body
   */
  body?: {
    nonce: string;
    refreshToken: string;
    signature: string;
  };
  path?: never;
  query?: never;
  url: '/devices/refresh';
};

export type DeviceRefreshErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'challenge_expired' | 'invalid_grant';
    message: string;
  };
  /**
   * 403
   */
  403: {
    code: 'device_revoked';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type DeviceRefreshError = DeviceRefreshErrors[keyof DeviceRefreshErrors];

export type DeviceRefreshResponses = {
  /**
   * 200
   */
  200: {
    accessToken: string;
    expiresIn: number;
    refreshToken: string;
  };
};

export type DeviceRefreshResponse = DeviceRefreshResponses[keyof DeviceRefreshResponses];

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
    pillar: 'bfm';
    status: 'ok';
    ts: string;
    version: string;
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type MobileBootstrapData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mobile/bootstrap';
};

export type MobileBootstrapErrors = {
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type MobileBootstrapError = MobileBootstrapErrors[keyof MobileBootstrapErrors];

export type MobileBootstrapResponses = {
  /**
   * 200
   */
  200: {
    device: {
      capabilities: Array<string>;
      id: string;
      lastSeenAt: string;
      name: string;
    };
    features: Array<{
      id: string;
      reachability: 'healthy' | 'degraded' | 'unavailable' | 'contract-mismatch';
    }>;
    pillars: Array<{
      id: string;
      reachability: 'healthy' | 'degraded' | 'unavailable' | 'contract-mismatch';
    }>;
    registry: {
      source: 'fresh' | 'cached' | 'stale-fallback' | 'unavailable';
    };
  };
};

export type MobileBootstrapResponse = MobileBootstrapResponses[keyof MobileBootstrapResponses];

export type MobileFinanceListAccountsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mobile/finance/accounts';
};

export type MobileFinanceListAccountsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceListAccountsError =
  MobileFinanceListAccountsErrors[keyof MobileFinanceListAccountsErrors];

export type MobileFinanceListAccountsResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      archived: boolean;
      balance: {
        asOf: string;
        balanceCents: number;
        basis: 'checkpoint' | 'transactions';
        inconsistent: boolean;
      };
      contact: string | null;
      currency: string;
      id: string;
      institutionId: string | null;
      institutionName: string | null;
      kind: string;
      name: string;
      transactionCount: number;
    }>;
  };
};

export type MobileFinanceListAccountsResponse =
  MobileFinanceListAccountsResponses[keyof MobileFinanceListAccountsResponses];

export type MobileFinanceGetAccountData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/finance/accounts/{id}';
};

export type MobileFinanceGetAccountErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceGetAccountError =
  MobileFinanceGetAccountErrors[keyof MobileFinanceGetAccountErrors];

export type MobileFinanceGetAccountResponses = {
  /**
   * 200
   */
  200: {
    account: {
      archived: boolean;
      balance: {
        asOf: string;
        balanceCents: number;
        basis: 'checkpoint' | 'transactions';
        inconsistent: boolean;
      };
      contact: string | null;
      currency: string;
      id: string;
      institutionId: string | null;
      institutionName: string | null;
      kind: string;
      name: string;
      transactionCount: number;
    };
    history: Array<{
      balanceCents: number;
      month: string;
    }>;
  };
};

export type MobileFinanceGetAccountResponse =
  MobileFinanceGetAccountResponses[keyof MobileFinanceGetAccountResponses];

export type MobileFinanceListTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    cursor?: string;
    accountId?: string;
  };
  url: '/mobile/finance/transactions';
};

export type MobileFinanceListTransactionsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceListTransactionsError =
  MobileFinanceListTransactionsErrors[keyof MobileFinanceListTransactionsErrors];

export type MobileFinanceListTransactionsResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      amount: number;
      currency: string;
      date: string;
      description: string;
      entityName: string | null;
      id: string;
      tags: Array<string>;
      type: string;
    }>;
    nextCursor: string | null;
  };
};

export type MobileFinanceListTransactionsResponse =
  MobileFinanceListTransactionsResponses[keyof MobileFinanceListTransactionsResponses];

export type MobileFinanceGetTransactionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/finance/transactions/{id}';
};

export type MobileFinanceGetTransactionErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceGetTransactionError =
  MobileFinanceGetTransactionErrors[keyof MobileFinanceGetTransactionErrors];

export type MobileFinanceGetTransactionResponses = {
  /**
   * 200
   */
  200: {
    account: string;
    amount: number;
    country: string | null;
    currency: string;
    date: string;
    description: string;
    entityId: string | null;
    entityName: string | null;
    id: string;
    lastEditedTime: string;
    location: string | null;
    notes: string | null;
    relatedTransactionId: string | null;
    tags: Array<string>;
    type: string;
  };
};

export type MobileFinanceGetTransactionResponse =
  MobileFinanceGetTransactionResponses[keyof MobileFinanceGetTransactionResponses];

export type MobilePurchasesListPurchasesData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/mobile/purchases';
};

export type MobilePurchasesListPurchasesErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesListPurchasesError =
  MobilePurchasesListPurchasesErrors[keyof MobilePurchasesListPurchasesErrors];

export type MobilePurchasesListPurchasesResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      currency: string;
      id: string;
      itemCount: number;
      merchantName: string | null;
      orderedOn: string;
      receiptUri: string | null;
      status: string;
      totalCents: number;
    }>;
    nextCursor: string | null;
  };
};

export type MobilePurchasesListPurchasesResponse =
  MobilePurchasesListPurchasesResponses[keyof MobilePurchasesListPurchasesResponses];

export type MobilePurchasesCreateManualPurchaseData = {
  /**
   * Body
   */
  body?: {
    capture?: {
      capturedAt: string | null;
      capturedAtSource: 'client' | 'exif' | null;
      declaredTimeZone: string | null;
      latitude: number | null;
      locationSource: 'client' | 'exif' | null;
      longitude: number | null;
      utcOffsetMinutes: number | null;
    } | null;
    currency: string;
    discountCents?: number;
    idempotencyKey: string;
    items: Array<{
      lineTotalCents: number;
      name: string;
      notes: Array<string>;
      quantity: number | null;
      unitPriceCents: number;
    }>;
    merchantName: string | null;
    orderedAt: string;
    orderedAtOffsetMinutes?: number | null;
    shippingCents?: number;
    surchargeCents?: number;
    taxCents?: number;
    totalCents: number;
  };
  path?: never;
  query?: never;
  url: '/mobile/purchases/manual';
};

export type MobilePurchasesCreateManualPurchaseErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesCreateManualPurchaseError =
  MobilePurchasesCreateManualPurchaseErrors[keyof MobilePurchasesCreateManualPurchaseErrors];

export type MobilePurchasesCreateManualPurchaseResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    id: string;
    itemCount: number;
    items: Array<{
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
  };
};

export type MobilePurchasesCreateManualPurchaseResponse =
  MobilePurchasesCreateManualPurchaseResponses[keyof MobilePurchasesCreateManualPurchaseResponses];

export type MobilePurchasesSaveReceiptDraftData = {
  /**
   * Body
   */
  body?: {
    capture?: {
      capturedAt: string | null;
      capturedAtSource: 'client' | 'exif' | null;
      declaredTimeZone: string | null;
      latitude: number | null;
      locationSource: 'client' | 'exif' | null;
      longitude: number | null;
      utcOffsetMinutes: number | null;
    } | null;
    currency: string;
    discountCents?: number;
    documents: Array<{
      documentUri: string;
      kind: 'receipt';
    }>;
    idempotencyKey: string;
    items: Array<{
      lineTotalCents: number;
      name: string;
      notes: Array<string>;
      quantity: number | null;
      unitPriceCents: number;
    }>;
    merchantName: string | null;
    orderedAt: string;
    orderedAtOffsetMinutes?: number | null;
    shippingCents?: number;
    surchargeCents?: number;
    taxCents?: number;
    totalCents: number;
  };
  path?: never;
  query?: never;
  url: '/mobile/purchases/receipts';
};

export type MobilePurchasesSaveReceiptDraftErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesSaveReceiptDraftError =
  MobilePurchasesSaveReceiptDraftErrors[keyof MobilePurchasesSaveReceiptDraftErrors];

export type MobilePurchasesSaveReceiptDraftResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    id: string;
    itemCount: number;
    items: Array<{
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
  };
};

export type MobilePurchasesSaveReceiptDraftResponse =
  MobilePurchasesSaveReceiptDraftResponses[keyof MobilePurchasesSaveReceiptDraftResponses];

export type MobilePurchasesExtractReceiptData = {
  /**
   * Body
   */
  body?: {
    capture?: {
      capturedAt?: string;
      location?: {
        latitude: number;
        longitude: number;
      };
      timeZone?: string;
    };
    parts: Array<{
      dataBase64: string;
      mediaType:
        | 'image/jpeg'
        | 'image/png'
        | 'image/webp'
        | 'image/gif'
        | 'application/pdf'
        | 'text/plain';
    }>;
  };
  path?: never;
  query?: never;
  url: '/mobile/purchases/receipts/extract';
};

export type MobilePurchasesExtractReceiptErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 413
   */
  413: {
    code: 'payload_too_large';
    maxBytes: number;
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesExtractReceiptError =
  MobilePurchasesExtractReceiptErrors[keyof MobilePurchasesExtractReceiptErrors];

export type MobilePurchasesExtractReceiptResponses = {
  /**
   * 200
   */
  200:
    | {
        draft: {
          capture: {
            capturedAt: string | null;
            capturedAtSource: 'client' | 'exif' | null;
            declaredTimeZone: string | null;
            latitude: number | null;
            locationSource: 'client' | 'exif' | null;
            longitude: number | null;
            utcOffsetMinutes: number | null;
          } | null;
          currency: string;
          discountCents: number;
          documents: Array<{
            documentUri: string;
            kind: 'receipt';
          }>;
          items: Array<{
            lineTotalCents: number;
            name: string;
            notes: Array<string>;
            quantity: number | null;
            unitPriceCents: number;
          }>;
          merchantName: string | null;
          orderedAt: string;
          orderedAtOffsetMinutes: number | null;
          shippingCents: number;
          subtotalCents: number;
          surchargeCents: number;
          taxCents: number;
          totalCents: number;
        };
        failures: Array<{
          code: string;
          deltaCents: number | null;
          detail: string;
        }>;
        kind: 'draft';
        receiptUris: Array<string>;
        reconciled: boolean;
      }
    | {
        kind: 'unreadable';
        reason: string;
        receiptUris: Array<string>;
      };
};

export type MobilePurchasesExtractReceiptResponse =
  MobilePurchasesExtractReceiptResponses[keyof MobilePurchasesExtractReceiptResponses];

export type MobilePurchasesGetReceiptData = {
  body?: never;
  path: {
    sha256: string;
  };
  query?: never;
  url: '/mobile/purchases/receipts/{sha256}';
};

export type MobilePurchasesGetReceiptErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetReceiptError =
  MobilePurchasesGetReceiptErrors[keyof MobilePurchasesGetReceiptErrors];

export type MobilePurchasesGetReceiptResponses = {
  /**
   * 200
   */
  200: {
    byteLength: number;
    dataBase64: string;
    mediaType: string;
    sha256: string;
  };
};

export type MobilePurchasesGetReceiptResponse =
  MobilePurchasesGetReceiptResponses[keyof MobilePurchasesGetReceiptResponses];

export type MobilePurchasesGetReceiptThumbnailData = {
  body?: never;
  path: {
    sha256: string;
  };
  query?: never;
  url: '/mobile/purchases/receipts/{sha256}/thumbnail';
};

export type MobilePurchasesGetReceiptThumbnailErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 415
   */
  415: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetReceiptThumbnailError =
  MobilePurchasesGetReceiptThumbnailErrors[keyof MobilePurchasesGetReceiptThumbnailErrors];

export type MobilePurchasesGetReceiptThumbnailResponses = {
  /**
   * 200
   */
  200: {
    byteLength: number;
    dataBase64: string;
    mediaType: string;
    sha256: string;
  };
};

export type MobilePurchasesGetReceiptThumbnailResponse =
  MobilePurchasesGetReceiptThumbnailResponses[keyof MobilePurchasesGetReceiptThumbnailResponses];

export type MobilePurchasesGetPurchaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/purchases/{id}';
};

export type MobilePurchasesGetPurchaseErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetPurchaseError =
  MobilePurchasesGetPurchaseErrors[keyof MobilePurchasesGetPurchaseErrors];

export type MobilePurchasesGetPurchaseResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    id: string;
    itemCount: number;
    items: Array<{
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
  };
};

export type MobilePurchasesGetPurchaseResponse =
  MobilePurchasesGetPurchaseResponses[keyof MobilePurchasesGetPurchaseResponses];

export type OperatorListDevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/operator/devices';
};

export type OperatorListDevicesErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
};

export type OperatorListDevicesError = OperatorListDevicesErrors[keyof OperatorListDevicesErrors];

export type OperatorListDevicesResponses = {
  /**
   * 200
   */
  200: {
    devices: Array<{
      createdAt: string;
      id: string;
      lastSeenAt: string;
      model: string;
      name: string;
      revokedAt: string | null;
    }>;
  };
};

export type OperatorListDevicesResponse =
  OperatorListDevicesResponses[keyof OperatorListDevicesResponses];

export type OperatorRevokeDeviceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/operator/devices/{id}';
};

export type OperatorRevokeDeviceErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code: string;
    message: string;
  };
};

export type OperatorRevokeDeviceError =
  OperatorRevokeDeviceErrors[keyof OperatorRevokeDeviceErrors];

export type OperatorRevokeDeviceResponses = {
  /**
   * 200
   */
  200: {
    alreadyRevoked: boolean;
    id: string;
    revokedAt: string;
  };
};

export type OperatorRevokeDeviceResponse =
  OperatorRevokeDeviceResponses[keyof OperatorRevokeDeviceResponses];

export type OperatorIssuePairingCodeData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path?: never;
  query?: never;
  url: '/operator/pairing/codes';
};

export type OperatorIssuePairingCodeErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: string;
    message: string;
  };
};

export type OperatorIssuePairingCodeError =
  OperatorIssuePairingCodeErrors[keyof OperatorIssuePairingCodeErrors];

export type OperatorIssuePairingCodeResponses = {
  /**
   * 201
   */
  201: {
    code: string;
    expiresAt: string;
    pairingUrl: string;
  };
};

export type OperatorIssuePairingCodeResponse =
  OperatorIssuePairingCodeResponses[keyof OperatorIssuePairingCodeResponses];
