// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type DeviceChallengeData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path?: never;
  query?: never;
  url: '/devices/challenge';
};

export type DeviceChallengeErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_request';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type DeviceChallengeError = DeviceChallengeErrors[keyof DeviceChallengeErrors];

export type DeviceChallengeResponses = {
  /**
   * 201
   */
  201: {
    expiresIn: number;
    nonce: string;
  };
};

export type DeviceChallengeResponse = DeviceChallengeResponses[keyof DeviceChallengeResponses];

export type DevicePairData = {
  /**
   * Body
   */
  body?: {
    code: string;
    deviceModel: string;
    deviceName: string;
    publicKey: string;
  };
  path?: never;
  query?: never;
  url: '/devices/pair';
};

export type DevicePairErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_request';
    message: string;
  };
  /**
   * 403
   */
  403: {
    code: 'pairing_rejected';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type DevicePairError = DevicePairErrors[keyof DevicePairErrors];

export type DevicePairResponses = {
  /**
   * 201
   */
  201: {
    accessToken: string;
    deviceId: string;
    expiresIn: number;
    refreshToken: string;
  };
};

export type DevicePairResponse = DevicePairResponses[keyof DevicePairResponses];

export type DeviceRefreshData = {
  /**
   * Body
   */
  body?: {
    nonce: string;
    refreshToken: string;
    signature: string;
  };
  path?: never;
  query?: never;
  url: '/devices/refresh';
};

export type DeviceRefreshErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'challenge_expired' | 'invalid_grant';
    message: string;
  };
  /**
   * 403
   */
  403: {
    code: 'device_revoked';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type DeviceRefreshError = DeviceRefreshErrors[keyof DeviceRefreshErrors];

export type DeviceRefreshResponses = {
  /**
   * 200
   */
  200: {
    accessToken: string;
    expiresIn: number;
    refreshToken: string;
  };
};

export type DeviceRefreshResponse = DeviceRefreshResponses[keyof DeviceRefreshResponses];

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
    pillar: 'bfm';
    status: 'ok';
    ts: string;
    version: string;
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type MobileBootstrapData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mobile/bootstrap';
};

export type MobileBootstrapErrors = {
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
};

export type MobileBootstrapError = MobileBootstrapErrors[keyof MobileBootstrapErrors];

export type MobileBootstrapResponses = {
  /**
   * 200
   */
  200: {
    device: {
      capabilities: Array<string>;
      id: string;
      lastSeenAt: string;
      name: string;
    };
    features: Array<{
      id: string;
      reachability: 'healthy' | 'degraded' | 'unavailable' | 'contract-mismatch';
    }>;
    pillars: Array<{
      id: string;
      reachability: 'healthy' | 'degraded' | 'unavailable' | 'contract-mismatch';
    }>;
    registry: {
      source: 'fresh' | 'cached' | 'stale-fallback' | 'unavailable';
    };
  };
};

export type MobileBootstrapResponse = MobileBootstrapResponses[keyof MobileBootstrapResponses];

export type MobileContactsCreateMerchantData = {
  /**
   * Body
   */
  body?: {
    name: string;
  };
  path?: never;
  query?: never;
  url: '/mobile/contacts/merchants';
};

export type MobileContactsCreateMerchantErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileContactsCreateMerchantError =
  MobileContactsCreateMerchantErrors[keyof MobileContactsCreateMerchantErrors];

export type MobileContactsCreateMerchantResponses = {
  /**
   * 200
   */
  200: {
    id: string;
    name: string;
  };
};

export type MobileContactsCreateMerchantResponse =
  MobileContactsCreateMerchantResponses[keyof MobileContactsCreateMerchantResponses];

export type MobileContactsSearchMerchantsData = {
  body?: never;
  path?: never;
  query: {
    q: string;
    limit?: number;
  };
  url: '/mobile/contacts/merchants/search';
};

export type MobileContactsSearchMerchantsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileContactsSearchMerchantsError =
  MobileContactsSearchMerchantsErrors[keyof MobileContactsSearchMerchantsErrors];

export type MobileContactsSearchMerchantsResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      id: string;
      name: string;
    }>;
  };
};

export type MobileContactsSearchMerchantsResponse =
  MobileContactsSearchMerchantsResponses[keyof MobileContactsSearchMerchantsResponses];

export type MobileContactsGetMerchantData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/contacts/merchants/{id}';
};

export type MobileContactsGetMerchantErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileContactsGetMerchantError =
  MobileContactsGetMerchantErrors[keyof MobileContactsGetMerchantErrors];

export type MobileContactsGetMerchantResponses = {
  /**
   * 200
   */
  200: {
    id: string;
    name: string;
  };
};

export type MobileContactsGetMerchantResponse =
  MobileContactsGetMerchantResponses[keyof MobileContactsGetMerchantResponses];

export type MobileContactsGetMerchantAddressesData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/contacts/merchants/{id}/addresses';
};

export type MobileContactsGetMerchantAddressesErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileContactsGetMerchantAddressesError =
  MobileContactsGetMerchantAddressesErrors[keyof MobileContactsGetMerchantAddressesErrors];

export type MobileContactsGetMerchantAddressesResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      id: string;
      value: string;
    }>;
  };
};

export type MobileContactsGetMerchantAddressesResponse =
  MobileContactsGetMerchantAddressesResponses[keyof MobileContactsGetMerchantAddressesResponses];

export type MobileContactsCreateMerchantAddressData = {
  /**
   * Body
   */
  body?: {
    value: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/contacts/merchants/{id}/addresses';
};

export type MobileContactsCreateMerchantAddressErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileContactsCreateMerchantAddressError =
  MobileContactsCreateMerchantAddressErrors[keyof MobileContactsCreateMerchantAddressErrors];

export type MobileContactsCreateMerchantAddressResponses = {
  /**
   * 200
   */
  200: {
    id: string;
    value: string;
  };
};

export type MobileContactsCreateMerchantAddressResponse =
  MobileContactsCreateMerchantAddressResponses[keyof MobileContactsCreateMerchantAddressResponses];

export type MobileFinanceListAccountsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mobile/finance/accounts';
};

export type MobileFinanceListAccountsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceListAccountsError =
  MobileFinanceListAccountsErrors[keyof MobileFinanceListAccountsErrors];

export type MobileFinanceListAccountsResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      archived: boolean;
      balance: {
        asOf: string;
        balanceCents: number;
        basis: 'checkpoint' | 'transactions';
        inconsistent: boolean;
      };
      contact: string | null;
      currency: string;
      id: string;
      institutionId: string | null;
      institutionName: string | null;
      kind: string;
      name: string;
      transactionCount: number;
    }>;
  };
};

export type MobileFinanceListAccountsResponse =
  MobileFinanceListAccountsResponses[keyof MobileFinanceListAccountsResponses];

export type MobileFinanceGetAccountData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/finance/accounts/{id}';
};

export type MobileFinanceGetAccountErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceGetAccountError =
  MobileFinanceGetAccountErrors[keyof MobileFinanceGetAccountErrors];

export type MobileFinanceGetAccountResponses = {
  /**
   * 200
   */
  200: {
    account: {
      archived: boolean;
      balance: {
        asOf: string;
        balanceCents: number;
        basis: 'checkpoint' | 'transactions';
        inconsistent: boolean;
      };
      contact: string | null;
      currency: string;
      id: string;
      institutionId: string | null;
      institutionName: string | null;
      kind: string;
      name: string;
      transactionCount: number;
    };
    history: Array<{
      balanceCents: number;
      month: string;
    }>;
  };
};

export type MobileFinanceGetAccountResponse =
  MobileFinanceGetAccountResponses[keyof MobileFinanceGetAccountResponses];

export type MobileFinanceListTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    cursor?: string;
    accountId?: string;
  };
  url: '/mobile/finance/transactions';
};

export type MobileFinanceListTransactionsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceListTransactionsError =
  MobileFinanceListTransactionsErrors[keyof MobileFinanceListTransactionsErrors];

export type MobileFinanceListTransactionsResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      amount: number;
      currency: string;
      date: string;
      description: string;
      entityName: string | null;
      id: string;
      tags: Array<string>;
      type: string;
    }>;
    nextCursor: string | null;
  };
};

export type MobileFinanceListTransactionsResponse =
  MobileFinanceListTransactionsResponses[keyof MobileFinanceListTransactionsResponses];

export type MobileFinanceGetTransactionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/finance/transactions/{id}';
};

export type MobileFinanceGetTransactionErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceGetTransactionError =
  MobileFinanceGetTransactionErrors[keyof MobileFinanceGetTransactionErrors];

export type MobileFinanceGetTransactionResponses = {
  /**
   * 200
   */
  200: {
    account: string;
    amount: number;
    country: string | null;
    currency: string;
    date: string;
    description: string;
    entityId: string | null;
    entityName: string | null;
    id: string;
    lastEditedTime: string;
    location: string | null;
    notes: string | null;
    relatedTransactionId: string | null;
    tags: Array<string>;
    type: string;
  };
};

export type MobileFinanceGetTransactionResponse =
  MobileFinanceGetTransactionResponses[keyof MobileFinanceGetTransactionResponses];

export type MobileInventorySuggestCodesData = {
  /**
   * Body
   */
  body?: {
    name: string;
    stem?: string;
    typeKey?: string;
  };
  path?: never;
  query?: never;
  url: '/mobile/inventory/codes/suggest';
};

export type MobileInventorySuggestCodesErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 426
   */
  426: {
    code: 'client_too_old';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventorySuggestCodesError =
  MobileInventorySuggestCodesErrors[keyof MobileInventorySuggestCodesErrors];

export type MobileInventorySuggestCodesResponses = {
  /**
   * 200
   */
  200: {
    suggestions: Array<string>;
  };
};

export type MobileInventorySuggestCodesResponse =
  MobileInventorySuggestCodesResponses[keyof MobileInventorySuggestCodesResponses];

export type MobileInventoryItemHistoryData = {
  body?: never;
  path: {
    id: string;
  };
  query?: {
    cursor?: string;
    limit?: number;
  };
  url: '/mobile/inventory/items/{id}/history';
};

export type MobileInventoryItemHistoryErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 426
   */
  426: {
    code: 'client_too_old';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventoryItemHistoryError =
  MobileInventoryItemHistoryErrors[keyof MobileInventoryItemHistoryErrors];

export type MobileInventoryItemHistoryResponses = {
  /**
   * 200
   */
  200: {
    events: Array<{
      actor: {
        kind: string;
        label: string;
      };
      after: {
        placement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | {
              kind: 'hand';
            };
        previousPlacement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | null;
        [key: string]: unknown;
      };
      before: {
        placement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | {
              kind: 'hand';
            };
        previousPlacement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | null;
        [key: string]: unknown;
      };
      clientTime: string | null;
      compensatesSeq: number | null;
      entityId: string;
      entityKind: 'item' | 'location';
      fields: Array<string>;
      kind: string;
      reason: string | null;
      seq: number;
      serverTime: string;
      undoable: boolean;
    }>;
    nextCursor: string | null;
  };
};

export type MobileInventoryItemHistoryResponse =
  MobileInventoryItemHistoryResponses[keyof MobileInventoryItemHistoryResponses];

export type MobileInventoryGetMediaData = {
  body?: never;
  path: {
    sha256: string;
  };
  query?: {
    variant?: 'full' | 'thumb' | 'medium';
  };
  url: '/mobile/inventory/media/{sha256}';
};

export type MobileInventoryGetMediaErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventoryGetMediaError =
  MobileInventoryGetMediaErrors[keyof MobileInventoryGetMediaErrors];

export type MobileInventoryGetMediaResponses = {
  /**
   * 200
   */
  200: {
    byteLength: number;
    dataBase64: string;
    mediaType: string;
    sha256: string;
  };
};

export type MobileInventoryGetMediaResponse =
  MobileInventoryGetMediaResponses[keyof MobileInventoryGetMediaResponses];

export type MobileInventoryPutMediaData = {
  /**
   * Body
   */
  body?: {
    dataBase64: string;
    mediaType: 'image/jpeg' | 'image/heic';
  };
  path: {
    sha256: string;
  };
  query?: never;
  url: '/mobile/inventory/media/{sha256}';
};

export type MobileInventoryPutMediaErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 413
   */
  413: {
    code: 'payload_too_large';
    maxBytes: number;
    message: string;
  };
  /**
   * 415
   */
  415: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventoryPutMediaError =
  MobileInventoryPutMediaErrors[keyof MobileInventoryPutMediaErrors];

export type MobileInventoryPutMediaResponses = {
  /**
   * 200
   */
  200: {
    alreadyStored: boolean;
    sha256: string;
  };
  /**
   * 201
   */
  201: {
    alreadyStored: boolean;
    sha256: string;
  };
};

export type MobileInventoryPutMediaResponse =
  MobileInventoryPutMediaResponses[keyof MobileInventoryPutMediaResponses];

export type MobileInventoryMutationsData = {
  /**
   * Body
   */
  body?: {
    mutations: Array<{
      args: unknown;
      baseRevision?: number | null;
      catalogueRevision?: number | null;
      clientTime: string;
      dependsOn: Array<string>;
      entityId: string;
      mutationId: string;
      op: string;
    }>;
  };
  path?: never;
  query?: never;
  url: '/mobile/inventory/mutations';
};

export type MobileInventoryMutationsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 413
   */
  413: {
    code: 'payload_too_large';
    maxBytes: number;
    message: string;
  };
  /**
   * 426
   */
  426: {
    code: 'client_too_old';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventoryMutationsError =
  MobileInventoryMutationsErrors[keyof MobileInventoryMutationsErrors];

export type MobileInventoryMutationsResponses = {
  /**
   * 200
   */
  200: {
    highWaterSeq: number;
    outcomes: Array<
      | {
          converged: boolean;
          mutationId: string;
          revision: number;
          seq: number;
          status: 'applied';
        }
      | {
          at: string;
          currentRevision: number;
          field: string;
          kind: 'field';
          mine: unknown;
          mutationId: string;
          source: {
            kind: string;
            label: string;
          };
          status: 'conflict';
          theirs: unknown;
        }
      | {
          heldBy: {
            id: string;
            name: string;
          };
          kind: 'code_collision';
          mutationId: string;
          status: 'conflict';
          suggestedCode: string | null;
        }
      | {
          at: string;
          kind: 'deleted';
          mutationId: string;
          source: {
            kind: string;
            label: string;
          };
          status: 'conflict';
        }
      | {
          message: string;
          mutationId: string;
          reason: string;
          status: 'rejected';
        }
      | {
          mutationId: string;
          status: 'deferred';
          waitingOn: string;
        }
    >;
  };
};

export type MobileInventoryMutationsResponse =
  MobileInventoryMutationsResponses[keyof MobileInventoryMutationsResponses];

export type MobileInventoryChangesData = {
  body?: never;
  path?: never;
  query: {
    since: number;
    epoch: string;
    limit?: number;
  };
  url: '/mobile/inventory/sync/changes';
};

export type MobileInventoryChangesErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 409
   */
  409: {
    code: 'resync_required';
    message: string;
  };
  /**
   * 426
   */
  426: {
    code: 'client_too_old';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventoryChangesError =
  MobileInventoryChangesErrors[keyof MobileInventoryChangesErrors];

export type MobileInventoryChangesResponses = {
  /**
   * 200
   */
  200: {
    catalogueVersion: string;
    epoch: string;
    events: Array<{
      actor: {
        kind: string;
        label: string;
      };
      after: {
        placement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | {
              kind: 'hand';
            };
        previousPlacement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | null;
        [key: string]: unknown;
      };
      before: {
        placement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | {
              kind: 'hand';
            };
        previousPlacement?:
          | {
              kind: 'location';
              locationId: string;
            }
          | {
              itemId: string;
              kind: 'container';
            }
          | null;
        [key: string]: unknown;
      };
      clientTime: string | null;
      compensatesSeq: number | null;
      entityId: string;
      entityKind: 'item' | 'location';
      fields: Array<string>;
      kind: string;
      reason: string | null;
      seq: number;
      serverTime: string;
      undoable: boolean;
    }>;
    hasMore: boolean;
    items: Array<{
      access: 'open' | 'closed' | null;
      code: string | null;
      createdAt: string;
      deletedAt: string | null;
      documentTitles: Array<string>;
      documentsStatus: 'linked' | 'none' | 'unavailable';
      externalIds: Array<{
        kind: string;
        value: string;
      }>;
      fields: {
        [key: string]: unknown;
      };
      id: string;
      isContainer: boolean;
      isFull: boolean | null;
      legacyType: string | null;
      lifecycle: string;
      lifecycleChangedAt: string | null;
      name: string;
      note: string | null;
      photos: Array<{
        caption: string | null;
        sha256: string;
      }>;
      placement:
        | {
            kind: 'location';
            locationId: string;
          }
        | {
            itemId: string;
            kind: 'container';
          }
        | {
            kind: 'hand';
          };
      previousPlacement:
        | {
            kind: 'location';
            locationId: string;
          }
        | {
            itemId: string;
            kind: 'container';
          }
        | null;
      provenance: {
        merchant: string | null;
        price: number | null;
        purchasedOn: string | null;
        transactionUri: string | null;
        warrantyExpires: string | null;
      } | null;
      quantity: number;
      revision: number;
      seq: number;
      typeKey: string | null;
      updatedAt: string;
    }>;
    locations: Array<{
      deletedAt: string | null;
      id: string;
      name: string;
      parentId: string | null;
      revision: number;
      seq: number;
      sortOrder: number;
    }>;
    nextSince: number;
  };
};

export type MobileInventoryChangesResponse =
  MobileInventoryChangesResponses[keyof MobileInventoryChangesResponses];

export type MobileInventorySnapshotData = {
  body?: never;
  path?: never;
  query?: {
    cursor?: string;
    limit?: number;
  };
  url: '/mobile/inventory/sync/snapshot';
};

export type MobileInventorySnapshotErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 409
   */
  409: {
    code: 'resync_required';
    message: string;
  };
  /**
   * 426
   */
  426: {
    code: 'client_too_old';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventorySnapshotError =
  MobileInventorySnapshotErrors[keyof MobileInventorySnapshotErrors];

export type MobileInventorySnapshotResponses = {
  /**
   * 200
   */
  200: {
    catalogueVersion: string;
    epoch: string;
    highWaterSeq: number;
    items: Array<{
      access: 'open' | 'closed' | null;
      code: string | null;
      createdAt: string;
      deletedAt: string | null;
      documentTitles: Array<string>;
      documentsStatus: 'linked' | 'none' | 'unavailable';
      externalIds: Array<{
        kind: string;
        value: string;
      }>;
      fields: {
        [key: string]: unknown;
      };
      id: string;
      isContainer: boolean;
      isFull: boolean | null;
      legacyType: string | null;
      lifecycle: string;
      lifecycleChangedAt: string | null;
      name: string;
      note: string | null;
      photos: Array<{
        caption: string | null;
        sha256: string;
      }>;
      placement:
        | {
            kind: 'location';
            locationId: string;
          }
        | {
            itemId: string;
            kind: 'container';
          }
        | {
            kind: 'hand';
          };
      previousPlacement:
        | {
            kind: 'location';
            locationId: string;
          }
        | {
            itemId: string;
            kind: 'container';
          }
        | null;
      provenance: {
        merchant: string | null;
        price: number | null;
        purchasedOn: string | null;
        transactionUri: string | null;
        warrantyExpires: string | null;
      } | null;
      quantity: number;
      revision: number;
      seq: number;
      typeKey: string | null;
      updatedAt: string;
    }>;
    locations: Array<{
      deletedAt: string | null;
      id: string;
      name: string;
      parentId: string | null;
      revision: number;
      seq: number;
      sortOrder: number;
    }>;
    nextCursor: string | null;
    total: number;
  };
};

export type MobileInventorySnapshotResponse =
  MobileInventorySnapshotResponses[keyof MobileInventorySnapshotResponses];

export type MobileInventoryCatalogueData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mobile/inventory/types';
};

export type MobileInventoryCatalogueErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 426
   */
  426: {
    code: 'client_too_old';
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileInventoryCatalogueError =
  MobileInventoryCatalogueErrors[keyof MobileInventoryCatalogueErrors];

export type MobileInventoryCatalogueResponses = {
  /**
   * 200
   */
  200: {
    types: Array<{
      capabilities: Array<string>;
      fields: Array<{
        choices?: Array<string>;
        dimension?: string;
        highlighted?: boolean;
        hint?: string;
        key: string;
        kind: string;
        label: string;
        required?: boolean;
        unit?: string;
      }>;
      key: string;
      legacyLabels: Array<string>;
      name: string;
    }>;
    units: Array<{
      dimension: string;
      multiplier: number;
      symbol: string;
    }>;
    version: string;
  };
};

export type MobileInventoryCatalogueResponse =
  MobileInventoryCatalogueResponses[keyof MobileInventoryCatalogueResponses];

export type MobilePurchasesListPurchasesData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    cursor?: string;
    status?: 'unsettled';
  };
  url: '/mobile/purchases';
};

export type MobilePurchasesListPurchasesErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesListPurchasesError =
  MobilePurchasesListPurchasesErrors[keyof MobilePurchasesListPurchasesErrors];

export type MobilePurchasesListPurchasesResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      currency: string;
      id: string;
      itemCount: number;
      merchant:
        | {
            entityId: string;
            name: string | null;
            resolution: 'entity';
          }
        | {
            name: string;
            resolution: 'name';
          }
        | {
            resolution: 'unattributed';
          };
      merchantName: string | null;
      orderedOn: string;
      receiptUri: string | null;
      status: string;
      totalCents: number;
    }>;
    nextCursor: string | null;
    total?: number | null;
  };
};

export type MobilePurchasesListPurchasesResponse =
  MobilePurchasesListPurchasesResponses[keyof MobilePurchasesListPurchasesResponses];

export type MobilePurchasesCreateManualPurchaseData = {
  /**
   * Body
   */
  body?: {
    capture?: {
      capturedAt: string | null;
      capturedAtSource: 'client' | 'exif' | null;
      declaredTimeZone: string | null;
      latitude: number | null;
      locationSource: 'client' | 'exif' | null;
      longitude: number | null;
      utcOffsetMinutes: number | null;
    } | null;
    currency: string;
    discountCents?: number;
    discountIncluded?: boolean | null;
    idempotencyKey: string;
    items: Array<{
      lineTotalCents: number;
      listPriceAsserted?: boolean;
      listPriceCents?: number | null;
      name: string;
      notes: Array<string>;
      quantity?: number | null;
      unitPriceCents: number;
    }>;
    merchantAddressId?: string | null;
    merchantAddressName?: string | null;
    merchantEntityId?: string | null;
    merchantName: string | null;
    orderedAt: string;
    orderedAtOffsetMinutes?: number | null;
    shippingCents?: number;
    shippingIncluded?: boolean | null;
    surchargeCents?: number;
    surchargeIncluded?: boolean | null;
    taxCents?: number;
    taxIncluded?: boolean | null;
    totalCents: number;
  };
  path?: never;
  query?: never;
  url: '/mobile/purchases/manual';
};

export type MobilePurchasesCreateManualPurchaseErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesCreateManualPurchaseError =
  MobilePurchasesCreateManualPurchaseErrors[keyof MobilePurchasesCreateManualPurchaseErrors];

export type MobilePurchasesCreateManualPurchaseResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    edit: {
      changes: Array<{
        current: string | null;
        field: string;
        itemId: string | null;
        original: string | null;
      }>;
      editedAt: string;
    } | null;
    id: string;
    itemCount: number;
    items: Array<{
      hasInventoryLink?: boolean;
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchant:
      | {
          entityId: string;
          name: string | null;
          resolution: 'entity';
        }
      | {
          name: string;
          resolution: 'name';
        }
      | {
          resolution: 'unattributed';
        };
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    receiptUris: Array<string>;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
    updatedAt: string | null;
  };
};

export type MobilePurchasesCreateManualPurchaseResponse =
  MobilePurchasesCreateManualPurchaseResponses[keyof MobilePurchasesCreateManualPurchaseResponses];

export type MobilePurchasesSaveReceiptDraftData = {
  /**
   * Body
   */
  body?: {
    capture?: {
      capturedAt: string | null;
      capturedAtSource: 'client' | 'exif' | null;
      declaredTimeZone: string | null;
      latitude: number | null;
      locationSource: 'client' | 'exif' | null;
      longitude: number | null;
      utcOffsetMinutes: number | null;
    } | null;
    currency: string;
    discountCents?: number;
    discountIncluded?: boolean | null;
    documents: Array<{
      documentUri: string;
      kind: 'receipt';
    }>;
    idempotencyKey: string;
    items: Array<{
      lineTotalCents: number;
      listPriceAsserted?: boolean;
      listPriceCents?: number | null;
      name: string;
      notes: Array<string>;
      quantity?: number | null;
      unitPriceCents: number;
    }>;
    merchantAddressId?: string | null;
    merchantAddressName?: string | null;
    merchantEntityId?: string | null;
    merchantName: string | null;
    orderedAt: string;
    orderedAtOffsetMinutes?: number | null;
    shippingCents?: number;
    shippingIncluded?: boolean | null;
    surchargeCents?: number;
    surchargeIncluded?: boolean | null;
    taxCents?: number;
    taxIncluded?: boolean | null;
    totalCents: number;
  };
  path?: never;
  query?: never;
  url: '/mobile/purchases/receipts';
};

export type MobilePurchasesSaveReceiptDraftErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesSaveReceiptDraftError =
  MobilePurchasesSaveReceiptDraftErrors[keyof MobilePurchasesSaveReceiptDraftErrors];

export type MobilePurchasesSaveReceiptDraftResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    edit: {
      changes: Array<{
        current: string | null;
        field: string;
        itemId: string | null;
        original: string | null;
      }>;
      editedAt: string;
    } | null;
    id: string;
    itemCount: number;
    items: Array<{
      hasInventoryLink?: boolean;
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchant:
      | {
          entityId: string;
          name: string | null;
          resolution: 'entity';
        }
      | {
          name: string;
          resolution: 'name';
        }
      | {
          resolution: 'unattributed';
        };
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    receiptUris: Array<string>;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
    updatedAt: string | null;
  };
};

export type MobilePurchasesSaveReceiptDraftResponse =
  MobilePurchasesSaveReceiptDraftResponses[keyof MobilePurchasesSaveReceiptDraftResponses];

export type MobilePurchasesExtractReceiptData = {
  /**
   * Body
   */
  body?: {
    capture?: {
      capturedAt?: string;
      location?: {
        latitude: number;
        longitude: number;
      };
      timeZone?: string;
    };
    parts: Array<{
      dataBase64: string;
      mediaType:
        | 'image/jpeg'
        | 'image/png'
        | 'image/webp'
        | 'image/gif'
        | 'application/pdf'
        | 'text/plain';
    }>;
  };
  path?: never;
  query?: never;
  url: '/mobile/purchases/receipts/extract';
};

export type MobilePurchasesExtractReceiptErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 413
   */
  413: {
    code: 'payload_too_large';
    maxBytes: number;
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesExtractReceiptError =
  MobilePurchasesExtractReceiptErrors[keyof MobilePurchasesExtractReceiptErrors];

export type MobilePurchasesExtractReceiptResponses = {
  /**
   * 200
   */
  200:
    | {
        draft: {
          capture: {
            capturedAt: string | null;
            capturedAtSource: 'client' | 'exif' | null;
            declaredTimeZone: string | null;
            latitude: number | null;
            locationSource: 'client' | 'exif' | null;
            longitude: number | null;
            utcOffsetMinutes: number | null;
          } | null;
          currency: string;
          discountCents: number;
          discountIncluded: boolean | null;
          documents: Array<{
            documentUri: string;
            kind: 'receipt';
          }>;
          items: Array<{
            lineTotalCents: number;
            listPriceAsserted?: boolean;
            listPriceCents?: number | null;
            name: string;
            notes: Array<string>;
            quantity?: number | null;
            unitPriceCents: number;
          }>;
          merchantAddressName: string | null;
          merchantName: string | null;
          orderedAt: string;
          orderedAtOffsetMinutes: number | null;
          shippingCents: number;
          shippingIncluded: boolean | null;
          subtotalCents: number;
          surchargeCents: number;
          surchargeIncluded: boolean | null;
          taxCents: number;
          taxIncluded: boolean | null;
          totalCents: number;
        };
        failures: Array<{
          code: string;
          deltaCents: number | null;
          detail: string;
        }>;
        kind: 'draft';
        matchedMerchantEntityId: string | null;
        receiptUris: Array<string>;
        reconciled: boolean;
      }
    | {
        kind: 'unreadable';
        reason: string;
        receiptUris: Array<string>;
      };
};

export type MobilePurchasesExtractReceiptResponse =
  MobilePurchasesExtractReceiptResponses[keyof MobilePurchasesExtractReceiptResponses];

export type MobilePurchasesGetReceiptData = {
  body?: never;
  path: {
    sha256: string;
  };
  query?: never;
  url: '/mobile/purchases/receipts/{sha256}';
};

export type MobilePurchasesGetReceiptErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetReceiptError =
  MobilePurchasesGetReceiptErrors[keyof MobilePurchasesGetReceiptErrors];

export type MobilePurchasesGetReceiptResponses = {
  /**
   * 200
   */
  200: {
    byteLength: number;
    dataBase64: string;
    mediaType: string;
    sha256: string;
  };
};

export type MobilePurchasesGetReceiptResponse =
  MobilePurchasesGetReceiptResponses[keyof MobilePurchasesGetReceiptResponses];

export type MobilePurchasesGetReceiptThumbnailData = {
  body?: never;
  path: {
    sha256: string;
  };
  query?: never;
  url: '/mobile/purchases/receipts/{sha256}/thumbnail';
};

export type MobilePurchasesGetReceiptThumbnailErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 415
   */
  415: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetReceiptThumbnailError =
  MobilePurchasesGetReceiptThumbnailErrors[keyof MobilePurchasesGetReceiptThumbnailErrors];

export type MobilePurchasesGetReceiptThumbnailResponses = {
  /**
   * 200
   */
  200: {
    byteLength: number;
    dataBase64: string;
    mediaType: string;
    sha256: string;
  };
};

export type MobilePurchasesGetReceiptThumbnailResponse =
  MobilePurchasesGetReceiptThumbnailResponses[keyof MobilePurchasesGetReceiptThumbnailResponses];

export type MobilePurchasesSearchPurchasesData = {
  body?: never;
  path?: never;
  query: {
    q: string;
    status?: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
    tags?: Array<string>;
  };
  url: '/mobile/purchases/search';
};

export type MobilePurchasesSearchPurchasesErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesSearchPurchasesError =
  MobilePurchasesSearchPurchasesErrors[keyof MobilePurchasesSearchPurchasesErrors];

export type MobilePurchasesSearchPurchasesResponses = {
  /**
   * 200
   */
  200: {
    hits: Array<
      | {
          currency: string;
          id: string;
          kind: 'purchase';
          matchField: string;
          matchedText: string | null;
          merchantName: string | null;
          orderedOn: string;
          status: string;
          totalCents: number;
        }
      | {
          currency: string;
          id: string;
          kind: 'item';
          lineTotalCents: number;
          matchField: string;
          matchedText: string | null;
          merchantName: string | null;
          name: string;
          orderedOn: string;
          purchaseId: string;
          quantity: number;
          status: string;
          totalCents: number;
        }
    >;
  };
};

export type MobilePurchasesSearchPurchasesResponse =
  MobilePurchasesSearchPurchasesResponses[keyof MobilePurchasesSearchPurchasesResponses];

export type MobilePurchasesGetMonthSummaryData = {
  body?: never;
  path?: never;
  query: {
    month: string;
  };
  url: '/mobile/purchases/summary';
};

export type MobilePurchasesGetMonthSummaryErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetMonthSummaryError =
  MobilePurchasesGetMonthSummaryErrors[keyof MobilePurchasesGetMonthSummaryErrors];

export type MobilePurchasesGetMonthSummaryResponses = {
  /**
   * 200
   */
  200: {
    merchantLeaders: Array<{
      currency: string;
      merchantName: string | null;
      netSpendCents: number;
      orderCount: number;
    }>;
    month: string;
    previousMonthTotals: Array<{
      currency: string;
      netSpendCents: number;
      orderCount: number;
      totalCents: number;
    }> | null;
    purchaseCount: number;
    totals: Array<{
      currency: string;
      netSpendCents: number;
      orderCount: number;
      totalCents: number;
    }>;
    unmatchedCount: number;
  };
};

export type MobilePurchasesGetMonthSummaryResponse =
  MobilePurchasesGetMonthSummaryResponses[keyof MobilePurchasesGetMonthSummaryResponses];

export type MobilePurchasesPurchaseTagsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/mobile/purchases/tags';
};

export type MobilePurchasesPurchaseTagsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesPurchaseTagsError =
  MobilePurchasesPurchaseTagsErrors[keyof MobilePurchasesPurchaseTagsErrors];

export type MobilePurchasesPurchaseTagsResponses = {
  /**
   * 200
   */
  200: {
    tags: Array<string>;
  };
};

export type MobilePurchasesPurchaseTagsResponse =
  MobilePurchasesPurchaseTagsResponses[keyof MobilePurchasesPurchaseTagsResponses];

export type MobilePurchasesGetPurchaseData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/purchases/{id}';
};

export type MobilePurchasesGetPurchaseErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesGetPurchaseError =
  MobilePurchasesGetPurchaseErrors[keyof MobilePurchasesGetPurchaseErrors];

export type MobilePurchasesGetPurchaseResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    edit: {
      changes: Array<{
        current: string | null;
        field: string;
        itemId: string | null;
        original: string | null;
      }>;
      editedAt: string;
    } | null;
    id: string;
    itemCount: number;
    items: Array<{
      hasInventoryLink?: boolean;
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchant:
      | {
          entityId: string;
          name: string | null;
          resolution: 'entity';
        }
      | {
          name: string;
          resolution: 'name';
        }
      | {
          resolution: 'unattributed';
        };
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    receiptUris: Array<string>;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
    updatedAt: string | null;
  };
};

export type MobilePurchasesGetPurchaseResponse =
  MobilePurchasesGetPurchaseResponses[keyof MobilePurchasesGetPurchaseResponses];

export type MobilePurchasesUpdatePurchaseData = {
  /**
   * Body
   */
  body?: {
    discountCents?: number;
    expectedUpdatedAt: string;
    lines: Array<{
      id?: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchantEntityId?: string | null;
    merchantEntityName?: string | null;
    orderedAt?: string;
    shippingCents?: number;
    subtotalCents?: number;
    surchargeCents?: number;
    taxCents?: number;
    totalCents?: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/purchases/{id}';
};

export type MobilePurchasesUpdatePurchaseErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor' | 'invalid_request';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token';
    message: string;
  };
  /**
   * 403
   */
  403:
    | {
        code: 'device_revoked';
        message: string;
      }
    | {
        capability: string;
        code: 'capability_not_granted';
        message: string;
      };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 409
   */
  409: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 429
   */
  429: {
    code: 'rate_limited';
    message: string;
    retryAfterSeconds: number;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'purchase_locked'
      | 'purchase_stale'
      | 'upstream_unsupported_media'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobilePurchasesUpdatePurchaseError =
  MobilePurchasesUpdatePurchaseErrors[keyof MobilePurchasesUpdatePurchaseErrors];

export type MobilePurchasesUpdatePurchaseResponses = {
  /**
   * 200
   */
  200: {
    currency: string;
    discountCents: number;
    edit: {
      changes: Array<{
        current: string | null;
        field: string;
        itemId: string | null;
        original: string | null;
      }>;
      editedAt: string;
    } | null;
    id: string;
    itemCount: number;
    items: Array<{
      hasInventoryLink?: boolean;
      id: string;
      lineTotalCents: number;
      name: string;
      quantity: number;
    }>;
    merchant:
      | {
          entityId: string;
          name: string | null;
          resolution: 'entity';
        }
      | {
          name: string;
          resolution: 'name';
        }
      | {
          resolution: 'unattributed';
        };
    merchantName: string | null;
    orderedAt: string;
    orderedOn: string;
    receiptUri: string | null;
    receiptUris: Array<string>;
    shippingCents: number;
    source: string;
    status: string;
    subtotalCents: number;
    surchargeCents: number;
    taxCents: number;
    totalCents: number;
    updatedAt: string | null;
  };
};

export type MobilePurchasesUpdatePurchaseResponse =
  MobilePurchasesUpdatePurchaseResponses[keyof MobilePurchasesUpdatePurchaseResponses];

export type OperatorListDevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/operator/devices';
};

export type OperatorListDevicesErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
};

export type OperatorListDevicesError = OperatorListDevicesErrors[keyof OperatorListDevicesErrors];

export type OperatorListDevicesResponses = {
  /**
   * 200
   */
  200: {
    devices: Array<{
      createdAt: string;
      id: string;
      lastSeenAt: string;
      model: string;
      name: string;
      revokedAt: string | null;
    }>;
  };
};

export type OperatorListDevicesResponse =
  OperatorListDevicesResponses[keyof OperatorListDevicesResponses];

export type OperatorRevokeDeviceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/operator/devices/{id}';
};

export type OperatorRevokeDeviceErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code: string;
    message: string;
  };
};

export type OperatorRevokeDeviceError =
  OperatorRevokeDeviceErrors[keyof OperatorRevokeDeviceErrors];

export type OperatorRevokeDeviceResponses = {
  /**
   * 200
   */
  200: {
    alreadyRevoked: boolean;
    id: string;
    revokedAt: string;
  };
};

export type OperatorRevokeDeviceResponse =
  OperatorRevokeDeviceResponses[keyof OperatorRevokeDeviceResponses];

export type OperatorIssuePairingCodeData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path?: never;
  query?: never;
  url: '/operator/pairing/codes';
};

export type OperatorIssuePairingCodeErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: string;
    message: string;
  };
};

export type OperatorIssuePairingCodeError =
  OperatorIssuePairingCodeErrors[keyof OperatorIssuePairingCodeErrors];

export type OperatorIssuePairingCodeResponses = {
  /**
   * 201
   */
  201: {
    code: string;
    expiresAt: string;
    pairingUrl: string;
  };
};

export type OperatorIssuePairingCodeResponse =
  OperatorIssuePairingCodeResponses[keyof OperatorIssuePairingCodeResponses];
