// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/health';
};

export type HealthResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
    pillar: 'bfm';
    status: 'ok';
    ts: string;
    version: string;
  };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type MobileFinanceListTransactionsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    cursor?: string;
  };
  url: '/mobile/finance/transactions';
};

export type MobileFinanceListTransactionsErrors = {
  /**
   * 400
   */
  400: {
    code: 'invalid_cursor';
    message: string;
  };
  /**
   * 401
   */
  401: {
    code: 'invalid_token' | 'device_revoked';
    message: string;
  };
  /**
   * 403
   */
  403: {
    code: 'invalid_token' | 'device_revoked';
    message: string;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceListTransactionsError =
  MobileFinanceListTransactionsErrors[keyof MobileFinanceListTransactionsErrors];

export type MobileFinanceListTransactionsResponses = {
  /**
   * 200
   */
  200: {
    data: Array<{
      amount: number;
      currency: 'AUD';
      date: string;
      description: string;
      entityName: string | null;
      id: string;
      tags: Array<string>;
      type: string;
    }>;
    nextCursor: string | null;
  };
};

export type MobileFinanceListTransactionsResponse =
  MobileFinanceListTransactionsResponses[keyof MobileFinanceListTransactionsResponses];

export type MobileFinanceGetTransactionData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/mobile/finance/transactions/{id}';
};

export type MobileFinanceGetTransactionErrors = {
  /**
   * 401
   */
  401: {
    code: 'invalid_token' | 'device_revoked';
    message: string;
  };
  /**
   * 403
   */
  403: {
    code: 'invalid_token' | 'device_revoked';
    message: string;
  };
  /**
   * 404
   */
  404: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 502
   */
  502: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
  /**
   * 503
   */
  503: {
    code:
      | 'upstream_unavailable'
      | 'upstream_degraded'
      | 'upstream_contract_mismatch'
      | 'upstream_misconfigured'
      | 'upstream_invalid_request'
      | 'upstream_conflict'
      | 'not_found';
    message: string;
    pillar: string;
    retryable: boolean;
  };
};

export type MobileFinanceGetTransactionError =
  MobileFinanceGetTransactionErrors[keyof MobileFinanceGetTransactionErrors];

export type MobileFinanceGetTransactionResponses = {
  /**
   * 200
   */
  200: {
    account: string;
    amount: number;
    country: string | null;
    currency: 'AUD';
    date: string;
    description: string;
    entityId: string | null;
    entityName: string | null;
    id: string;
    lastEditedTime: string;
    location: string | null;
    notes: string | null;
    relatedTransactionId: string | null;
    tags: Array<string>;
    type: string;
  };
};

export type MobileFinanceGetTransactionResponse =
  MobileFinanceGetTransactionResponses[keyof MobileFinanceGetTransactionResponses];

export type OperatorListDevicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/operator/devices';
};

export type OperatorListDevicesErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
};

export type OperatorListDevicesError = OperatorListDevicesErrors[keyof OperatorListDevicesErrors];

export type OperatorListDevicesResponses = {
  /**
   * 200
   */
  200: {
    devices: Array<{
      createdAt: string;
      id: string;
      lastSeenAt: string;
      model: string;
      name: string;
      revokedAt: string | null;
    }>;
  };
};

export type OperatorListDevicesResponse =
  OperatorListDevicesResponses[keyof OperatorListDevicesResponses];

export type OperatorRevokeDeviceData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/operator/devices/{id}';
};

export type OperatorRevokeDeviceErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code: string;
    message: string;
  };
};

export type OperatorRevokeDeviceError =
  OperatorRevokeDeviceErrors[keyof OperatorRevokeDeviceErrors];

export type OperatorRevokeDeviceResponses = {
  /**
   * 200
   */
  200: {
    alreadyRevoked: boolean;
    id: string;
    revokedAt: string;
  };
};

export type OperatorRevokeDeviceResponse =
  OperatorRevokeDeviceResponses[keyof OperatorRevokeDeviceResponses];

export type OperatorIssuePairingCodeData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path?: never;
  query?: never;
  url: '/operator/pairing/codes';
};

export type OperatorIssuePairingCodeErrors = {
  /**
   * 401
   */
  401: {
    code: string;
    message: string;
  };
  /**
   * 429
   */
  429: {
    code: string;
    message: string;
  };
};

export type OperatorIssuePairingCodeError =
  OperatorIssuePairingCodeErrors[keyof OperatorIssuePairingCodeErrors];

export type OperatorIssuePairingCodeResponses = {
  /**
   * 201
   */
  201: {
    code: string;
    expiresAt: string;
    pairingUrl: string;
  };
};

export type OperatorIssuePairingCodeResponse =
  OperatorIssuePairingCodeResponses[keyof OperatorIssuePairingCodeResponses];
