import { defineType, type TypeDefinition } from '../define-type.js';

const BOOK_GENRE_CHOICES = [
  'Art',
  'Biography & memoir',
  'Business & economics',
  "Children's",
  'Classics',
  'Comics & graphic novels',
  'Cookbooks',
  'Crafts & hobbies',
  'Decorative',
  'Education',
  'Fantasy',
  'Fiction',
  'Gardening',
  'Health & wellness',
  'History',
  'Home & design',
  'Horror',
  'Humor',
  'Literary fiction',
  'Mystery & crime',
  'Non-fiction',
  'Philosophy',
  'Poetry',
  'Politics',
  'Reference',
  'Religion & spirituality',
  'Romance',
  'Science',
  'Science fiction',
  'Self-help',
  'Social sciences',
  'Sports',
  'Technology',
  'Thriller',
  'Travel',
  'True crime',
  'Young adult',
] as const;

const BOOK_FORMAT_CHOICES = [
  'Paperback',
  'Hardcover',
  'Mass-market paperback',
  'Trade paperback',
  'Board book',
  'Spiral-bound',
  'Leather-bound',
  'Library binding',
  'Other',
] as const;

export const bookType: TypeDefinition = defineType({
  key: 'book',
  name: 'Book',
  legacyLabels: ['Book', 'Books'],
  fields: [
    {
      key: 'Length',
      label: 'Length',
      kind: 'text',
      hint: 'Page count',
      highlighted: true,
    },
    {
      key: 'Genre',
      label: 'Genre',
      kind: 'choice',
      choices: BOOK_GENRE_CHOICES,
      highlighted: true,
    },
    {
      key: 'Type',
      label: 'Type',
      kind: 'choice',
      choices: BOOK_FORMAT_CHOICES,
      hint: 'The book format or binding',
      highlighted: true,
    },
    {
      key: 'ISBN',
      label: 'ISBN',
      kind: 'text',
      hint: 'ISBN-10 or ISBN-13',
    },
  ],
});
