#!/usr/bin/env bash
#
# Which Swift files the two tools see, and the boundary that decides it.
#
# Generated code is the whole reason this file exists. `.swiftlint.yml`'s rules
# describe code a person wrote, and generated OpenAPI Swift breaks four of them
# by construction: `Components.Schemas.Transaction` is two levels of nested
# type, a generated `Types.swift` runs to thousands of lines, long signatures
# pass 120 columns, and an optional boolean in the contract becomes `Bool?`.
# Holding a generator to those rules has exactly one outcome — the blanket
# `swiftlint:disable` that `.swiftlint.yml`'s header forbids.
#
# So: generated sources live in a directory named `Generated`, and neither tool
# looks inside one. SwiftLint learns that from its own `excluded:`.
#
# The formatter's exclusion is a separate decision with a separate reason, and
# it goes the other way from the TypeScript side, where the generated
# cross-pillar clients ARE formatted (`openapi-ts … && oxfmt --write`) and the
# diff gate compares formatted output against formatted output. Formatting
# generated Swift is just as harmless in itself — the objection is what it would
# make the generated client's byte-equality gate depend on. swift-format ships
# inside the Xcode toolchain and cannot be pinned by this repo (see the README);
# the generator can be, through SPM. Format-then-commit would make the committed
# bytes a product of both, so two contributors on two Xcodes would regenerate to
# two different files and one of them would fail a gate with no local fix.
# Excluding leaves the generator as the single producer of those bytes.
#
# swift-format has no exclusion mechanism this repo can use to express that: a
# `.swift-format-ignore` file is ignored by the Xcode toolchain's swift-format
# both for explicitly-passed paths and under `--recursive`. Measured, not
# assumed. So the formatter learns the boundary from `list` below, which is the
# only thing that decides which files it is handed.
#
# An exclusion keyed on a directory name is only safe while the name means what
# it says, which is what `check` is for: a generated file anywhere else fails,
# and a hand-written file inside a `Generated` directory fails too. Without the
# second half the directory is somewhere to hide code from the linter, which is
# the suppression comment again wearing a different hat.
#
# `self-test` proves both tools honour the boundary, against fixtures built from
# the real `.swiftlint.yml`. Every claim above is about how two third-party
# tools read two config files in two formats, so none of it is worth asserting
# in a comment that nothing runs.

set -euo pipefail

# The directory name that means "a generator wrote this". Named once; SwiftLint
# spells the same idea as `'**/Generated'` in `.swiftlint.yml`, and the two are
# held together by `self-test` rather than by anyone remembering.
readonly GENERATED_DIRNAME='Generated'

# SwiftPM checkout and build products, pruned everywhere. `.swiftlint.yml`
# excludes the same directory; the two describe one file set.
readonly BUILD_DIRNAME='.build'

# A generated file announces itself in its header, and every generator this repo
# is likely to meet uses one of these phrasings — swift-openapi-generator emits
# "Generated by swift-openapi-generator, do not modify.". Matching a family of
# conventions rather than one exact string means adopting a second generator is
# not a silent failure; adopting one that announces itself some third way is a
# loud one, and the fix is to widen this pattern on purpose.
readonly GENERATOR_MARKER='^[[:space:]]*//.*([Gg]enerated by |DO NOT EDIT|[Dd]o not modify)'

# How far into a file to look for that header. Generators put it first; a
# bounded window keeps the phrase from matching prose somewhere in the middle of
# a long hand-written file.
readonly GENERATOR_MARKER_LINES=20

root_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
readonly root_dir

die() {
    printf 'swift-sources: %s\n' "$1" >&2
    shift
    for line in "$@"; do
        printf '               %s\n' "$line" >&2
    done
    exit 1
}

require_roots() {
    # Every root, checked individually and before anything else. Checking only
    # the combined result is not enough: with two roots and one of them renamed,
    # `find` still returns the other's files, so a non-empty result would say
    # "fine" while an entire directory went unlinted. Each root is asserted by
    # name so the message names the one that moved.
    if [ "$#" -eq 0 ]; then
        die "no source roots given."
    fi
    for root in "$@"; do
        if [ ! -d "$root" ]; then
            die "'$root' is not a directory."
        fi
    done
}

# Every Swift file under the given roots, NUL-separated, `.build` pruned and
# nothing else. What `check` reasons about.
find_all_swift() {
    find "$@" -name "$BUILD_DIRNAME" -type d -prune -o -name '*.swift' -print0
}

carries_generator_marker() {
    local header
    # Read the header into a variable rather than piping `head` into `grep`:
    # under `pipefail` a matching `grep -q` exits early, `head` dies of SIGPIPE,
    # and the pipeline's status says "no match" for a file that matched.
    header="$(head -n "$GENERATOR_MARKER_LINES" -- "$1")"
    grep -Eq "$GENERATOR_MARKER" <<<"$header"
}

lives_in_generated_dir() {
    case "/$1" in
        */"$GENERATED_DIRNAME"/*) return 0 ;;
        *) return 1 ;;
    esac
}

# ---------------------------------------------------------------------------
# list — the formatter's file set
# ---------------------------------------------------------------------------

cmd_list() {
    require_roots "$@"

    # A file rather than a variable because the list is NUL-separated, and
    # cleaned up by hand rather than by `trap ... RETURN`: a RETURN trap is
    # global shell state that outlives the function that set it, so it would sit
    # installed for the rest of the run holding a reference to a local that no
    # longer exists. Today it would not fire — bash does not inherit RETURN
    # traps into functions without `set -T` — but that is a rule the reader has
    # to know before this looks safe, and two explicit `rm`s need no rule at all.
    local sources
    sources="$(mktemp)"

    # `-prune` rather than a path filter, so a large checkout is skipped rather
    # than walked.
    find "$@" \
        \( -name "$BUILD_DIRNAME" -o -name "$GENERATED_DIRNAME" \) -type d -prune \
        -o -name '*.swift' -print0 > "$sources"

    # The roots exist by now, so an empty result means they hold no Swift at
    # all. swift-format exits 0 both on a path that does not exist and on one
    # with nothing to check — no message either time — so without this the tools
    # would report success having read nothing. Verified against swift-format
    # from Xcode 27.
    if [ ! -s "$sources" ]; then
        rm -f "$sources"
        printf 'swift-sources: no Swift sources under '\''%s'\'' — the source roots are stale.\n' "$*" >&2
        return 1
    fi

    cat "$sources"
    rm -f "$sources"
}

# ---------------------------------------------------------------------------
# check — the boundary itself
# ---------------------------------------------------------------------------

cmd_check() {
    require_roots "$@"

    local -a stray_generated=() unmarked_in_generated=()
    local file
    while IFS= read -r -d '' file; do
        if carries_generator_marker "$file"; then
            lives_in_generated_dir "$file" || stray_generated+=("$file")
        else
            ! lives_in_generated_dir "$file" || unmarked_in_generated+=("$file")
        fi
    done < <(find_all_swift "$@")

    local status=0

    if [ "${#stray_generated[@]}" -gt 0 ]; then
        {
            printf 'swift-sources: generated code outside a %s/ directory.\n' "$GENERATED_DIRNAME"
            printf '               Both tools lint it as if a person wrote it, and the rules it\n'
            printf '               will fail are rules written for people:\n'
            printf '                 %s\n' "${stray_generated[@]}"
            printf '               Move it under a directory named %s.\n' "$GENERATED_DIRNAME"
        } >&2
        status=1
    fi

    if [ "${#unmarked_in_generated[@]}" -gt 0 ]; then
        {
            printf 'swift-sources: hand-written code inside a %s/ directory.\n' "$GENERATED_DIRNAME"
            printf '               Neither tool looks in there, so nothing checks this code at all:\n'
            printf '                 %s\n' "${unmarked_in_generated[@]}"
            printf '               Move it out — or, if a generator really did write it, teach\n'
            printf '               GENERATOR_MARKER in %s about that generator.\n' "${BASH_SOURCE[0]}"
        } >&2
        status=1
    fi

    return "$status"
}

# ---------------------------------------------------------------------------
# self-test — proof that the two tools agree with the two paragraphs above
# ---------------------------------------------------------------------------

# Breaks `nesting` (two levels of type) and `discouraged_optional_boolean`, the
# two rules generated OpenAPI Swift trips first, in six lines.
readonly FIXTURE_VIOLATION='public enum Components {
    public enum Schemas {
        public struct Transaction {
            public var settled: Bool?
        }
    }
}'

readonly FIXTURE_GENERATED_HEADER='// Generated by swift-openapi-generator, do not modify.'

readonly FIXTURE_CLEAN='public enum Demo {
    public static let name = "Demo"
}'

# A fixture is a miniature of the real tree — same root names, the real
# `.swiftlint.yml` — so the thing under test is this repo's configuration and
# not a restatement of it.
new_fixture() {
    local fixture
    fixture="$(mktemp -d)"
    mkdir -p "$fixture/App" "$fixture/Packages/Demo/Sources/Demo/$GENERATED_DIRNAME"
    cp "$root_dir/.swiftlint.yml" "$fixture/.swiftlint.yml"
    printf '%s\n' "$FIXTURE_CLEAN" > "$fixture/App/Demo.swift"
    printf '%s\n' "$fixture"
}

# SwiftLint reads `included:`/`excluded:` relative to the working directory, so
# the fixture has to be entered rather than pointed at.
swiftlint_passes_in() {
    (cd "$1" && swiftlint lint --strict --quiet > /dev/null 2>&1)
}

expect() {
    local description="$1"
    shift
    if "$@"; then
        return 0
    fi
    printf 'swift-sources self-test: %s\n' "$description" >&2
    return 1
}

not() {
    ! "$@"
}

cmd_self_test() {
    local status=0
    local generated_fixture stray_fixture unmarked_fixture

    # 1. A generated file inside Generated/ is invisible to SwiftLint, despite
    #    breaking two of its rules.
    generated_fixture="$(new_fixture)"
    printf '%s\n%s\n' "$FIXTURE_GENERATED_HEADER" "$FIXTURE_VIOLATION" \
        > "$generated_fixture/Packages/Demo/Sources/Demo/$GENERATED_DIRNAME/Types.swift"
    expect "SwiftLint lints inside $GENERATED_DIRNAME/ — the '**/$GENERATED_DIRNAME' exclusion in .swiftlint.yml is gone or misspelt." \
        swiftlint_passes_in "$generated_fixture" || status=1

    # 2. The same file one directory up still fails. This is the half that keeps
    #    the exclusion from quietly widening into "the BFMClient module".
    stray_fixture="$(new_fixture)"
    printf '%s\n%s\n' "$FIXTURE_GENERATED_HEADER" "$FIXTURE_VIOLATION" \
        > "$stray_fixture/Packages/Demo/Sources/Demo/Types.swift"
    expect "SwiftLint passed a violating file OUTSIDE $GENERATED_DIRNAME/ — the exclusion is wider than the directory it names." \
        not swiftlint_passes_in "$stray_fixture" || status=1

    # 3. The formatter's file set skips Generated/ and keeps everything else.
    #    swift-format is never invoked here: it has no say in which files it is
    #    handed, so `list` is the only thing that can be wrong.
    local listed
    listed="$(cd "$generated_fixture" && cmd_list App Packages | tr '\0' '\n')"
    expect "list included a file under $GENERATED_DIRNAME/ — the formatter would rewrite generated bytes." \
        not grep -q "/$GENERATED_DIRNAME/" <<<"$listed" || status=1
    expect "list dropped a hand-written source — the prune is catching more than $GENERATED_DIRNAME/." \
        grep -q 'App/Demo.swift' <<<"$listed" || status=1

    # 4. `check` catches generated code that landed somewhere else.
    expect "check passed a generated file outside $GENERATED_DIRNAME/." \
        not run_check_in "$stray_fixture" || status=1

    # 5. `check` catches hand-written code hiding where nothing looks.
    unmarked_fixture="$(new_fixture)"
    printf '%s\n' "$FIXTURE_CLEAN" \
        > "$unmarked_fixture/Packages/Demo/Sources/Demo/$GENERATED_DIRNAME/Sneaky.swift"
    expect "check passed a hand-written file inside $GENERATED_DIRNAME/." \
        not run_check_in "$unmarked_fixture" || status=1

    # 6. And a tree where both hold is not reported. A guard that fails on a
    #    correct tree gets deleted rather than obeyed.
    expect "check failed on a tree that respects the boundary." \
        run_check_in "$generated_fixture" || status=1

    # 7. A root holding no Swift is a stale root, not an empty file set. Nothing
    #    downstream can tell the two apart — swift-format is silent and exits 0
    #    on both — so this refusal is the only thing between a renamed directory
    #    and a lint run that reads nothing and reports success.
    local empty_root
    empty_root="$(mktemp -d)"
    mkdir -p "$empty_root/App"
    expect "list accepted a source root with no Swift under it." \
        not run_list_in "$empty_root" || status=1

    rm -rf "$generated_fixture" "$stray_fixture" "$unmarked_fixture" "$empty_root"

    if [ "$status" -eq 0 ]; then
        printf 'swift-sources: the generated-code boundary holds in both tools.\n'
    fi
    return "$status"
}

run_check_in() {
    (cd "$1" && cmd_check App Packages 2> /dev/null)
}

run_list_in() {
    (cd "$1" && cmd_list App > /dev/null 2>&1)
}

# ---------------------------------------------------------------------------

case "${1-}" in
    list)
        shift
        cmd_list "$@"
        ;;
    check)
        shift
        cmd_check "$@"
        ;;
    self-test)
        cmd_self_test
        ;;
    *)
        die "unknown mode '${1-}' — expected 'list <root>...', 'check <root>...' or 'self-test'."
        ;;
esac
