/**
 * View types for the batched reverse lookup, derived from the generated
 * client for the same reason `../purchase-detail/types.ts` is: this is another
 * pillar's contract, regenerated by CI from its snapshot, and a hand-written
 * mirror would keep compiling while rendering fields purchases stopped
 * sending.
 */
import type { ReconcileLinksBatchResponses } from '../../../purchases-api/types.gen.js';

type BatchPayload = NonNullable<ReconcileLinksBatchResponses[200]>;

/**
 * One transaction's linkage. `confirmedChargeCount` and `derivedChargeCount`
 * are separate because a decision somebody made and the matcher's current
 * belief are different claims; both can be non-zero on one transaction.
 */
export type TransactionLinkSummary = BatchPayload['transactions'][number];
