/**
 * Structural snapshot of the inventory pillar's public surface, plus the
 * runtime `ModuleManifest` value the registry consumes on self-registration.
 * The `InventoryContract` type lives in `manifest.generated.ts` and is
 * regenerated by the `generate:manifest` script. This file is the stable
 * import path (`@pops/inventory/manifest`) so consumers don't move with the
 * generator output.
 */
import { inventoryManifest as inventorySettingsManifest } from './settings/index.js';

import type { ModuleManifest } from '@pops/types';

export type { InventoryContract } from './manifest.generated.js';

export { INVENTORY_PAGES } from './pages.js';
export type { InventoryPageSlot } from './pages.js';

export const inventoryManifest: ModuleManifest = {
  id: 'inventory',
  name: 'Inventory',
  version: '0.1.0',
  surfaces: ['app'],
  description: 'Home items, locations, connections, warranties, and documents.',
  settings: [inventorySettingsManifest],
};
