// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type {
  AccountsCreateData,
  AccountsCreateErrors,
  AccountsCreateResponses,
  AccountsDeleteData,
  AccountsDeleteErrors,
  AccountsDeleteResponses,
  AccountsGetData,
  AccountsGetErrors,
  AccountsGetResponses,
  AccountsListData,
  AccountsListResponses,
  AccountsMergeData,
  AccountsMergeErrors,
  AccountsMergeResponses,
  AccountsPreviewMergeData,
  AccountsPreviewMergeErrors,
  AccountsPreviewMergeResponses,
  AccountsReorderData,
  AccountsReorderErrors,
  AccountsReorderResponses,
  AccountsUpdateData,
  AccountsUpdateErrors,
  AccountsUpdateResponses,
  BudgetsCreateData,
  BudgetsCreateErrors,
  BudgetsCreateResponses,
  BudgetsDeleteData,
  BudgetsDeleteErrors,
  BudgetsDeleteResponses,
  BudgetsGetData,
  BudgetsGetErrors,
  BudgetsGetResponses,
  BudgetsListData,
  BudgetsListResponses,
  BudgetsUpdateData,
  BudgetsUpdateErrors,
  BudgetsUpdateResponses,
  CorrectionsAdjustConfidenceData,
  CorrectionsAdjustConfidenceErrors,
  CorrectionsAdjustConfidenceResponses,
  CorrectionsAnalyzeCorrectionData,
  CorrectionsAnalyzeCorrectionErrors,
  CorrectionsAnalyzeCorrectionResponses,
  CorrectionsApplyChangeSetData,
  CorrectionsApplyChangeSetErrors,
  CorrectionsApplyChangeSetResponses,
  CorrectionsApplyExistingData,
  CorrectionsApplyExistingErrors,
  CorrectionsApplyExistingResponses,
  CorrectionsCreateOrUpdateData,
  CorrectionsCreateOrUpdateErrors,
  CorrectionsCreateOrUpdateResponses,
  CorrectionsDeleteData,
  CorrectionsDeleteErrors,
  CorrectionsDeleteResponses,
  CorrectionsFindMatchData,
  CorrectionsFindMatchErrors,
  CorrectionsFindMatchResponses,
  CorrectionsGenerateRulesData,
  CorrectionsGenerateRulesErrors,
  CorrectionsGenerateRulesResponses,
  CorrectionsGetData,
  CorrectionsGetErrors,
  CorrectionsGetResponses,
  CorrectionsListData,
  CorrectionsListErrors,
  CorrectionsListMergedData,
  CorrectionsListMergedErrors,
  CorrectionsListMergedResponses,
  CorrectionsListResponses,
  CorrectionsPreviewChangeSetData,
  CorrectionsPreviewChangeSetErrors,
  CorrectionsPreviewChangeSetResponses,
  CorrectionsPreviewMatchesData,
  CorrectionsPreviewMatchesErrors,
  CorrectionsPreviewMatchesResponses,
  CorrectionsProposeChangeSetData,
  CorrectionsProposeChangeSetErrors,
  CorrectionsProposeChangeSetResponses,
  CorrectionsRejectChangeSetData,
  CorrectionsRejectChangeSetErrors,
  CorrectionsRejectChangeSetResponses,
  CorrectionsReviseChangeSetData,
  CorrectionsReviseChangeSetErrors,
  CorrectionsReviseChangeSetResponses,
  CorrectionsRuleMatchPreviewData,
  CorrectionsRuleMatchPreviewErrors,
  CorrectionsRuleMatchPreviewResponses,
  CorrectionsUpdateData,
  CorrectionsUpdateErrors,
  CorrectionsUpdateResponses,
  CurrenciesCreateData,
  CurrenciesCreateErrors,
  CurrenciesCreateResponses,
  CurrenciesDeleteData,
  CurrenciesDeleteErrors,
  CurrenciesDeleteResponses,
  CurrenciesListData,
  CurrenciesListResponses,
  CurrenciesUpdateData,
  CurrenciesUpdateErrors,
  CurrenciesUpdateResponses,
  EntityUsageListData,
  EntityUsageListErrors,
  EntityUsageListResponses,
  GiftCardDetailsGetData,
  GiftCardDetailsGetErrors,
  GiftCardDetailsGetResponses,
  GiftCardDetailsRevealData,
  GiftCardDetailsRevealErrors,
  GiftCardDetailsRevealResponses,
  GiftCardDetailsWriteData,
  GiftCardDetailsWriteErrors,
  GiftCardDetailsWriteResponses,
  ImportsApplyChangeSetAndReevaluateData,
  ImportsApplyChangeSetAndReevaluateErrors,
  ImportsApplyChangeSetAndReevaluateResponses,
  ImportsCommitImportData,
  ImportsCommitImportErrors,
  ImportsCommitImportResponses,
  ImportsCreateEntityData,
  ImportsCreateEntityErrors,
  ImportsCreateEntityResponses,
  ImportsGetImportProgressData,
  ImportsGetImportProgressErrors,
  ImportsGetImportProgressResponses,
  ImportsProcessImportData,
  ImportsProcessImportErrors,
  ImportsProcessImportResponses,
  ImportsReevaluateWithPendingRulesData,
  ImportsReevaluateWithPendingRulesErrors,
  ImportsReevaluateWithPendingRulesResponses,
  InstitutionsCreateData,
  InstitutionsCreateErrors,
  InstitutionsCreateResponses,
  InstitutionsDeleteData,
  InstitutionsDeleteErrors,
  InstitutionsDeleteResponses,
  InstitutionsListData,
  InstitutionsListResponses,
  InstitutionsUpdateData,
  InstitutionsUpdateErrors,
  InstitutionsUpdateResponses,
  LoanGetTermsData,
  LoanGetTermsErrors,
  LoanGetTermsResponses,
  LoanLinkOffsetAccountData,
  LoanLinkOffsetAccountErrors,
  LoanLinkOffsetAccountResponses,
  LoanListOffsetLinksData,
  LoanListOffsetLinksErrors,
  LoanListOffsetLinksResponses,
  LoanListRateHistoryData,
  LoanListRateHistoryErrors,
  LoanListRateHistoryResponses,
  LoanRecordRateData,
  LoanRecordRateErrors,
  LoanRecordRateResponses,
  LoanUnlinkOffsetAccountData,
  LoanUnlinkOffsetAccountErrors,
  LoanUnlinkOffsetAccountResponses,
  LoanWriteTermsData,
  LoanWriteTermsErrors,
  LoanWriteTermsResponses,
  SearchSearchData,
  SearchSearchErrors,
  SearchSearchResponses,
  SettingsEnsureData,
  SettingsEnsureErrors,
  SettingsEnsureResponses,
  SettingsGetData,
  SettingsGetErrors,
  SettingsGetManyData,
  SettingsGetManyErrors,
  SettingsGetManyResponses,
  SettingsGetResponses,
  SettingsListData,
  SettingsListErrors,
  SettingsListResponses,
  SettingsResetData,
  SettingsResetErrors,
  SettingsResetKeyData,
  SettingsResetKeyErrors,
  SettingsResetKeyResponses,
  SettingsResetResponses,
  SettingsSetData,
  SettingsSetErrors,
  SettingsSetManyData,
  SettingsSetManyErrors,
  SettingsSetManyResponses,
  SettingsSetResponses,
  TagRulesApplyData,
  TagRulesApplyErrors,
  TagRulesApplyExistingData,
  TagRulesApplyExistingErrors,
  TagRulesApplyExistingResponses,
  TagRulesApplyResponses,
  TagRulesDeleteData,
  TagRulesDeleteErrors,
  TagRulesDeleteResponses,
  TagRulesDisableData,
  TagRulesDisableErrors,
  TagRulesDisableResponses,
  TagRulesFacetsData,
  TagRulesFacetsResponses,
  TagRulesGetData,
  TagRulesGetErrors,
  TagRulesGetResponses,
  TagRulesListData,
  TagRulesListErrors,
  TagRulesListResponses,
  TagRulesMatchPreviewData,
  TagRulesMatchPreviewErrors,
  TagRulesMatchPreviewResponses,
  TagRulesPreviewData,
  TagRulesPreviewErrors,
  TagRulesPreviewResponses,
  TagRulesProposeData,
  TagRulesProposeErrors,
  TagRulesProposeResponses,
  TagRulesRejectData,
  TagRulesRejectErrors,
  TagRulesRejectResponses,
  TagRulesUpdateData,
  TagRulesUpdateErrors,
  TagRulesUpdateResponses,
  TagRulesVocabularyData,
  TagRulesVocabularyResponses,
  TransactionsAvailableTagsData,
  TransactionsAvailableTagsResponses,
  TransactionsCreateData,
  TransactionsCreateErrors,
  TransactionsCreateResponses,
  TransactionsDeleteData,
  TransactionsDeleteErrors,
  TransactionsDeleteResponses,
  TransactionsDescriptionsForPreviewData,
  TransactionsDescriptionsForPreviewResponses,
  TransactionsGetData,
  TransactionsGetErrors,
  TransactionsGetResponses,
  TransactionsListData,
  TransactionsListErrors,
  TransactionsListResponses,
  TransactionsRestoreData,
  TransactionsRestoreErrors,
  TransactionsRestoreResponses,
  TransactionsSuggestTagsData,
  TransactionsSuggestTagsResponses,
  TransactionsUnlinkTransferData,
  TransactionsUnlinkTransferErrors,
  TransactionsUnlinkTransferResponses,
  TransactionsUpdateData,
  TransactionsUpdateErrors,
  TransactionsUpdateResponses,
  WishlistCreateData,
  WishlistCreateErrors,
  WishlistCreateResponses,
  WishlistDeleteData,
  WishlistDeleteErrors,
  WishlistDeleteResponses,
  WishlistGetData,
  WishlistGetErrors,
  WishlistGetResponses,
  WishlistListData,
  WishlistListResponses,
  WishlistUpdateData,
  WishlistUpdateErrors,
  WishlistUpdateResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List accounts with optional search / kind / archived filters and pagination
 */
export const accountsList = <ThrowOnError extends boolean = false>(
  options?: Options<AccountsListData, ThrowOnError>
): RequestResult<AccountsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AccountsListResponses, unknown, ThrowOnError>({
    url: '/accounts',
    ...options,
  });

/**
 * Create a new account; rejects a reserved kind with 422
 */
export const accountsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<AccountsCreateData, ThrowOnError>
): RequestResult<AccountsCreateResponses, AccountsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<AccountsCreateResponses, AccountsCreateErrors, ThrowOnError>({
    url: '/accounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Batch-update display order for a set of accounts atomically; an unknown id 404s the whole batch
 */
export const accountsReorder = <ThrowOnError extends boolean = false>(
  options?: Options<AccountsReorderData, ThrowOnError>
): RequestResult<AccountsReorderResponses, AccountsReorderErrors, ThrowOnError> =>
  (options?.client ?? client).post<AccountsReorderResponses, AccountsReorderErrors, ThrowOnError>({
    url: '/accounts/reorder',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Archive an account (sets archivedAt); idempotent if already archived
 */
export const accountsDelete = <ThrowOnError extends boolean = false>(
  options: Options<AccountsDeleteData, ThrowOnError>
): RequestResult<AccountsDeleteResponses, AccountsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<AccountsDeleteResponses, AccountsDeleteErrors, ThrowOnError>({
    url: '/accounts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single account
 */
export const accountsGet = <ThrowOnError extends boolean = false>(
  options: Options<AccountsGetData, ThrowOnError>
): RequestResult<AccountsGetResponses, AccountsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<AccountsGetResponses, AccountsGetErrors, ThrowOnError>({
    url: '/accounts/{id}',
    ...options,
  });

/**
 * Update an account, including unarchiving it by clearing archivedAt; rejects patching kind into a reserved value with 422
 */
export const accountsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AccountsUpdateData, ThrowOnError>
): RequestResult<AccountsUpdateResponses, AccountsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<AccountsUpdateResponses, AccountsUpdateErrors, ThrowOnError>({
    url: '/accounts/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Masked read of a gift card account’s details — never the number/PIN
 */
export const giftCardDetailsGet = <ThrowOnError extends boolean = false>(
  options: Options<GiftCardDetailsGetData, ThrowOnError>
): RequestResult<GiftCardDetailsGetResponses, GiftCardDetailsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GiftCardDetailsGetResponses,
    GiftCardDetailsGetErrors,
    ThrowOnError
  >({ url: '/accounts/{id}/gift-card-details', ...options });

/**
 * Create or replace a gift card account’s encrypted number/PIN
 */
export const giftCardDetailsWrite = <ThrowOnError extends boolean = false>(
  options: Options<GiftCardDetailsWriteData, ThrowOnError>
): RequestResult<GiftCardDetailsWriteResponses, GiftCardDetailsWriteErrors, ThrowOnError> =>
  (options.client ?? client).put<
    GiftCardDetailsWriteResponses,
    GiftCardDetailsWriteErrors,
    ThrowOnError
  >({
    url: '/accounts/{id}/gift-card-details',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Decrypt and return the plaintext number/PIN once; audited
 */
export const giftCardDetailsReveal = <ThrowOnError extends boolean = false>(
  options: Options<GiftCardDetailsRevealData, ThrowOnError>
): RequestResult<GiftCardDetailsRevealResponses, GiftCardDetailsRevealErrors, ThrowOnError> =>
  (options.client ?? client).post<
    GiftCardDetailsRevealResponses,
    GiftCardDetailsRevealErrors,
    ThrowOnError
  >({
    url: '/accounts/{id}/gift-card-details/reveal',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List a loan account’s offset links, closed ones included unless active=true
 */
export const loanListOffsetLinks = <ThrowOnError extends boolean = false>(
  options: Options<LoanListOffsetLinksData, ThrowOnError>
): RequestResult<LoanListOffsetLinksResponses, LoanListOffsetLinksErrors, ThrowOnError> =>
  (options.client ?? client).get<
    LoanListOffsetLinksResponses,
    LoanListOffsetLinksErrors,
    ThrowOnError
  >({ url: '/accounts/{id}/loan-offset-links', ...options });

/**
 * Link an offset account to a loan account; any existing account may be the offset
 */
export const loanLinkOffsetAccount = <ThrowOnError extends boolean = false>(
  options: Options<LoanLinkOffsetAccountData, ThrowOnError>
): RequestResult<LoanLinkOffsetAccountResponses, LoanLinkOffsetAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<
    LoanLinkOffsetAccountResponses,
    LoanLinkOffsetAccountErrors,
    ThrowOnError
  >({
    url: '/accounts/{id}/loan-offset-links',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Close an offset link (sets unlinkedAt) without deleting it; idempotent
 */
export const loanUnlinkOffsetAccount = <ThrowOnError extends boolean = false>(
  options: Options<LoanUnlinkOffsetAccountData, ThrowOnError>
): RequestResult<LoanUnlinkOffsetAccountResponses, LoanUnlinkOffsetAccountErrors, ThrowOnError> =>
  (options.client ?? client).post<
    LoanUnlinkOffsetAccountResponses,
    LoanUnlinkOffsetAccountErrors,
    ThrowOnError
  >({
    url: '/accounts/{id}/loan-offset-links/{linkId}/unlink',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List every rate a loan account has carried, newest effective date first
 */
export const loanListRateHistory = <ThrowOnError extends boolean = false>(
  options: Options<LoanListRateHistoryData, ThrowOnError>
): RequestResult<LoanListRateHistoryResponses, LoanListRateHistoryErrors, ThrowOnError> =>
  (options.client ?? client).get<
    LoanListRateHistoryResponses,
    LoanListRateHistoryErrors,
    ThrowOnError
  >({ url: '/accounts/{id}/loan-rate-history', ...options });

/**
 * Record a rate change and mirror it onto the loan’s terms; 422s a non-latest effectiveFrom
 */
export const loanRecordRate = <ThrowOnError extends boolean = false>(
  options: Options<LoanRecordRateData, ThrowOnError>
): RequestResult<LoanRecordRateResponses, LoanRecordRateErrors, ThrowOnError> =>
  (options.client ?? client).post<LoanRecordRateResponses, LoanRecordRateErrors, ThrowOnError>({
    url: '/accounts/{id}/loan-rate-history',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Read a loan account’s terms
 */
export const loanGetTerms = <ThrowOnError extends boolean = false>(
  options: Options<LoanGetTermsData, ThrowOnError>
): RequestResult<LoanGetTermsResponses, LoanGetTermsErrors, ThrowOnError> =>
  (options.client ?? client).get<LoanGetTermsResponses, LoanGetTermsErrors, ThrowOnError>({
    url: '/accounts/{id}/loan-terms',
    ...options,
  });

/**
 * Create or replace a loan account’s terms, recording the matching rate history row atomically
 */
export const loanWriteTerms = <ThrowOnError extends boolean = false>(
  options: Options<LoanWriteTermsData, ThrowOnError>
): RequestResult<LoanWriteTermsResponses, LoanWriteTermsErrors, ThrowOnError> =>
  (options.client ?? client).put<LoanWriteTermsResponses, LoanWriteTermsErrors, ThrowOnError>({
    url: '/accounts/{id}/loan-terms',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Merge account :id (the source) into targetId: repoint its transactions onto targetId and delete it outright. Irreversible — the caller should show the preview first
 */
export const accountsMerge = <ThrowOnError extends boolean = false>(
  options: Options<AccountsMergeData, ThrowOnError>
): RequestResult<AccountsMergeResponses, AccountsMergeErrors, ThrowOnError> =>
  (options.client ?? client).post<AccountsMergeResponses, AccountsMergeErrors, ThrowOnError>({
    url: '/accounts/{id}/merge',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Preview merging account :id (the source) into targetId, without writing anything; rejects with 422 for a merge that cannot be meaningful (self, cross-currency, cross-sign-convention)
 */
export const accountsPreviewMerge = <ThrowOnError extends boolean = false>(
  options: Options<AccountsPreviewMergeData, ThrowOnError>
): RequestResult<AccountsPreviewMergeResponses, AccountsPreviewMergeErrors, ThrowOnError> =>
  (options.client ?? client).post<
    AccountsPreviewMergeResponses,
    AccountsPreviewMergeErrors,
    ThrowOnError
  >({
    url: '/accounts/{id}/merge/preview',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List budgets with optional search / period / active filters and pagination
 */
export const budgetsList = <ThrowOnError extends boolean = false>(
  options?: Options<BudgetsListData, ThrowOnError>
): RequestResult<BudgetsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<BudgetsListResponses, unknown, ThrowOnError>({
    url: '/budgets',
    ...options,
  });

/**
 * Create a budget
 */
export const budgetsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<BudgetsCreateData, ThrowOnError>
): RequestResult<BudgetsCreateResponses, BudgetsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<BudgetsCreateResponses, BudgetsCreateErrors, ThrowOnError>({
    url: '/budgets',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete a budget
 */
export const budgetsDelete = <ThrowOnError extends boolean = false>(
  options: Options<BudgetsDeleteData, ThrowOnError>
): RequestResult<BudgetsDeleteResponses, BudgetsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<BudgetsDeleteResponses, BudgetsDeleteErrors, ThrowOnError>({
    url: '/budgets/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single budget (with spend aggregates)
 */
export const budgetsGet = <ThrowOnError extends boolean = false>(
  options: Options<BudgetsGetData, ThrowOnError>
): RequestResult<BudgetsGetResponses, BudgetsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<BudgetsGetResponses, BudgetsGetErrors, ThrowOnError>({
    url: '/budgets/{id}',
    ...options,
  });

/**
 * Update a budget
 */
export const budgetsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<BudgetsUpdateData, ThrowOnError>
): RequestResult<BudgetsUpdateResponses, BudgetsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<BudgetsUpdateResponses, BudgetsUpdateErrors, ThrowOnError>({
    url: '/budgets/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List corrections with optional minConfidence / matchType filters and pagination
 */
export const correctionsList = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsListData, ThrowOnError>
): RequestResult<CorrectionsListResponses, CorrectionsListErrors, ThrowOnError> =>
  (options?.client ?? client).get<CorrectionsListResponses, CorrectionsListErrors, ThrowOnError>({
    url: '/corrections',
    ...options,
  });

/**
 * Create a correction, or reinforce an existing one keyed on (pattern, matchType)
 */
export const correctionsCreateOrUpdate = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsCreateOrUpdateData, ThrowOnError>
): RequestResult<
  CorrectionsCreateOrUpdateResponses,
  CorrectionsCreateOrUpdateErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsCreateOrUpdateResponses,
    CorrectionsCreateOrUpdateErrors,
    ThrowOnError
  >({
    url: '/corrections',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * AI-derive a reusable rule (matchType/pattern/confidence) from one labelled transaction
 */
export const correctionsAnalyzeCorrection = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsAnalyzeCorrectionData, ThrowOnError>
): RequestResult<
  CorrectionsAnalyzeCorrectionResponses,
  CorrectionsAnalyzeCorrectionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsAnalyzeCorrectionResponses,
    CorrectionsAnalyzeCorrectionErrors,
    ThrowOnError
  >({
    url: '/corrections/analyze',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Apply a correction-rule ChangeSet atomically; returns the full rule set
 */
export const correctionsApplyChangeSet = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsApplyChangeSetData, ThrowOnError>
): RequestResult<
  CorrectionsApplyChangeSetResponses,
  CorrectionsApplyChangeSetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsApplyChangeSetResponses,
    CorrectionsApplyChangeSetErrors,
    ThrowOnError
  >({
    url: '/corrections/apply-changeset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Find the winning correction for a description (null when none match)
 */
export const correctionsFindMatch = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsFindMatchData, ThrowOnError>
): RequestResult<CorrectionsFindMatchResponses, CorrectionsFindMatchErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CorrectionsFindMatchResponses,
    CorrectionsFindMatchErrors,
    ThrowOnError
  >({
    url: '/corrections/find-match',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * AI-propose reusable tagging rules from a batch of transactions
 */
export const correctionsGenerateRules = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsGenerateRulesData, ThrowOnError>
): RequestResult<CorrectionsGenerateRulesResponses, CorrectionsGenerateRulesErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CorrectionsGenerateRulesResponses,
    CorrectionsGenerateRulesErrors,
    ThrowOnError
  >({
    url: '/corrections/generate-rules',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List corrections with pending (un-persisted) ChangeSets folded in (temp: rows included), paginated
 */
export const correctionsListMerged = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsListMergedData, ThrowOnError>
): RequestResult<CorrectionsListMergedResponses, CorrectionsListMergedErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    CorrectionsListMergedResponses,
    CorrectionsListMergedErrors,
    ThrowOnError
  >({
    url: '/corrections/list-merged',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Preview the before/after match impact of a ChangeSet against caller-supplied transactions
 */
export const correctionsPreviewChangeSet = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsPreviewChangeSetData, ThrowOnError>
): RequestResult<
  CorrectionsPreviewChangeSetResponses,
  CorrectionsPreviewChangeSetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsPreviewChangeSetResponses,
    CorrectionsPreviewChangeSetErrors,
    ThrowOnError
  >({
    url: '/corrections/preview-changeset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Preview the transactions a candidate (pattern, matchType) rule would match
 */
export const correctionsPreviewMatches = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsPreviewMatchesData, ThrowOnError>
): RequestResult<
  CorrectionsPreviewMatchesResponses,
  CorrectionsPreviewMatchesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsPreviewMatchesResponses,
    CorrectionsPreviewMatchesErrors,
    ThrowOnError
  >({
    url: '/corrections/preview-matches',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Propose an add/edit ChangeSet for a correction signal (adapts to prior rejections)
 */
export const correctionsProposeChangeSet = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsProposeChangeSetData, ThrowOnError>
): RequestResult<
  CorrectionsProposeChangeSetResponses,
  CorrectionsProposeChangeSetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsProposeChangeSetResponses,
    CorrectionsProposeChangeSetErrors,
    ThrowOnError
  >({
    url: '/corrections/propose-changeset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Record rejection feedback for a ChangeSet (best-effort; feeds the next proposal)
 */
export const correctionsRejectChangeSet = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsRejectChangeSetData, ThrowOnError>
): RequestResult<
  CorrectionsRejectChangeSetResponses,
  CorrectionsRejectChangeSetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsRejectChangeSetResponses,
    CorrectionsRejectChangeSetErrors,
    ThrowOnError
  >({
    url: '/corrections/reject-changeset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * AI-revise an in-progress ChangeSet from a free-text instruction
 */
export const correctionsReviseChangeSet = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsReviseChangeSetData, ThrowOnError>
): RequestResult<
  CorrectionsReviseChangeSetResponses,
  CorrectionsReviseChangeSetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsReviseChangeSetResponses,
    CorrectionsReviseChangeSetErrors,
    ThrowOnError
  >({
    url: '/corrections/revise-changeset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List every DB transaction a candidate (pattern, matchType) rule matches, paged, with the full-DB match total
 */
export const correctionsRuleMatchPreview = <ThrowOnError extends boolean = false>(
  options?: Options<CorrectionsRuleMatchPreviewData, ThrowOnError>
): RequestResult<
  CorrectionsRuleMatchPreviewResponses,
  CorrectionsRuleMatchPreviewErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    CorrectionsRuleMatchPreviewResponses,
    CorrectionsRuleMatchPreviewErrors,
    ThrowOnError
  >({
    url: '/corrections/rule-match-preview',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete a correction
 */
export const correctionsDelete = <ThrowOnError extends boolean = false>(
  options: Options<CorrectionsDeleteData, ThrowOnError>
): RequestResult<CorrectionsDeleteResponses, CorrectionsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    CorrectionsDeleteResponses,
    CorrectionsDeleteErrors,
    ThrowOnError
  >({
    url: '/corrections/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single correction by id
 */
export const correctionsGet = <ThrowOnError extends boolean = false>(
  options: Options<CorrectionsGetData, ThrowOnError>
): RequestResult<CorrectionsGetResponses, CorrectionsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<CorrectionsGetResponses, CorrectionsGetErrors, ThrowOnError>({
    url: '/corrections/{id}',
    ...options,
  });

/**
 * Update a correction
 */
export const correctionsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CorrectionsUpdateData, ThrowOnError>
): RequestResult<CorrectionsUpdateResponses, CorrectionsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    CorrectionsUpdateResponses,
    CorrectionsUpdateErrors,
    ThrowOnError
  >({
    url: '/corrections/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Nudge a correction confidence by delta (deletes the row when it drops below 0.3)
 */
export const correctionsAdjustConfidence = <ThrowOnError extends boolean = false>(
  options: Options<CorrectionsAdjustConfidenceData, ThrowOnError>
): RequestResult<
  CorrectionsAdjustConfidenceResponses,
  CorrectionsAdjustConfidenceErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CorrectionsAdjustConfidenceResponses,
    CorrectionsAdjustConfidenceErrors,
    ThrowOnError
  >({
    url: '/corrections/{id}/adjust-confidence',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Retroactively apply a correction rule to every existing transaction it currently wins against (#3660); dryRun previews without writing
 */
export const correctionsApplyExisting = <ThrowOnError extends boolean = false>(
  options: Options<CorrectionsApplyExistingData, ThrowOnError>
): RequestResult<CorrectionsApplyExistingResponses, CorrectionsApplyExistingErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CorrectionsApplyExistingResponses,
    CorrectionsApplyExistingErrors,
    ThrowOnError
  >({
    url: '/corrections/{id}/apply-existing',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List every currency, fiat and points alike
 */
export const currenciesList = <ThrowOnError extends boolean = false>(
  options?: Options<CurrenciesListData, ThrowOnError>
): RequestResult<CurrenciesListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<CurrenciesListResponses, unknown, ThrowOnError>({
    url: '/currencies',
    ...options,
  });

/**
 * Register a new currency (or points program)
 */
export const currenciesCreate = <ThrowOnError extends boolean = false>(
  options?: Options<CurrenciesCreateData, ThrowOnError>
): RequestResult<CurrenciesCreateResponses, CurrenciesCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<CurrenciesCreateResponses, CurrenciesCreateErrors, ThrowOnError>(
    {
      url: '/currencies',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    }
  );

/**
 * Delete a currency, refused while any table still references it
 */
export const currenciesDelete = <ThrowOnError extends boolean = false>(
  options: Options<CurrenciesDeleteData, ThrowOnError>
): RequestResult<CurrenciesDeleteResponses, CurrenciesDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    CurrenciesDeleteResponses,
    CurrenciesDeleteErrors,
    ThrowOnError
  >({
    url: '/currencies/{code}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Edit a currency; changing decimals is refused with 409 while any account references it
 */
export const currenciesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<CurrenciesUpdateData, ThrowOnError>
): RequestResult<CurrenciesUpdateResponses, CurrenciesUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<CurrenciesUpdateResponses, CurrenciesUpdateErrors, ThrowOnError>(
    {
      url: '/currencies/{code}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    }
  );

/**
 * List entities with per-entity transactionCount; orphanedOnly=true returns count===0
 */
export const entityUsageList = <ThrowOnError extends boolean = false>(
  options?: Options<EntityUsageListData, ThrowOnError>
): RequestResult<EntityUsageListResponses, EntityUsageListErrors, ThrowOnError> =>
  (options?.client ?? client).get<EntityUsageListResponses, EntityUsageListErrors, ThrowOnError>({
    url: '/entity-usage',
    ...options,
  });

/**
 * Apply a correction ChangeSet atomically, then re-evaluate the import session
 */
export const importsApplyChangeSetAndReevaluate = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsApplyChangeSetAndReevaluateData, ThrowOnError>
): RequestResult<
  ImportsApplyChangeSetAndReevaluateResponses,
  ImportsApplyChangeSetAndReevaluateErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    ImportsApplyChangeSetAndReevaluateResponses,
    ImportsApplyChangeSetAndReevaluateErrors,
    ThrowOnError
  >({
    url: '/imports/apply-changeset-reevaluate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Atomically create entities, apply changeSets + tag-rule changeSets, write transactions
 */
export const importsCommitImport = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsCommitImportData, ThrowOnError>
): RequestResult<ImportsCommitImportResponses, ImportsCommitImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsCommitImportResponses,
    ImportsCommitImportErrors,
    ThrowOnError
  >({
    url: '/imports/commit',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Create a new entity during an import session
 */
export const importsCreateEntity = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsCreateEntityData, ThrowOnError>
): RequestResult<ImportsCreateEntityResponses, ImportsCreateEntityErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsCreateEntityResponses,
    ImportsCreateEntityErrors,
    ThrowOnError
  >({
    url: '/imports/entities',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Start an import process (dedup + entity matching); returns a session id to poll
 */
export const importsProcessImport = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsProcessImportData, ThrowOnError>
): RequestResult<ImportsProcessImportResponses, ImportsProcessImportErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    ImportsProcessImportResponses,
    ImportsProcessImportErrors,
    ThrowOnError
  >({
    url: '/imports/process',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Poll an import session for progress (null when the session is unknown/expired)
 */
export const importsGetImportProgress = <ThrowOnError extends boolean = false>(
  options: Options<ImportsGetImportProgressData, ThrowOnError>
): RequestResult<ImportsGetImportProgressResponses, ImportsGetImportProgressErrors, ThrowOnError> =>
  (options.client ?? client).get<
    ImportsGetImportProgressResponses,
    ImportsGetImportProgressErrors,
    ThrowOnError
  >({ url: '/imports/progress', ...options });

/**
 * Re-evaluate the import session against merged (DB + pending) rules; no DB writes
 */
export const importsReevaluateWithPendingRules = <ThrowOnError extends boolean = false>(
  options?: Options<ImportsReevaluateWithPendingRulesData, ThrowOnError>
): RequestResult<
  ImportsReevaluateWithPendingRulesResponses,
  ImportsReevaluateWithPendingRulesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    ImportsReevaluateWithPendingRulesResponses,
    ImportsReevaluateWithPendingRulesErrors,
    ThrowOnError
  >({
    url: '/imports/reevaluate-pending',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List every institution
 */
export const institutionsList = <ThrowOnError extends boolean = false>(
  options?: Options<InstitutionsListData, ThrowOnError>
): RequestResult<InstitutionsListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<InstitutionsListResponses, unknown, ThrowOnError>({
    url: '/institutions',
    ...options,
  });

/**
 * Register a new institution
 */
export const institutionsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<InstitutionsCreateData, ThrowOnError>
): RequestResult<InstitutionsCreateResponses, InstitutionsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    InstitutionsCreateResponses,
    InstitutionsCreateErrors,
    ThrowOnError
  >({
    url: '/institutions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete an institution, refused while any account still references it
 */
export const institutionsDelete = <ThrowOnError extends boolean = false>(
  options: Options<InstitutionsDeleteData, ThrowOnError>
): RequestResult<InstitutionsDeleteResponses, InstitutionsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    InstitutionsDeleteResponses,
    InstitutionsDeleteErrors,
    ThrowOnError
  >({
    url: '/institutions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Rename an institution and/or change its colour
 */
export const institutionsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<InstitutionsUpdateData, ThrowOnError>
): RequestResult<InstitutionsUpdateResponses, InstitutionsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    InstitutionsUpdateResponses,
    InstitutionsUpdateErrors,
    ThrowOnError
  >({
    url: '/institutions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Search the finance pillar's domains (transactions, budgets, wishlist) for the unified search engine
 */
export const searchSearch = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchData, ThrowOnError>
): RequestResult<SearchSearchResponses, SearchSearchErrors, ThrowOnError> =>
  (options?.client ?? client).post<SearchSearchResponses, SearchSearchErrors, ThrowOnError>({
    url: '/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List effective values for every declared key (sensitive redacted)
 */
export const settingsList = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsListData, ThrowOnError>
): RequestResult<SettingsListResponses, SettingsListErrors, ThrowOnError> =>
  (options?.client ?? client).get<SettingsListResponses, SettingsListErrors, ThrowOnError>({
    url: '/settings',
    ...options,
  });

/**
 * Batch-read settings by key (missing omitted; sensitive redacted)
 */
export const settingsGetMany = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsGetManyData, ThrowOnError>
): RequestResult<SettingsGetManyResponses, SettingsGetManyErrors, ThrowOnError> =>
  (options?.client ?? client).post<SettingsGetManyResponses, SettingsGetManyErrors, ThrowOnError>({
    url: '/settings/get-many',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Reset declared keys to defaults (omit keys ⇒ reset all)
 */
export const settingsReset = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsResetData, ThrowOnError>
): RequestResult<SettingsResetResponses, SettingsResetErrors, ThrowOnError> =>
  (options?.client ?? client).post<SettingsResetResponses, SettingsResetErrors, ThrowOnError>({
    url: '/settings/reset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Transactional batch write (all-or-nothing); returns the written mirror
 */
export const settingsSetMany = <ThrowOnError extends boolean = false>(
  options?: Options<SettingsSetManyData, ThrowOnError>
): RequestResult<SettingsSetManyResponses, SettingsSetManyErrors, ThrowOnError> =>
  (options?.client ?? client).post<SettingsSetManyResponses, SettingsSetManyErrors, ThrowOnError>({
    url: '/settings/set-many',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Read a single setting (null on unset; sensitive redacted)
 */
export const settingsGet = <ThrowOnError extends boolean = false>(
  options: Options<SettingsGetData, ThrowOnError>
): RequestResult<SettingsGetResponses, SettingsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<SettingsGetResponses, SettingsGetErrors, ThrowOnError>({
    url: '/settings/{key}',
    ...options,
  });

/**
 * Upsert a single declared setting
 */
export const settingsSet = <ThrowOnError extends boolean = false>(
  options: Options<SettingsSetData, ThrowOnError>
): RequestResult<SettingsSetResponses, SettingsSetErrors, ThrowOnError> =>
  (options.client ?? client).put<SettingsSetResponses, SettingsSetErrors, ThrowOnError>({
    url: '/settings/{key}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Internal-only write-once seed (encryption seed / client id)
 */
export const settingsEnsure = <ThrowOnError extends boolean = false>(
  options: Options<SettingsEnsureData, ThrowOnError>
): RequestResult<SettingsEnsureResponses, SettingsEnsureErrors, ThrowOnError> =>
  (options.client ?? client).post<SettingsEnsureResponses, SettingsEnsureErrors, ThrowOnError>({
    url: '/settings/{key}/ensure',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reset a single setting to its manifest default
 */
export const settingsResetKey = <ThrowOnError extends boolean = false>(
  options: Options<SettingsResetKeyData, ThrowOnError>
): RequestResult<SettingsResetKeyResponses, SettingsResetKeyErrors, ThrowOnError> =>
  (options.client ?? client).post<SettingsResetKeyResponses, SettingsResetKeyErrors, ThrowOnError>({
    url: '/settings/{key}/reset',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List tag rules with optional matchType/isActive/minConfidence filters and pagination
 */
export const tagRulesList = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesListData, ThrowOnError>
): RequestResult<TagRulesListResponses, TagRulesListErrors, ThrowOnError> =>
  (options?.client ?? client).get<TagRulesListResponses, TagRulesListErrors, ThrowOnError>({
    url: '/tag-rules',
    ...options,
  });

/**
 * Apply a tag-rule ChangeSet; upserts accepted new vocabulary tags
 */
export const tagRulesApply = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesApplyData, ThrowOnError>
): RequestResult<TagRulesApplyResponses, TagRulesApplyErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesApplyResponses, TagRulesApplyErrors, ThrowOnError>({
    url: '/tag-rules/apply',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * The tag namespaces and who may mint a value on each
 */
export const tagRulesFacets = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesFacetsData, ThrowOnError>
): RequestResult<TagRulesFacetsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TagRulesFacetsResponses, unknown, ThrowOnError>({
    url: '/tag-rules/facets',
    ...options,
  });

/**
 * List every DB transaction a candidate (pattern, matchType) tag rule matches, paged, with the full-DB match total
 */
export const tagRulesMatchPreview = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesMatchPreviewData, ThrowOnError>
): RequestResult<TagRulesMatchPreviewResponses, TagRulesMatchPreviewErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TagRulesMatchPreviewResponses,
    TagRulesMatchPreviewErrors,
    ThrowOnError
  >({
    url: '/tag-rules/match-preview',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Preview the suggestion-impact of a tag-rule ChangeSet over the supplied transactions
 */
export const tagRulesPreview = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesPreviewData, ThrowOnError>
): RequestResult<TagRulesPreviewResponses, TagRulesPreviewErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesPreviewResponses, TagRulesPreviewErrors, ThrowOnError>({
    url: '/tag-rules/preview',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Propose a tag-rule ChangeSet from a tag-edit signal (deterministic, with impact preview)
 */
export const tagRulesPropose = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesProposeData, ThrowOnError>
): RequestResult<TagRulesProposeResponses, TagRulesProposeErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesProposeResponses, TagRulesProposeErrors, ThrowOnError>({
    url: '/tag-rules/propose',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Reject a ChangeSet, recording the feedback against the refused ChangeSet
 */
export const tagRulesReject = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesRejectData, ThrowOnError>
): RequestResult<TagRulesRejectResponses, TagRulesRejectErrors, ThrowOnError> =>
  (options?.client ?? client).post<TagRulesRejectResponses, TagRulesRejectErrors, ThrowOnError>({
    url: '/tag-rules/reject',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List the user tag vocabulary
 */
export const tagRulesVocabulary = <ThrowOnError extends boolean = false>(
  options?: Options<TagRulesVocabularyData, ThrowOnError>
): RequestResult<TagRulesVocabularyResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TagRulesVocabularyResponses, unknown, ThrowOnError>({
    url: '/tag-rules/vocabulary',
    ...options,
  });

/**
 * Delete a tag rule
 */
export const tagRulesDelete = <ThrowOnError extends boolean = false>(
  options: Options<TagRulesDeleteData, ThrowOnError>
): RequestResult<TagRulesDeleteResponses, TagRulesDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<TagRulesDeleteResponses, TagRulesDeleteErrors, ThrowOnError>({
    url: '/tag-rules/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single tag rule by id
 */
export const tagRulesGet = <ThrowOnError extends boolean = false>(
  options: Options<TagRulesGetData, ThrowOnError>
): RequestResult<TagRulesGetResponses, TagRulesGetErrors, ThrowOnError> =>
  (options.client ?? client).get<TagRulesGetResponses, TagRulesGetErrors, ThrowOnError>({
    url: '/tag-rules/{id}',
    ...options,
  });

/**
 * Edit a tag rule (entityId / tags / confidence / priority / isActive)
 */
export const tagRulesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TagRulesUpdateData, ThrowOnError>
): RequestResult<TagRulesUpdateResponses, TagRulesUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<TagRulesUpdateResponses, TagRulesUpdateErrors, ThrowOnError>({
    url: '/tag-rules/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Retroactively apply a tag rule to every existing matching transaction (#3660); dryRun previews without writing
 */
export const tagRulesApplyExisting = <ThrowOnError extends boolean = false>(
  options: Options<TagRulesApplyExistingData, ThrowOnError>
): RequestResult<TagRulesApplyExistingResponses, TagRulesApplyExistingErrors, ThrowOnError> =>
  (options.client ?? client).post<
    TagRulesApplyExistingResponses,
    TagRulesApplyExistingErrors,
    ThrowOnError
  >({
    url: '/tag-rules/{id}/apply-existing',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Disable a tag rule (soft-delete: isActive=false)
 */
export const tagRulesDisable = <ThrowOnError extends boolean = false>(
  options: Options<TagRulesDisableData, ThrowOnError>
): RequestResult<TagRulesDisableResponses, TagRulesDisableErrors, ThrowOnError> =>
  (options.client ?? client).post<TagRulesDisableResponses, TagRulesDisableErrors, ThrowOnError>({
    url: '/tag-rules/{id}/disable',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List transactions with optional filters and pagination
 */
export const transactionsList = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsListData, ThrowOnError>
): RequestResult<TransactionsListResponses, TransactionsListErrors, ThrowOnError> =>
  (options?.client ?? client).get<TransactionsListResponses, TransactionsListErrors, ThrowOnError>({
    url: '/transactions',
    ...options,
  });

/**
 * Create a transaction
 */
export const transactionsCreate = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsCreateData, ThrowOnError>
): RequestResult<TransactionsCreateResponses, TransactionsCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TransactionsCreateResponses,
    TransactionsCreateErrors,
    ThrowOnError
  >({
    url: '/transactions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Distinct tag values across all transactions (autocomplete)
 */
export const transactionsAvailableTags = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsAvailableTagsData, ThrowOnError>
): RequestResult<TransactionsAvailableTagsResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<TransactionsAvailableTagsResponses, unknown, ThrowOnError>({
    url: '/transactions/available-tags',
    ...options,
  });

/**
 * Descriptions (+ checksums) of existing transactions for client-side rule preview
 */
export const transactionsDescriptionsForPreview = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsDescriptionsForPreviewData, ThrowOnError>
): RequestResult<TransactionsDescriptionsForPreviewResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    TransactionsDescriptionsForPreviewResponses,
    unknown,
    ThrowOnError
  >({ url: '/transactions/descriptions-preview', ...options });

/**
 * Restore a previously-deleted transaction from its snapshot
 */
export const transactionsRestore = <ThrowOnError extends boolean = false>(
  options?: Options<TransactionsRestoreData, ThrowOnError>
): RequestResult<TransactionsRestoreResponses, TransactionsRestoreErrors, ThrowOnError> =>
  (options?.client ?? client).post<
    TransactionsRestoreResponses,
    TransactionsRestoreErrors,
    ThrowOnError
  >({
    url: '/transactions/restore',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Rule-based tag suggestions for a description/entity (no LLM call)
 */
export const transactionsSuggestTags = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsSuggestTagsData, ThrowOnError>
): RequestResult<TransactionsSuggestTagsResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<TransactionsSuggestTagsResponses, unknown, ThrowOnError>({
    url: '/transactions/suggest-tags',
    ...options,
  });

/**
 * Delete a transaction; returns a snapshot for Undo via restore
 */
export const transactionsDelete = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsDeleteData, ThrowOnError>
): RequestResult<TransactionsDeleteResponses, TransactionsDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<
    TransactionsDeleteResponses,
    TransactionsDeleteErrors,
    ThrowOnError
  >({
    url: '/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single transaction
 */
export const transactionsGet = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsGetData, ThrowOnError>
): RequestResult<TransactionsGetResponses, TransactionsGetErrors, ThrowOnError> =>
  (options.client ?? client).get<TransactionsGetResponses, TransactionsGetErrors, ThrowOnError>({
    url: '/transactions/{id}',
    ...options,
  });

/**
 * Update a transaction
 */
export const transactionsUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsUpdateData, ThrowOnError>
): RequestResult<TransactionsUpdateResponses, TransactionsUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    TransactionsUpdateResponses,
    TransactionsUpdateErrors,
    ThrowOnError
  >({
    url: '/transactions/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Break a false-positive transfer pair; symmetrically unlinks both legs
 */
export const transactionsUnlinkTransfer = <ThrowOnError extends boolean = false>(
  options: Options<TransactionsUnlinkTransferData, ThrowOnError>
): RequestResult<
  TransactionsUnlinkTransferResponses,
  TransactionsUnlinkTransferErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    TransactionsUnlinkTransferResponses,
    TransactionsUnlinkTransferErrors,
    ThrowOnError
  >({
    url: '/transactions/{id}/unlink-transfer',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List wish-list items with optional search / priority filters and pagination
 */
export const wishlistList = <ThrowOnError extends boolean = false>(
  options?: Options<WishlistListData, ThrowOnError>
): RequestResult<WishlistListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<WishlistListResponses, unknown, ThrowOnError>({
    url: '/wishlist',
    ...options,
  });

/**
 * Create a wish-list item
 */
export const wishlistCreate = <ThrowOnError extends boolean = false>(
  options?: Options<WishlistCreateData, ThrowOnError>
): RequestResult<WishlistCreateResponses, WishlistCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<WishlistCreateResponses, WishlistCreateErrors, ThrowOnError>({
    url: '/wishlist',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Delete a wish-list item
 */
export const wishlistDelete = <ThrowOnError extends boolean = false>(
  options: Options<WishlistDeleteData, ThrowOnError>
): RequestResult<WishlistDeleteResponses, WishlistDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<WishlistDeleteResponses, WishlistDeleteErrors, ThrowOnError>({
    url: '/wishlist/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single wish-list item
 */
export const wishlistGet = <ThrowOnError extends boolean = false>(
  options: Options<WishlistGetData, ThrowOnError>
): RequestResult<WishlistGetResponses, WishlistGetErrors, ThrowOnError> =>
  (options.client ?? client).get<WishlistGetResponses, WishlistGetErrors, ThrowOnError>({
    url: '/wishlist/{id}',
    ...options,
  });

/**
 * Update a wish-list item
 */
export const wishlistUpdate = <ThrowOnError extends boolean = false>(
  options: Options<WishlistUpdateData, ThrowOnError>
): RequestResult<WishlistUpdateResponses, WishlistUpdateErrors, ThrowOnError> =>
  (options.client ?? client).patch<WishlistUpdateResponses, WishlistUpdateErrors, ThrowOnError>({
    url: '/wishlist/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
