/**
 * View types for the reverse lookup, derived from the generated client.
 *
 * Aliases into `purchases-api/types.gen.ts` rather than a hand-written mirror:
 * this is another pillar's contract, regenerated by CI from its snapshot, and
 * a mirror would keep compiling while rendering fields purchases stopped
 * sending.
 */
import type { ReconcileLinksResponses } from '../../../purchases-api/types.gen.js';

type LinksPayload = NonNullable<ReconcileLinksResponses[200]>;

/** One order with at least one charge linked to the transaction being viewed. */
export type LinkedPurchase = LinksPayload['purchases'][number];

/** The order row itself — merchant, money as the merchant stated it, status. */
export type Purchase = LinkedPurchase['purchase'];

/** One charge of that order, paired with the link attaching it to the transaction. */
export type LinkedCharge = LinkedPurchase['charges'][number];

/** The link row. `confirmedAt === null` means the matcher derived it. */
export type ChargeLink = LinkedCharge['link'];
