import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MANIFEST_HEADER = '// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_JSON_PATH = resolve(HERE, '..', 'package.json');

export function readContractVersion(): string {
  const pkg: unknown = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8'));
  if (
    typeof pkg !== 'object' ||
    pkg === null ||
    !('version' in pkg) ||
    typeof (pkg as { version: unknown }).version !== 'string'
  ) {
    throw new Error('package.json must declare a string `version` field');
  }
  return (pkg as { version: string }).version;
}

export function renderManifest(version: string): string {
  return `${MANIFEST_HEADER}
// Regenerated by \`pnpm -F @pops/food-contract generate:manifest\`.
// Source version pinned at generation time: ${version}
import type { Ingredient } from './types/ingredient.js';
import type { MealPlan } from './types/meal-plan.js';
import type { Recipe } from './types/recipe.js';
import type { FoodError } from './errors.js';
import type { FoodRouter } from './router.js';

export interface FoodContract {
  readonly pillar: 'food';
  readonly version: string;
  readonly entities: {
    readonly ingredient: Ingredient;
    readonly mealPlan: MealPlan;
    readonly recipe: Recipe;
  };
  readonly errors: FoodError;
  readonly router: FoodRouter;
}
`;
}

export const MANIFEST_OUTPUT_PATH = resolve(HERE, '..', 'src', 'contract', 'manifest.generated.ts');

/**
 * {@link renderManifest} put through `oxfmt`, which is the form the committed
 * file is in — `generate:manifest` formats after writing, so the raw render
 * never matches the file byte for byte.
 *
 * Exported so the drift check and the idempotence test ask the same question
 * of the same bytes. Before POPS-1566 the test asked it by spawning
 * `pnpm run generate:manifest`, which is `pnpm` -> `tsx` -> `node` -> a second
 * `pnpm exec`, on vitest's default 5s budget: it passed in 1.5s idle and
 * timed out at 11.3s under real multi-agent load, so the verdict tracked
 * machine contention rather than the code. It also rewrote a committed file
 * mid-run, leaving a failing run's tree dirty.
 *
 * One `oxfmt` subprocess is left, and it is the irreducible part — the
 * committed bytes are oxfmt's output, so nothing in-process can predict them.
 */
export function renderFormattedManifest(version: string): string {
  const dir = mkdtempSync(join(tmpdir(), 'manifest-render-'));
  const path = join(dir, 'manifest.generated.ts');
  writeFileSync(path, renderManifest(version));
  execFileSync('pnpm', ['exec', 'oxfmt', '--write', path], { stdio: 'ignore' });
  return readFileSync(path, 'utf8');
}
