/**
 * AUTOGENERATED by scripts/generate-api-types.ts via openapi-typescript.
 * Do not edit by hand — regenerate via `pnpm -F @pops/purchases generate:api-types`.
 */
export interface paths {
  '/analytics/merchant-spend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Spend per merchant and currency over a period, with the explained/unexplained split */
    get: operations['analytics.merchantSpend'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Every line carrying an item tag, across every order */
    get: operations['purchase.itemsByTag'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/purchases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List orders, newest first */
    get: operations['purchase.list'];
    put?: never;
    /** Create an order with its deliveries, lines, charges and documents */
    post: operations['purchase.create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/purchases/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an order with its deliveries, lines, charges, documents and accounting split */
    get: operations['purchase.get'];
    put?: never;
    post?: never;
    /** Hard-delete an order (everything hanging off it cascades) */
    delete: operations['purchase.delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/purchases/{id}/items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Confirm a line's kind and item tags */
    patch: operations['purchase.patchItem'];
    trace?: never;
  };
  '/receipts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Read an uploaded receipt — photograph, PDF or pasted body — and create its purchase */
    post: operations['receipt.upload'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reconcile/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pin a link so re-derivation never revises it */
    post: operations['reconcile.confirm'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reconcile/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Charges awaiting a decision, newest order first */
    get: operations['reconcile.queue'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reconcile/sweep': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run a reconciliation sweep now */
    post: operations['reconcile.sweep'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reconcile/unlink': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Remove a link. The next sweep may re-derive it — see POPS-1309 */
    post: operations['reconcile.unlink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Search the purchases pillar's orders and line items for the unified search engine */
    post: operations['search.search'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sources': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List registered purchase sources */
    get: operations['source.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/sources/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a single purchase source */
    get: operations['source.get'];
    /** Register or update a purchase source */
    put: operations['source.upsert'];
    post?: never;
    /** Delete a purchase source that has no purchases */
    delete: operations['source.delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'analytics.merchantSpend': {
    parameters: {
      query?: {
        sources?: string[];
        statuses?: ('awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored')[];
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            merchants: {
              accounting: {
                awaitingImportCents: number;
                matchedCents: number;
                netSpendCents: number;
                refundedCents: number;
                residualCents: number;
                totalCents: number;
              };
              currency: string;
              merchant:
                | {
                    entityId: string;
                    name: string | null;
                    /** @enum {string} */
                    resolution: 'entity';
                  }
                | {
                    /** @enum {string|null} */
                    entityId: null;
                    name: string;
                    /** @enum {string} */
                    resolution: 'name';
                  }
                | {
                    /** @enum {string|null} */
                    entityId: null;
                    /** @enum {string|null} */
                    name: null;
                    /** @enum {string} */
                    resolution: 'unattributed';
                  };
              orderCount: number;
            }[];
            period: {
              from: string | null;
              to: string | null;
            };
            totals: {
              accounting: {
                awaitingImportCents: number;
                matchedCents: number;
                netSpendCents: number;
                refundedCents: number;
                residualCents: number;
                totalCents: number;
              };
              currency: string;
              orderCount: number;
            }[];
          };
        };
      };
    };
  };
  'purchase.itemsByTag': {
    parameters: {
      query: {
        tag: string;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              confirmedAt: string | null;
              item: {
                allocatedAdjustmentCents: number;
                allocatedShippingCents: number;
                createdAt: string;
                gstApplicable: boolean | null;
                id: string;
                imageUrl: string | null;
                kind: {
                  confirmedAt: string | null;
                  /** @enum {string} */
                  value: 'consumable' | 'durable' | 'digital' | 'service';
                } | null;
                lineTotalCents: number;
                merchantCategory: string | null;
                merchantCondition: string | null;
                name: string;
                position: number;
                promotionalPrice: boolean | null;
                purchaseId: string;
                quantity: number;
                refundedCents: number;
                shipmentId: string | null;
                sku: string | null;
                unitPriceCents: number;
                url: string | null;
              };
            }[];
          };
        };
      };
    };
  };
  'purchase.list': {
    parameters: {
      query?: {
        sources?: string[];
        statuses?: ('awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored')[];
        from?: string;
        to?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              checksum: string;
              createdAt: string;
              currency: string;
              discountCents: number;
              id: string;
              /** @enum {string} */
              ingestMethod: 'email' | 'export' | 'upload' | 'manual';
              merchantEntityId: string | null;
              merchantEntityName: string | null;
              orderedAt: string;
              paymentHint: string | null;
              rawRef: string | null;
              /** @enum {string} */
              settlementMode: 'card' | 'cash' | 'unknown';
              shippingCents: number;
              source: string;
              sourceOrderId: string | null;
              /** @enum {string} */
              status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
              subtotalCents: number;
              surchargeCents: number;
              taxCents: number;
              totalCents: number;
              updatedAt: string;
            }[];
          };
        };
      };
    };
  };
  'purchase.create': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          charges?: {
            allocations?: {
              amountCents: number;
              itemRef: string;
            }[];
            amountCents: number;
            chargedAt?: string | null;
            currency?: string;
            orderAmountCents?: number;
            /** @enum {string} */
            origin?: 'merchant' | 'derived';
            paymentHint?: string | null;
            /** @enum {string} */
            role?: 'capture' | 'authorization' | 'refund' | 'adjustment';
            shipmentRef?: string | null;
            sourceChargeRef?: string | null;
          }[];
          checksum: string;
          currency: string;
          discountCents?: number;
          documents?: {
            documentUri: string;
            /** @enum {string} */
            kind?: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
            shipmentRef?: string | null;
          }[];
          /** @enum {string} */
          ingestMethod: 'email' | 'export' | 'upload' | 'manual';
          items?: {
            allocatedAdjustmentCents?: number;
            allocatedShippingCents?: number;
            gstApplicable?: boolean | null;
            imageUrl?: string | null;
            /** @enum {string|null} */
            kind?: 'consumable' | 'durable' | 'digital' | 'service' | null;
            lineTotalCents: number;
            merchantCategory?: string | null;
            merchantCondition?: string | null;
            name: string;
            notes?: string[];
            promotionalPrice?: boolean | null;
            quantity?: number;
            ref?: string;
            shipmentRef?: string | null;
            sku?: string | null;
            tags?: string[];
            unitPriceCents: number;
            units?: {
              inventoryItemUri?: string | null;
              serialNumber?: string | null;
            }[];
            url?: string | null;
          }[];
          merchantEntityId?: string | null;
          merchantEntityName?: string | null;
          orderedAt: string;
          paymentHint?: string | null;
          rawRef?: string | null;
          /** @enum {string} */
          settlementMode?: 'card' | 'cash' | 'unknown';
          shipments?: {
            carrier?: string | null;
            deliveredAt?: string | null;
            ref: string;
            shippedAt?: string | null;
            shippingCents?: number;
            sourceShipmentRef?: string | null;
            /** @enum {string} */
            status?: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
            trackingNumber?: string | null;
          }[];
          shippingCents?: number;
          source: string;
          sourceOrderId?: string | null;
          subtotalCents?: number;
          surchargeCents?: number;
          taxCents?: number;
          totalCents: number;
        };
      };
    };
    responses: {
      /** @description 201 */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accounting: {
              awaitingImportCents: number;
              matchedCents: number;
              netSpendCents: number;
              refundedCents: number;
              residualCents: number;
              totalCents: number;
            };
            charges: {
              allocations: {
                amountCents: number;
                chargeId: string;
                createdAt: string;
                id: string;
                itemId: string;
              }[];
              charge: {
                amountCents: number;
                chargedAt: string | null;
                createdAt: string;
                currency: string;
                id: string;
                orderAmountCents: number;
                /** @enum {string} */
                origin: 'merchant' | 'derived';
                paymentHint: string | null;
                position: number;
                purchaseId: string;
                /** @enum {string} */
                role: 'capture' | 'authorization' | 'refund' | 'adjustment';
                shipmentId: string | null;
                sourceChargeRef: string | null;
                updatedAt: string;
              };
              links: {
                amountCents: number;
                chargeId: string;
                confidence: number;
                confirmedAt: string | null;
                createdAt: string;
                id: string;
                /** @enum {string} */
                linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
                matchRuleId: string | null;
                transactionUri: string;
              }[];
            }[];
            documents: {
              createdAt: string;
              documentStaleAt: string | null;
              documentUri: string;
              id: string;
              /** @enum {string} */
              kind: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
              purchaseId: string;
              shipmentId: string | null;
            }[];
            items: {
              item: {
                allocatedAdjustmentCents: number;
                allocatedShippingCents: number;
                createdAt: string;
                gstApplicable: boolean | null;
                id: string;
                imageUrl: string | null;
                kind: {
                  confirmedAt: string | null;
                  /** @enum {string} */
                  value: 'consumable' | 'durable' | 'digital' | 'service';
                } | null;
                lineTotalCents: number;
                merchantCategory: string | null;
                merchantCondition: string | null;
                name: string;
                position: number;
                promotionalPrice: boolean | null;
                purchaseId: string;
                quantity: number;
                refundedCents: number;
                shipmentId: string | null;
                sku: string | null;
                unitPriceCents: number;
                url: string | null;
              };
              landedCostCents: number;
              notes: string[];
              tags: {
                confirmedAt: string | null;
                tag: string;
              }[];
              units: {
                createdAt: string;
                id: string;
                inventoryItemStaleAt: string | null;
                inventoryItemUri: string | null;
                itemId: string;
                serialNumber: string | null;
              }[];
            }[];
            purchase: {
              checksum: string;
              createdAt: string;
              currency: string;
              discountCents: number;
              id: string;
              /** @enum {string} */
              ingestMethod: 'email' | 'export' | 'upload' | 'manual';
              merchantEntityId: string | null;
              merchantEntityName: string | null;
              orderedAt: string;
              paymentHint: string | null;
              rawRef: string | null;
              /** @enum {string} */
              settlementMode: 'card' | 'cash' | 'unknown';
              shippingCents: number;
              source: string;
              sourceOrderId: string | null;
              /** @enum {string} */
              status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
              subtotalCents: number;
              surchargeCents: number;
              taxCents: number;
              totalCents: number;
              updatedAt: string;
            };
            shipments: {
              carrier: string | null;
              createdAt: string;
              deliveredAt: string | null;
              id: string;
              position: number;
              purchaseId: string;
              shippedAt: string | null;
              shippingCents: number;
              sourceShipmentRef: string | null;
              /** @enum {string} */
              status: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
              trackingNumber: string | null;
              updatedAt: string;
            }[];
            tags: string[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'purchase.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accounting: {
              awaitingImportCents: number;
              matchedCents: number;
              netSpendCents: number;
              refundedCents: number;
              residualCents: number;
              totalCents: number;
            };
            charges: {
              allocations: {
                amountCents: number;
                chargeId: string;
                createdAt: string;
                id: string;
                itemId: string;
              }[];
              charge: {
                amountCents: number;
                chargedAt: string | null;
                createdAt: string;
                currency: string;
                id: string;
                orderAmountCents: number;
                /** @enum {string} */
                origin: 'merchant' | 'derived';
                paymentHint: string | null;
                position: number;
                purchaseId: string;
                /** @enum {string} */
                role: 'capture' | 'authorization' | 'refund' | 'adjustment';
                shipmentId: string | null;
                sourceChargeRef: string | null;
                updatedAt: string;
              };
              links: {
                amountCents: number;
                chargeId: string;
                confidence: number;
                confirmedAt: string | null;
                createdAt: string;
                id: string;
                /** @enum {string} */
                linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
                matchRuleId: string | null;
                transactionUri: string;
              }[];
            }[];
            documents: {
              createdAt: string;
              documentStaleAt: string | null;
              documentUri: string;
              id: string;
              /** @enum {string} */
              kind: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
              purchaseId: string;
              shipmentId: string | null;
            }[];
            items: {
              item: {
                allocatedAdjustmentCents: number;
                allocatedShippingCents: number;
                createdAt: string;
                gstApplicable: boolean | null;
                id: string;
                imageUrl: string | null;
                kind: {
                  confirmedAt: string | null;
                  /** @enum {string} */
                  value: 'consumable' | 'durable' | 'digital' | 'service';
                } | null;
                lineTotalCents: number;
                merchantCategory: string | null;
                merchantCondition: string | null;
                name: string;
                position: number;
                promotionalPrice: boolean | null;
                purchaseId: string;
                quantity: number;
                refundedCents: number;
                shipmentId: string | null;
                sku: string | null;
                unitPriceCents: number;
                url: string | null;
              };
              landedCostCents: number;
              notes: string[];
              tags: {
                confirmedAt: string | null;
                tag: string;
              }[];
              units: {
                createdAt: string;
                id: string;
                inventoryItemStaleAt: string | null;
                inventoryItemUri: string | null;
                itemId: string;
                serialNumber: string | null;
              }[];
            }[];
            purchase: {
              checksum: string;
              createdAt: string;
              currency: string;
              discountCents: number;
              id: string;
              /** @enum {string} */
              ingestMethod: 'email' | 'export' | 'upload' | 'manual';
              merchantEntityId: string | null;
              merchantEntityName: string | null;
              orderedAt: string;
              paymentHint: string | null;
              rawRef: string | null;
              /** @enum {string} */
              settlementMode: 'card' | 'cash' | 'unknown';
              shippingCents: number;
              source: string;
              sourceOrderId: string | null;
              /** @enum {string} */
              status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
              subtotalCents: number;
              surchargeCents: number;
              taxCents: number;
              totalCents: number;
              updatedAt: string;
            };
            shipments: {
              carrier: string | null;
              createdAt: string;
              deliveredAt: string | null;
              id: string;
              position: number;
              purchaseId: string;
              shippedAt: string | null;
              shippingCents: number;
              sourceShipmentRef: string | null;
              /** @enum {string} */
              status: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
              trackingNumber: string | null;
              updatedAt: string;
            }[];
            tags: string[];
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'purchase.delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'purchase.patchItem': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
        itemId: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          /** @enum {string|null} */
          kind?: 'consumable' | 'durable' | 'digital' | 'service' | null;
          tags?: string[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            item: {
              allocatedAdjustmentCents: number;
              allocatedShippingCents: number;
              createdAt: string;
              gstApplicable: boolean | null;
              id: string;
              imageUrl: string | null;
              kind: {
                confirmedAt: string | null;
                /** @enum {string} */
                value: 'consumable' | 'durable' | 'digital' | 'service';
              } | null;
              lineTotalCents: number;
              merchantCategory: string | null;
              merchantCondition: string | null;
              name: string;
              position: number;
              promotionalPrice: boolean | null;
              purchaseId: string;
              quantity: number;
              refundedCents: number;
              shipmentId: string | null;
              sku: string | null;
              unitPriceCents: number;
              url: string | null;
            };
            landedCostCents: number;
            notes: string[];
            tags: {
              confirmedAt: string | null;
              tag: string;
            }[];
            units: {
              createdAt: string;
              id: string;
              inventoryItemStaleAt: string | null;
              inventoryItemUri: string | null;
              itemId: string;
              serialNumber: string | null;
            }[];
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'receipt.upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          parts: {
            dataBase64: string;
            /** @enum {string} */
            mediaType:
              | 'image/jpeg'
              | 'image/png'
              | 'image/webp'
              | 'image/gif'
              | 'application/pdf'
              | 'text/plain';
          }[];
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                alreadyStored: boolean;
                /** @enum {string} */
                kind: 'created';
                purchase: {
                  accounting: {
                    awaitingImportCents: number;
                    matchedCents: number;
                    netSpendCents: number;
                    refundedCents: number;
                    residualCents: number;
                    totalCents: number;
                  };
                  charges: {
                    allocations: {
                      amountCents: number;
                      chargeId: string;
                      createdAt: string;
                      id: string;
                      itemId: string;
                    }[];
                    charge: {
                      amountCents: number;
                      chargedAt: string | null;
                      createdAt: string;
                      currency: string;
                      id: string;
                      orderAmountCents: number;
                      /** @enum {string} */
                      origin: 'merchant' | 'derived';
                      paymentHint: string | null;
                      position: number;
                      purchaseId: string;
                      /** @enum {string} */
                      role: 'capture' | 'authorization' | 'refund' | 'adjustment';
                      shipmentId: string | null;
                      sourceChargeRef: string | null;
                      updatedAt: string;
                    };
                    links: {
                      amountCents: number;
                      chargeId: string;
                      confidence: number;
                      confirmedAt: string | null;
                      createdAt: string;
                      id: string;
                      /** @enum {string} */
                      linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
                      matchRuleId: string | null;
                      transactionUri: string;
                    }[];
                  }[];
                  documents: {
                    createdAt: string;
                    documentStaleAt: string | null;
                    documentUri: string;
                    id: string;
                    /** @enum {string} */
                    kind:
                      | 'tax_invoice'
                      | 'receipt'
                      | 'order_confirmation'
                      | 'delivery_photo'
                      | 'other';
                    purchaseId: string;
                    shipmentId: string | null;
                  }[];
                  items: {
                    item: {
                      allocatedAdjustmentCents: number;
                      allocatedShippingCents: number;
                      createdAt: string;
                      gstApplicable: boolean | null;
                      id: string;
                      imageUrl: string | null;
                      kind: {
                        confirmedAt: string | null;
                        /** @enum {string} */
                        value: 'consumable' | 'durable' | 'digital' | 'service';
                      } | null;
                      lineTotalCents: number;
                      merchantCategory: string | null;
                      merchantCondition: string | null;
                      name: string;
                      position: number;
                      promotionalPrice: boolean | null;
                      purchaseId: string;
                      quantity: number;
                      refundedCents: number;
                      shipmentId: string | null;
                      sku: string | null;
                      unitPriceCents: number;
                      url: string | null;
                    };
                    landedCostCents: number;
                    notes: string[];
                    tags: {
                      confirmedAt: string | null;
                      tag: string;
                    }[];
                    units: {
                      createdAt: string;
                      id: string;
                      inventoryItemStaleAt: string | null;
                      inventoryItemUri: string | null;
                      itemId: string;
                      serialNumber: string | null;
                    }[];
                  }[];
                  purchase: {
                    checksum: string;
                    createdAt: string;
                    currency: string;
                    discountCents: number;
                    id: string;
                    /** @enum {string} */
                    ingestMethod: 'email' | 'export' | 'upload' | 'manual';
                    merchantEntityId: string | null;
                    merchantEntityName: string | null;
                    orderedAt: string;
                    paymentHint: string | null;
                    rawRef: string | null;
                    /** @enum {string} */
                    settlementMode: 'card' | 'cash' | 'unknown';
                    shippingCents: number;
                    source: string;
                    sourceOrderId: string | null;
                    /** @enum {string} */
                    status:
                      | 'awaiting_settlement'
                      | 'linked'
                      | 'partial'
                      | 'settled_cash'
                      | 'ignored';
                    subtotalCents: number;
                    surchargeCents: number;
                    taxCents: number;
                    totalCents: number;
                    updatedAt: string;
                  };
                  shipments: {
                    carrier: string | null;
                    createdAt: string;
                    deliveredAt: string | null;
                    id: string;
                    position: number;
                    purchaseId: string;
                    shippedAt: string | null;
                    shippingCents: number;
                    sourceShipmentRef: string | null;
                    /** @enum {string} */
                    status: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
                    trackingNumber: string | null;
                    updatedAt: string;
                  }[];
                  tags: string[];
                };
              }
            | {
                extracted: {
                  /** @default null */
                  address: string | null;
                  currency: string | null;
                  /** @default [] */
                  discounts: string[];
                  lines: {
                    amount: string;
                    description: string;
                    quantity?: number;
                    unitNote?: string;
                  }[];
                  merchantName: string | null;
                  purchasedAt: string | null;
                  purchasedOn: string | null;
                  /** @default null */
                  shipping: string | null;
                  /** @default [] */
                  surcharges: string[];
                  tax: string | null;
                  /** @default null */
                  timeZone: string | null;
                  total: string;
                  /** @default [] */
                  unreadable: string[];
                };
                failures: {
                  deltaCents?: number;
                  detail: string;
                  /** @enum {string} */
                  kind:
                    | 'unreadable-total'
                    | 'unreadable-line'
                    | 'no-lines'
                    | 'negative-line'
                    | 'sum-mismatch'
                    | 'damaged';
                }[];
                /** @enum {string} */
                kind: 'needs-review';
                receiptUris: string[];
              }
            | {
                /** @enum {string} */
                kind: 'unreadable';
                reason: string;
                receiptUris: string[];
              };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 503 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'reconcile.confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          chargeId: string;
          transactionUri: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'reconcile.queue': {
    parameters: {
      query?: {
        source?: string;
        kind?: 'proposed' | 'unexplained';
        includeAuto?: boolean;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              amountCents: number;
              chargeId: string;
              currency: string;
              deltaCents: number;
              merchantEntityName: string | null;
              orderedAt: string;
              proposed: {
                amountCents: number;
                confidence: number;
                /** @enum {string} */
                linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
                transactionUri: string;
              }[];
              purchaseId: string;
              source: string;
              sourceOrderId: string | null;
            }[];
          };
        };
      };
    };
  };
  'reconcile.sweep': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          source?: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | {
                chargesConsidered: number;
                derivedChargesMinted: number;
                /** @enum {string} */
                kind: 'swept';
                linksTornDown: number;
                linksWritten: number;
                reviewCount: number;
              }
            | {
                /** @enum {string} */
                kind: 'skipped';
                reason: string;
              };
        };
      };
      /** @description 503 */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'reconcile.unlink': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          chargeId: string;
          transactionUri: string;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'search.search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          context?: {
            app: string | null;
            entity?: {
              title: string;
              type: string;
              uri: string;
            };
            filters?: {
              [key: string]: string;
            };
            page: string | null;
          };
          query: {
            filters?: {
              field: string;
              operator: string;
              value: string;
            }[];
            text: string;
          };
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            hits: {
              data: {
                [key: string]: unknown;
              };
              matchField: string;
              /** @enum {string} */
              matchType: 'exact' | 'prefix' | 'contains';
              score: number;
              uri: string;
            }[];
          };
        };
      };
    };
  };
  'source.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            items: {
              /** @enum {string} */
              autoLinkPolicy: 'auto' | 'review';
              createdAt: string;
              descriptorPattern: string | null;
              id: string;
              ingestAdapter: string | null;
              label: string;
              settlementWindowDays: number;
            }[];
          };
        };
      };
    };
  };
  'source.get': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            autoLinkPolicy: 'auto' | 'review';
            createdAt: string;
            descriptorPattern: string | null;
            id: string;
            ingestAdapter: string | null;
            label: string;
            settlementWindowDays: number;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'source.upsert': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': {
          /** @enum {string} */
          autoLinkPolicy?: 'auto' | 'review';
          descriptorPattern?: string | null;
          ingestAdapter?: string | null;
          label: string;
          settlementWindowDays?: number;
        };
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {string} */
            autoLinkPolicy: 'auto' | 'review';
            createdAt: string;
            descriptorPattern: string | null;
            id: string;
            ingestAdapter: string | null;
            label: string;
            settlementWindowDays: number;
          };
        };
      };
      /** @description 400 */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
  'source.delete': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** @description Body */
    requestBody?: {
      content: {
        'application/json': Record<string, never>;
      };
    };
    responses: {
      /** @description 200 */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @enum {boolean} */
            ok: true;
          };
        };
      };
      /** @description 404 */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
      /** @description 409 */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            code?: string;
            message: string;
          };
        };
      };
    };
  };
}
