// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type {
  AnalyticsMerchantSpendData,
  AnalyticsMerchantSpendResponses,
  PurchaseCreateData,
  PurchaseCreateErrors,
  PurchaseCreateResponses,
  PurchaseDeleteData,
  PurchaseDeleteErrors,
  PurchaseDeleteResponses,
  PurchaseGetData,
  PurchaseGetErrors,
  PurchaseGetResponses,
  PurchaseItemsByTagData,
  PurchaseItemsByTagResponses,
  PurchaseListData,
  PurchaseListResponses,
  PurchasePatchItemData,
  PurchasePatchItemErrors,
  PurchasePatchItemResponses,
  ReceiptUploadData,
  ReceiptUploadErrors,
  ReceiptUploadResponses,
  ReconcileConfirmData,
  ReconcileConfirmErrors,
  ReconcileConfirmResponses,
  ReconcileQueueData,
  ReconcileQueueResponses,
  ReconcileSweepData,
  ReconcileSweepErrors,
  ReconcileSweepResponses,
  ReconcileUnlinkData,
  ReconcileUnlinkErrors,
  ReconcileUnlinkResponses,
  SearchSearchData,
  SearchSearchErrors,
  SearchSearchResponses,
  SourceDeleteData,
  SourceDeleteErrors,
  SourceDeleteResponses,
  SourceGetData,
  SourceGetErrors,
  SourceGetResponses,
  SourceListData,
  SourceListResponses,
  SourceUpsertData,
  SourceUpsertErrors,
  SourceUpsertResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Spend per merchant and currency over a period, with the explained/unexplained split
 */
export const analyticsMerchantSpend = <ThrowOnError extends boolean = false>(
  options?: Options<AnalyticsMerchantSpendData, ThrowOnError>
): RequestResult<AnalyticsMerchantSpendResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<AnalyticsMerchantSpendResponses, unknown, ThrowOnError>({
    url: '/analytics/merchant-spend',
    ...options,
  });

/**
 * Every line carrying an item tag, across every order
 */
export const purchaseItemsByTag = <ThrowOnError extends boolean = false>(
  options: Options<PurchaseItemsByTagData, ThrowOnError>
): RequestResult<PurchaseItemsByTagResponses, unknown, ThrowOnError> =>
  (options.client ?? client).get<PurchaseItemsByTagResponses, unknown, ThrowOnError>({
    url: '/items',
    ...options,
  });

/**
 * List orders, newest first
 */
export const purchaseList = <ThrowOnError extends boolean = false>(
  options?: Options<PurchaseListData, ThrowOnError>
): RequestResult<PurchaseListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<PurchaseListResponses, unknown, ThrowOnError>({
    url: '/purchases',
    ...options,
  });

/**
 * Create an order with its deliveries, lines, charges and documents
 */
export const purchaseCreate = <ThrowOnError extends boolean = false>(
  options?: Options<PurchaseCreateData, ThrowOnError>
): RequestResult<PurchaseCreateResponses, PurchaseCreateErrors, ThrowOnError> =>
  (options?.client ?? client).post<PurchaseCreateResponses, PurchaseCreateErrors, ThrowOnError>({
    url: '/purchases',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Hard-delete an order (everything hanging off it cascades)
 */
export const purchaseDelete = <ThrowOnError extends boolean = false>(
  options: Options<PurchaseDeleteData, ThrowOnError>
): RequestResult<PurchaseDeleteResponses, PurchaseDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<PurchaseDeleteResponses, PurchaseDeleteErrors, ThrowOnError>({
    url: '/purchases/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get an order with its deliveries, lines, charges, documents and accounting split
 */
export const purchaseGet = <ThrowOnError extends boolean = false>(
  options: Options<PurchaseGetData, ThrowOnError>
): RequestResult<PurchaseGetResponses, PurchaseGetErrors, ThrowOnError> =>
  (options.client ?? client).get<PurchaseGetResponses, PurchaseGetErrors, ThrowOnError>({
    url: '/purchases/{id}',
    ...options,
  });

/**
 * Confirm a line's kind and item tags
 */
export const purchasePatchItem = <ThrowOnError extends boolean = false>(
  options: Options<PurchasePatchItemData, ThrowOnError>
): RequestResult<PurchasePatchItemResponses, PurchasePatchItemErrors, ThrowOnError> =>
  (options.client ?? client).patch<
    PurchasePatchItemResponses,
    PurchasePatchItemErrors,
    ThrowOnError
  >({
    url: '/purchases/{id}/items/{itemId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Read an uploaded receipt — photograph, PDF or pasted body — and create its purchase
 */
export const receiptUpload = <ThrowOnError extends boolean = false>(
  options?: Options<ReceiptUploadData, ThrowOnError>
): RequestResult<ReceiptUploadResponses, ReceiptUploadErrors, ThrowOnError> =>
  (options?.client ?? client).post<ReceiptUploadResponses, ReceiptUploadErrors, ThrowOnError>({
    url: '/receipts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Pin a link so re-derivation never revises it
 */
export const reconcileConfirm = <ThrowOnError extends boolean = false>(
  options?: Options<ReconcileConfirmData, ThrowOnError>
): RequestResult<ReconcileConfirmResponses, ReconcileConfirmErrors, ThrowOnError> =>
  (options?.client ?? client).post<ReconcileConfirmResponses, ReconcileConfirmErrors, ThrowOnError>(
    {
      url: '/reconcile/confirm',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
      },
    }
  );

/**
 * Charges awaiting a decision, newest order first
 */
export const reconcileQueue = <ThrowOnError extends boolean = false>(
  options?: Options<ReconcileQueueData, ThrowOnError>
): RequestResult<ReconcileQueueResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ReconcileQueueResponses, unknown, ThrowOnError>({
    url: '/reconcile/queue',
    ...options,
  });

/**
 * Run a reconciliation sweep now
 */
export const reconcileSweep = <ThrowOnError extends boolean = false>(
  options?: Options<ReconcileSweepData, ThrowOnError>
): RequestResult<ReconcileSweepResponses, ReconcileSweepErrors, ThrowOnError> =>
  (options?.client ?? client).post<ReconcileSweepResponses, ReconcileSweepErrors, ThrowOnError>({
    url: '/reconcile/sweep',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Remove a link. The next sweep may re-derive it — see POPS-1309
 */
export const reconcileUnlink = <ThrowOnError extends boolean = false>(
  options?: Options<ReconcileUnlinkData, ThrowOnError>
): RequestResult<ReconcileUnlinkResponses, ReconcileUnlinkErrors, ThrowOnError> =>
  (options?.client ?? client).post<ReconcileUnlinkResponses, ReconcileUnlinkErrors, ThrowOnError>({
    url: '/reconcile/unlink',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * Search the purchases pillar's orders and line items for the unified search engine
 */
export const searchSearch = <ThrowOnError extends boolean = false>(
  options?: Options<SearchSearchData, ThrowOnError>
): RequestResult<SearchSearchResponses, SearchSearchErrors, ThrowOnError> =>
  (options?.client ?? client).post<SearchSearchResponses, SearchSearchErrors, ThrowOnError>({
    url: '/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

/**
 * List registered purchase sources
 */
export const sourceList = <ThrowOnError extends boolean = false>(
  options?: Options<SourceListData, ThrowOnError>
): RequestResult<SourceListResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<SourceListResponses, unknown, ThrowOnError>({
    url: '/sources',
    ...options,
  });

/**
 * Delete a purchase source that has no purchases
 */
export const sourceDelete = <ThrowOnError extends boolean = false>(
  options: Options<SourceDeleteData, ThrowOnError>
): RequestResult<SourceDeleteResponses, SourceDeleteErrors, ThrowOnError> =>
  (options.client ?? client).delete<SourceDeleteResponses, SourceDeleteErrors, ThrowOnError>({
    url: '/sources/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a single purchase source
 */
export const sourceGet = <ThrowOnError extends boolean = false>(
  options: Options<SourceGetData, ThrowOnError>
): RequestResult<SourceGetResponses, SourceGetErrors, ThrowOnError> =>
  (options.client ?? client).get<SourceGetResponses, SourceGetErrors, ThrowOnError>({
    url: '/sources/{id}',
    ...options,
  });

/**
 * Register or update a purchase source
 */
export const sourceUpsert = <ThrowOnError extends boolean = false>(
  options: Options<SourceUpsertData, ThrowOnError>
): RequestResult<SourceUpsertResponses, SourceUpsertErrors, ThrowOnError> =>
  (options.client ?? client).put<SourceUpsertResponses, SourceUpsertErrors, ThrowOnError>({
    url: '/sources/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
