// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type AnalyticsMerchantSpendData = {
  body?: never;
  path?: never;
  query?: {
    sources?: Array<string>;
    statuses?: Array<'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored'>;
    from?: string;
    to?: string;
  };
  url: '/analytics/merchant-spend';
};

export type AnalyticsMerchantSpendResponses = {
  /**
   * 200
   */
  200: {
    merchants: Array<{
      accounting: {
        awaitingImportCents: number;
        matchedCents: number;
        netSpendCents: number;
        refundedCents: number;
        residualCents: number;
        totalCents: number;
      };
      currency: string;
      merchant:
        | {
            entityId: string;
            name: string | null;
            resolution: 'entity';
          }
        | {
            entityId: null;
            name: string;
            resolution: 'name';
          }
        | {
            entityId: null;
            name: null;
            resolution: 'unattributed';
          };
      orderCount: number;
    }>;
    period: {
      from: string | null;
      to: string | null;
    };
    totals: Array<{
      accounting: {
        awaitingImportCents: number;
        matchedCents: number;
        netSpendCents: number;
        refundedCents: number;
        residualCents: number;
        totalCents: number;
      };
      currency: string;
      orderCount: number;
    }>;
  };
};

export type AnalyticsMerchantSpendResponse =
  AnalyticsMerchantSpendResponses[keyof AnalyticsMerchantSpendResponses];

export type PurchaseItemsByTagData = {
  body?: never;
  path?: never;
  query: {
    tag: string;
    limit?: number;
  };
  url: '/items';
};

export type PurchaseItemsByTagResponses = {
  /**
   * 200
   */
  200: {
    items: Array<{
      confirmedAt: string | null;
      item: {
        allocatedAdjustmentCents: number;
        allocatedShippingCents: number;
        createdAt: string;
        gstApplicable: boolean | null;
        id: string;
        imageUrl: string | null;
        kind: {
          confirmedAt: string | null;
          value: 'consumable' | 'durable' | 'digital' | 'service';
        } | null;
        lineTotalCents: number;
        merchantCategory: string | null;
        merchantCondition: string | null;
        name: string;
        position: number;
        promotionalPrice: boolean | null;
        purchaseId: string;
        quantity: number;
        refundedCents: number;
        shipmentId: string | null;
        sku: string | null;
        unitPriceCents: number;
        url: string | null;
      };
    }>;
  };
};

export type PurchaseItemsByTagResponse =
  PurchaseItemsByTagResponses[keyof PurchaseItemsByTagResponses];

export type PurchaseListData = {
  body?: never;
  path?: never;
  query?: {
    sources?: Array<string>;
    statuses?: Array<'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored'>;
    from?: string;
    to?: string;
    limit?: number;
    offset?: number;
  };
  url: '/purchases';
};

export type PurchaseListResponses = {
  /**
   * 200
   */
  200: {
    items: Array<{
      checksum: string;
      createdAt: string;
      currency: string;
      discountCents: number;
      id: string;
      ingestMethod: 'email' | 'export' | 'upload' | 'manual';
      merchantEntityId: string | null;
      merchantEntityName: string | null;
      orderedAt: string;
      paymentHint: string | null;
      rawRef: string | null;
      settlementMode: 'card' | 'cash' | 'unknown';
      shippingCents: number;
      source: string;
      sourceOrderId: string | null;
      status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
      subtotalCents: number;
      surchargeCents: number;
      taxCents: number;
      totalCents: number;
      updatedAt: string;
    }>;
  };
};

export type PurchaseListResponse = PurchaseListResponses[keyof PurchaseListResponses];

export type PurchaseCreateData = {
  /**
   * Body
   */
  body?: {
    charges?: Array<{
      allocations?: Array<{
        amountCents: number;
        itemRef: string;
      }>;
      amountCents: number;
      chargedAt?: string | null;
      currency?: string;
      orderAmountCents?: number;
      origin?: 'merchant' | 'derived';
      paymentHint?: string | null;
      role?: 'capture' | 'authorization' | 'refund' | 'adjustment';
      shipmentRef?: string | null;
      sourceChargeRef?: string | null;
    }>;
    checksum: string;
    currency: string;
    discountCents?: number;
    documents?: Array<{
      documentUri: string;
      kind?: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
      shipmentRef?: string | null;
    }>;
    ingestMethod: 'email' | 'export' | 'upload' | 'manual';
    items?: Array<{
      allocatedAdjustmentCents?: number;
      allocatedShippingCents?: number;
      gstApplicable?: boolean | null;
      imageUrl?: string | null;
      kind?: 'consumable' | 'durable' | 'digital' | 'service';
      lineTotalCents: number;
      merchantCategory?: string | null;
      merchantCondition?: string | null;
      name: string;
      notes?: Array<string>;
      promotionalPrice?: boolean | null;
      quantity?: number;
      ref?: string;
      shipmentRef?: string | null;
      sku?: string | null;
      tags?: Array<string>;
      unitPriceCents: number;
      units?: Array<{
        inventoryItemUri?: string | null;
        serialNumber?: string | null;
      }>;
      url?: string | null;
    }>;
    merchantEntityId?: string | null;
    merchantEntityName?: string | null;
    orderedAt: string;
    paymentHint?: string | null;
    rawRef?: string | null;
    settlementMode?: 'card' | 'cash' | 'unknown';
    shipments?: Array<{
      carrier?: string | null;
      deliveredAt?: string | null;
      ref: string;
      shippedAt?: string | null;
      shippingCents?: number;
      sourceShipmentRef?: string | null;
      status?: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
      trackingNumber?: string | null;
    }>;
    shippingCents?: number;
    source: string;
    sourceOrderId?: string | null;
    subtotalCents?: number;
    surchargeCents?: number;
    taxCents?: number;
    totalCents: number;
  };
  path?: never;
  query?: never;
  url: '/purchases';
};

export type PurchaseCreateErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type PurchaseCreateError = PurchaseCreateErrors[keyof PurchaseCreateErrors];

export type PurchaseCreateResponses = {
  /**
   * 201
   */
  201: {
    accounting: {
      awaitingImportCents: number;
      matchedCents: number;
      netSpendCents: number;
      refundedCents: number;
      residualCents: number;
      totalCents: number;
    };
    charges: Array<{
      allocations: Array<{
        amountCents: number;
        chargeId: string;
        createdAt: string;
        id: string;
        itemId: string;
      }>;
      charge: {
        amountCents: number;
        chargedAt: string | null;
        createdAt: string;
        currency: string;
        id: string;
        orderAmountCents: number;
        origin: 'merchant' | 'derived';
        paymentHint: string | null;
        position: number;
        purchaseId: string;
        role: 'capture' | 'authorization' | 'refund' | 'adjustment';
        shipmentId: string | null;
        sourceChargeRef: string | null;
        updatedAt: string;
      };
      links: Array<{
        amountCents: number;
        chargeId: string;
        confidence: number;
        confirmedAt: string | null;
        createdAt: string;
        id: string;
        linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
        matchRuleId: string | null;
        transactionUri: string;
      }>;
    }>;
    documents: Array<{
      createdAt: string;
      documentStaleAt: string | null;
      documentUri: string;
      id: string;
      kind: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
      purchaseId: string;
      shipmentId: string | null;
    }>;
    items: Array<{
      item: {
        allocatedAdjustmentCents: number;
        allocatedShippingCents: number;
        createdAt: string;
        gstApplicable: boolean | null;
        id: string;
        imageUrl: string | null;
        kind: {
          confirmedAt: string | null;
          value: 'consumable' | 'durable' | 'digital' | 'service';
        } | null;
        lineTotalCents: number;
        merchantCategory: string | null;
        merchantCondition: string | null;
        name: string;
        position: number;
        promotionalPrice: boolean | null;
        purchaseId: string;
        quantity: number;
        refundedCents: number;
        shipmentId: string | null;
        sku: string | null;
        unitPriceCents: number;
        url: string | null;
      };
      landedCostCents: number;
      notes: Array<string>;
      tags: Array<{
        confirmedAt: string | null;
        tag: string;
      }>;
      units: Array<{
        createdAt: string;
        id: string;
        inventoryItemStaleAt: string | null;
        inventoryItemUri: string | null;
        itemId: string;
        serialNumber: string | null;
      }>;
    }>;
    purchase: {
      checksum: string;
      createdAt: string;
      currency: string;
      discountCents: number;
      id: string;
      ingestMethod: 'email' | 'export' | 'upload' | 'manual';
      merchantEntityId: string | null;
      merchantEntityName: string | null;
      orderedAt: string;
      paymentHint: string | null;
      rawRef: string | null;
      settlementMode: 'card' | 'cash' | 'unknown';
      shippingCents: number;
      source: string;
      sourceOrderId: string | null;
      status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
      subtotalCents: number;
      surchargeCents: number;
      taxCents: number;
      totalCents: number;
      updatedAt: string;
    };
    shipments: Array<{
      carrier: string | null;
      createdAt: string;
      deliveredAt: string | null;
      id: string;
      position: number;
      purchaseId: string;
      shippedAt: string | null;
      shippingCents: number;
      sourceShipmentRef: string | null;
      status: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
      trackingNumber: string | null;
      updatedAt: string;
    }>;
    tags: Array<string>;
  };
};

export type PurchaseCreateResponse = PurchaseCreateResponses[keyof PurchaseCreateResponses];

export type PurchaseDeleteData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/purchases/{id}';
};

export type PurchaseDeleteErrors = {
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
};

export type PurchaseDeleteError = PurchaseDeleteErrors[keyof PurchaseDeleteErrors];

export type PurchaseDeleteResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
  };
};

export type PurchaseDeleteResponse = PurchaseDeleteResponses[keyof PurchaseDeleteResponses];

export type PurchaseGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/purchases/{id}';
};

export type PurchaseGetErrors = {
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
};

export type PurchaseGetError = PurchaseGetErrors[keyof PurchaseGetErrors];

export type PurchaseGetResponses = {
  /**
   * 200
   */
  200: {
    accounting: {
      awaitingImportCents: number;
      matchedCents: number;
      netSpendCents: number;
      refundedCents: number;
      residualCents: number;
      totalCents: number;
    };
    charges: Array<{
      allocations: Array<{
        amountCents: number;
        chargeId: string;
        createdAt: string;
        id: string;
        itemId: string;
      }>;
      charge: {
        amountCents: number;
        chargedAt: string | null;
        createdAt: string;
        currency: string;
        id: string;
        orderAmountCents: number;
        origin: 'merchant' | 'derived';
        paymentHint: string | null;
        position: number;
        purchaseId: string;
        role: 'capture' | 'authorization' | 'refund' | 'adjustment';
        shipmentId: string | null;
        sourceChargeRef: string | null;
        updatedAt: string;
      };
      links: Array<{
        amountCents: number;
        chargeId: string;
        confidence: number;
        confirmedAt: string | null;
        createdAt: string;
        id: string;
        linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
        matchRuleId: string | null;
        transactionUri: string;
      }>;
    }>;
    documents: Array<{
      createdAt: string;
      documentStaleAt: string | null;
      documentUri: string;
      id: string;
      kind: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
      purchaseId: string;
      shipmentId: string | null;
    }>;
    items: Array<{
      item: {
        allocatedAdjustmentCents: number;
        allocatedShippingCents: number;
        createdAt: string;
        gstApplicable: boolean | null;
        id: string;
        imageUrl: string | null;
        kind: {
          confirmedAt: string | null;
          value: 'consumable' | 'durable' | 'digital' | 'service';
        } | null;
        lineTotalCents: number;
        merchantCategory: string | null;
        merchantCondition: string | null;
        name: string;
        position: number;
        promotionalPrice: boolean | null;
        purchaseId: string;
        quantity: number;
        refundedCents: number;
        shipmentId: string | null;
        sku: string | null;
        unitPriceCents: number;
        url: string | null;
      };
      landedCostCents: number;
      notes: Array<string>;
      tags: Array<{
        confirmedAt: string | null;
        tag: string;
      }>;
      units: Array<{
        createdAt: string;
        id: string;
        inventoryItemStaleAt: string | null;
        inventoryItemUri: string | null;
        itemId: string;
        serialNumber: string | null;
      }>;
    }>;
    purchase: {
      checksum: string;
      createdAt: string;
      currency: string;
      discountCents: number;
      id: string;
      ingestMethod: 'email' | 'export' | 'upload' | 'manual';
      merchantEntityId: string | null;
      merchantEntityName: string | null;
      orderedAt: string;
      paymentHint: string | null;
      rawRef: string | null;
      settlementMode: 'card' | 'cash' | 'unknown';
      shippingCents: number;
      source: string;
      sourceOrderId: string | null;
      status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
      subtotalCents: number;
      surchargeCents: number;
      taxCents: number;
      totalCents: number;
      updatedAt: string;
    };
    shipments: Array<{
      carrier: string | null;
      createdAt: string;
      deliveredAt: string | null;
      id: string;
      position: number;
      purchaseId: string;
      shippedAt: string | null;
      shippingCents: number;
      sourceShipmentRef: string | null;
      status: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
      trackingNumber: string | null;
      updatedAt: string;
    }>;
    tags: Array<string>;
  };
};

export type PurchaseGetResponse = PurchaseGetResponses[keyof PurchaseGetResponses];

export type PurchasePatchItemData = {
  /**
   * Body
   */
  body?: {
    kind?: 'consumable' | 'durable' | 'digital' | 'service';
    tags?: Array<string>;
  };
  path: {
    id: string;
    itemId: string;
  };
  query?: never;
  url: '/purchases/{id}/items/{itemId}';
};

export type PurchasePatchItemErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
};

export type PurchasePatchItemError = PurchasePatchItemErrors[keyof PurchasePatchItemErrors];

export type PurchasePatchItemResponses = {
  /**
   * 200
   */
  200: {
    item: {
      allocatedAdjustmentCents: number;
      allocatedShippingCents: number;
      createdAt: string;
      gstApplicable: boolean | null;
      id: string;
      imageUrl: string | null;
      kind: {
        confirmedAt: string | null;
        value: 'consumable' | 'durable' | 'digital' | 'service';
      } | null;
      lineTotalCents: number;
      merchantCategory: string | null;
      merchantCondition: string | null;
      name: string;
      position: number;
      promotionalPrice: boolean | null;
      purchaseId: string;
      quantity: number;
      refundedCents: number;
      shipmentId: string | null;
      sku: string | null;
      unitPriceCents: number;
      url: string | null;
    };
    landedCostCents: number;
    notes: Array<string>;
    tags: Array<{
      confirmedAt: string | null;
      tag: string;
    }>;
    units: Array<{
      createdAt: string;
      id: string;
      inventoryItemStaleAt: string | null;
      inventoryItemUri: string | null;
      itemId: string;
      serialNumber: string | null;
    }>;
  };
};

export type PurchasePatchItemResponse =
  PurchasePatchItemResponses[keyof PurchasePatchItemResponses];

export type ReceiptUploadData = {
  /**
   * Body
   */
  body?: {
    parts: Array<{
      dataBase64: string;
      mediaType:
        | 'image/jpeg'
        | 'image/png'
        | 'image/webp'
        | 'image/gif'
        | 'application/pdf'
        | 'text/plain';
    }>;
  };
  path?: never;
  query?: never;
  url: '/receipts';
};

export type ReceiptUploadErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
  /**
   * 503
   */
  503: {
    code?: string;
    message: string;
  };
};

export type ReceiptUploadError = ReceiptUploadErrors[keyof ReceiptUploadErrors];

export type ReceiptUploadResponses = {
  /**
   * 200
   */
  200:
    | {
        alreadyStored: boolean;
        kind: 'created';
        purchase: {
          accounting: {
            awaitingImportCents: number;
            matchedCents: number;
            netSpendCents: number;
            refundedCents: number;
            residualCents: number;
            totalCents: number;
          };
          charges: Array<{
            allocations: Array<{
              amountCents: number;
              chargeId: string;
              createdAt: string;
              id: string;
              itemId: string;
            }>;
            charge: {
              amountCents: number;
              chargedAt: string | null;
              createdAt: string;
              currency: string;
              id: string;
              orderAmountCents: number;
              origin: 'merchant' | 'derived';
              paymentHint: string | null;
              position: number;
              purchaseId: string;
              role: 'capture' | 'authorization' | 'refund' | 'adjustment';
              shipmentId: string | null;
              sourceChargeRef: string | null;
              updatedAt: string;
            };
            links: Array<{
              amountCents: number;
              chargeId: string;
              confidence: number;
              confirmedAt: string | null;
              createdAt: string;
              id: string;
              linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
              matchRuleId: string | null;
              transactionUri: string;
            }>;
          }>;
          documents: Array<{
            createdAt: string;
            documentStaleAt: string | null;
            documentUri: string;
            id: string;
            kind: 'tax_invoice' | 'receipt' | 'order_confirmation' | 'delivery_photo' | 'other';
            purchaseId: string;
            shipmentId: string | null;
          }>;
          items: Array<{
            item: {
              allocatedAdjustmentCents: number;
              allocatedShippingCents: number;
              createdAt: string;
              gstApplicable: boolean | null;
              id: string;
              imageUrl: string | null;
              kind: {
                confirmedAt: string | null;
                value: 'consumable' | 'durable' | 'digital' | 'service';
              } | null;
              lineTotalCents: number;
              merchantCategory: string | null;
              merchantCondition: string | null;
              name: string;
              position: number;
              promotionalPrice: boolean | null;
              purchaseId: string;
              quantity: number;
              refundedCents: number;
              shipmentId: string | null;
              sku: string | null;
              unitPriceCents: number;
              url: string | null;
            };
            landedCostCents: number;
            notes: Array<string>;
            tags: Array<{
              confirmedAt: string | null;
              tag: string;
            }>;
            units: Array<{
              createdAt: string;
              id: string;
              inventoryItemStaleAt: string | null;
              inventoryItemUri: string | null;
              itemId: string;
              serialNumber: string | null;
            }>;
          }>;
          purchase: {
            checksum: string;
            createdAt: string;
            currency: string;
            discountCents: number;
            id: string;
            ingestMethod: 'email' | 'export' | 'upload' | 'manual';
            merchantEntityId: string | null;
            merchantEntityName: string | null;
            orderedAt: string;
            paymentHint: string | null;
            rawRef: string | null;
            settlementMode: 'card' | 'cash' | 'unknown';
            shippingCents: number;
            source: string;
            sourceOrderId: string | null;
            status: 'awaiting_settlement' | 'linked' | 'partial' | 'settled_cash' | 'ignored';
            subtotalCents: number;
            surchargeCents: number;
            taxCents: number;
            totalCents: number;
            updatedAt: string;
          };
          shipments: Array<{
            carrier: string | null;
            createdAt: string;
            deliveredAt: string | null;
            id: string;
            position: number;
            purchaseId: string;
            shippedAt: string | null;
            shippingCents: number;
            sourceShipmentRef: string | null;
            status: 'pending' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
            trackingNumber: string | null;
            updatedAt: string;
          }>;
          tags: Array<string>;
        };
      }
    | {
        extracted: {
          address: string | null;
          currency: string | null;
          discounts: Array<string>;
          lines: Array<{
            amount: string;
            description: string;
            quantity?: number;
            unitNote?: string;
          }>;
          merchantName: string | null;
          purchasedAt: string | null;
          purchasedOn: string | null;
          shipping: string | null;
          surcharges: Array<string>;
          tax: string | null;
          timeZone: string | null;
          total: string;
          unreadable: Array<string>;
        };
        failures: Array<{
          deltaCents?: number;
          detail: string;
          kind:
            | 'unreadable-total'
            | 'unreadable-line'
            | 'no-lines'
            | 'negative-line'
            | 'sum-mismatch'
            | 'damaged';
        }>;
        kind: 'needs-review';
        receiptUris: Array<string>;
      }
    | {
        kind: 'unreadable';
        reason: string;
        receiptUris: Array<string>;
      };
};

export type ReceiptUploadResponse = ReceiptUploadResponses[keyof ReceiptUploadResponses];

export type ReconcileConfirmData = {
  /**
   * Body
   */
  body?: {
    chargeId: string;
    transactionUri: string;
  };
  path?: never;
  query?: never;
  url: '/reconcile/confirm';
};

export type ReconcileConfirmErrors = {
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
};

export type ReconcileConfirmError = ReconcileConfirmErrors[keyof ReconcileConfirmErrors];

export type ReconcileConfirmResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
  };
};

export type ReconcileConfirmResponse = ReconcileConfirmResponses[keyof ReconcileConfirmResponses];

export type ReconcileQueueData = {
  body?: never;
  path?: never;
  query?: {
    source?: string;
    kind?: 'proposed' | 'unexplained';
    includeAuto?: boolean;
    limit?: number;
    offset?: number;
  };
  url: '/reconcile/queue';
};

export type ReconcileQueueResponses = {
  /**
   * 200
   */
  200: {
    items: Array<{
      amountCents: number;
      chargeId: string;
      currency: string;
      deltaCents: number;
      merchantEntityName: string | null;
      orderedAt: string;
      proposed: Array<{
        amountCents: number;
        confidence: number;
        linkType: 'exact' | 'split' | 'combined' | 'partial' | 'rule' | 'manual';
        transactionUri: string;
      }>;
      purchaseId: string;
      source: string;
      sourceOrderId: string | null;
    }>;
  };
};

export type ReconcileQueueResponse = ReconcileQueueResponses[keyof ReconcileQueueResponses];

export type ReconcileSweepData = {
  /**
   * Body
   */
  body?: {
    source?: string;
  };
  path?: never;
  query?: never;
  url: '/reconcile/sweep';
};

export type ReconcileSweepErrors = {
  /**
   * 503
   */
  503: {
    code?: string;
    message: string;
  };
};

export type ReconcileSweepError = ReconcileSweepErrors[keyof ReconcileSweepErrors];

export type ReconcileSweepResponses = {
  /**
   * 200
   */
  200:
    | {
        chargesConsidered: number;
        derivedChargesMinted: number;
        kind: 'swept';
        linksTornDown: number;
        linksWritten: number;
        reviewCount: number;
      }
    | {
        kind: 'skipped';
        reason: string;
      };
};

export type ReconcileSweepResponse = ReconcileSweepResponses[keyof ReconcileSweepResponses];

export type ReconcileUnlinkData = {
  /**
   * Body
   */
  body?: {
    chargeId: string;
    transactionUri: string;
  };
  path?: never;
  query?: never;
  url: '/reconcile/unlink';
};

export type ReconcileUnlinkErrors = {
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
};

export type ReconcileUnlinkError = ReconcileUnlinkErrors[keyof ReconcileUnlinkErrors];

export type ReconcileUnlinkResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
  };
};

export type ReconcileUnlinkResponse = ReconcileUnlinkResponses[keyof ReconcileUnlinkResponses];

export type SearchSearchData = {
  /**
   * Body
   */
  body?: {
    context?: {
      app: string | null;
      entity?: {
        title: string;
        type: string;
        uri: string;
      };
      filters?: {
        [key: string]: string;
      };
      page: string | null;
    };
    query: {
      filters?: Array<{
        field: string;
        operator: string;
        value: string;
      }>;
      text: string;
    };
  };
  path?: never;
  query?: never;
  url: '/search';
};

export type SearchSearchResponses = {
  /**
   * 200
   */
  200: {
    hits: Array<{
      data: {
        [key: string]: unknown;
      };
      matchField: string;
      matchType: 'exact' | 'prefix' | 'contains';
      score: number;
      uri: string;
    }>;
  };
};

export type SearchSearchResponse = SearchSearchResponses[keyof SearchSearchResponses];

export type SourceListData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/sources';
};

export type SourceListResponses = {
  /**
   * 200
   */
  200: {
    items: Array<{
      autoLinkPolicy: 'auto' | 'review';
      createdAt: string;
      descriptorPattern: string | null;
      id: string;
      ingestAdapter: string | null;
      label: string;
      settlementWindowDays: number;
    }>;
  };
};

export type SourceListResponse = SourceListResponses[keyof SourceListResponses];

export type SourceDeleteData = {
  /**
   * Body
   */
  body?: {
    [key: string]: never;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/sources/{id}';
};

export type SourceDeleteErrors = {
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
  /**
   * 409
   */
  409: {
    code?: string;
    message: string;
  };
};

export type SourceDeleteError = SourceDeleteErrors[keyof SourceDeleteErrors];

export type SourceDeleteResponses = {
  /**
   * 200
   */
  200: {
    ok: true;
  };
};

export type SourceDeleteResponse = SourceDeleteResponses[keyof SourceDeleteResponses];

export type SourceGetData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/sources/{id}';
};

export type SourceGetErrors = {
  /**
   * 404
   */
  404: {
    code?: string;
    message: string;
  };
};

export type SourceGetError = SourceGetErrors[keyof SourceGetErrors];

export type SourceGetResponses = {
  /**
   * 200
   */
  200: {
    autoLinkPolicy: 'auto' | 'review';
    createdAt: string;
    descriptorPattern: string | null;
    id: string;
    ingestAdapter: string | null;
    label: string;
    settlementWindowDays: number;
  };
};

export type SourceGetResponse = SourceGetResponses[keyof SourceGetResponses];

export type SourceUpsertData = {
  /**
   * Body
   */
  body?: {
    autoLinkPolicy?: 'auto' | 'review';
    descriptorPattern?: string | null;
    ingestAdapter?: string | null;
    label: string;
    settlementWindowDays?: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: '/sources/{id}';
};

export type SourceUpsertErrors = {
  /**
   * 400
   */
  400: {
    code?: string;
    message: string;
  };
};

export type SourceUpsertError = SourceUpsertErrors[keyof SourceUpsertErrors];

export type SourceUpsertResponses = {
  /**
   * 200
   */
  200: {
    autoLinkPolicy: 'auto' | 'review';
    createdAt: string;
    descriptorPattern: string | null;
    id: string;
    ingestAdapter: string | null;
    label: string;
    settlementWindowDays: number;
  };
};

export type SourceUpsertResponse = SourceUpsertResponses[keyof SourceUpsertResponses];
