import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MANIFEST_HEADER = '// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_JSON_PATH = resolve(HERE, '..', 'package.json');

export function readContractVersion(): string {
  const pkg: unknown = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf8'));
  if (
    typeof pkg !== 'object' ||
    pkg === null ||
    !('version' in pkg) ||
    typeof (pkg as { version: unknown }).version !== 'string'
  ) {
    throw new Error('package.json must declare a string `version` field');
  }
  return (pkg as { version: string }).version;
}

export function renderManifest(version: string): string {
  return `${MANIFEST_HEADER}
// Regenerated by \`pnpm -F @pops/purchases generate:manifest\`.
// Source version pinned at generation time: ${version}
import type { Purchase, PurchaseItem, PurchaseTransactionLink } from './types/purchase.js';
import type { PurchaseSource } from './types/purchase-source.js';
import type { PurchasesError } from './errors.js';

export interface PurchasesContract {
  readonly pillar: 'purchases';
  readonly version: string;
  readonly entities: {
    readonly purchase: Purchase;
    readonly purchaseItem: PurchaseItem;
    readonly purchaseSource: PurchaseSource;
    readonly purchaseTransactionLink: PurchaseTransactionLink;
  };
  readonly errors: PurchasesError;
}
`;
}

export const MANIFEST_OUTPUT_PATH = resolve(HERE, '..', 'src', 'contract', 'manifest.generated.ts');
