import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, expectTypeOf, it } from 'vitest';

import { readContractVersion, renderFormattedManifest } from '../../../scripts/render-manifest.js';

import type { InventoryContract } from '../manifest.js';
import type { Connection } from '../types/connection.js';
import type { Item } from '../types/item.js';
import type { Location } from '../types/location.js';
import type { Warranty } from '../types/warranty.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = resolve(HERE, '..', '..', '..');
const GENERATED_PATH = resolve(PACKAGE_ROOT, 'src', 'contract', 'manifest.generated.ts');
const AUTOGENERATED_HEADER = '// AUTOGENERATED by scripts/generate-manifest.ts. Do not edit.';

describe('InventoryContract manifest type generation', () => {
  it('exposes Item on entities.item with byte-equal shape', () => {
    expectTypeOf<InventoryContract['entities']['item']>().toEqualTypeOf<Item>();
  });

  it('exposes Location on entities.location with byte-equal shape', () => {
    expectTypeOf<InventoryContract['entities']['location']>().toEqualTypeOf<Location>();
  });

  it('exposes Warranty on entities.warranty with byte-equal shape', () => {
    expectTypeOf<InventoryContract['entities']['warranty']>().toEqualTypeOf<Warranty>();
  });

  it('exposes Connection on entities.connection with byte-equal shape', () => {
    expectTypeOf<InventoryContract['entities']['connection']>().toEqualTypeOf<Connection>();
  });

  it('pins pillar discriminant and exposes errors/router slots', () => {
    expectTypeOf<InventoryContract['pillar']>().toEqualTypeOf<'inventory'>();
    expectTypeOf<InventoryContract['version']>().toEqualTypeOf<string>();
    expectTypeOf<InventoryContract>().toHaveProperty('errors');
    expectTypeOf<InventoryContract>().toHaveProperty('router');
  });

  it('emits the AUTOGENERATED header so hand-edits fail loudly', () => {
    const contents = readFileSync(GENERATED_PATH, 'utf8');
    expect(contents).toContain(AUTOGENERATED_HEADER);
  });

  // Re-rendered in memory rather than by spawning `pnpm run generate:manifest`
  // (POPS-1566). That spawn was `pnpm` -> `tsx` -> `node` -> a second
  // `pnpm exec`, on vitest's default 5s budget: 1.5s on an idle machine and a
  // timeout at 11.3s under multi-agent load, so the verdict tracked how busy
  // the machine was rather than the code. It also rewrote a committed file
  // mid-run, so a failure left the tree dirty.
  //
  // The claim is unchanged and slightly stronger: what the generator would
  // write must equal what is committed — which also catches a stale committed
  // manifest, not only a non-deterministic generator. One `oxfmt` subprocess
  // survives because the committed bytes are its output; the timeout allows
  // for it starting cold under contention.
  it('regeneration is idempotent (no diff on a second run)', { timeout: 30_000 }, () => {
    expect(renderFormattedManifest(readContractVersion())).toBe(
      readFileSync(GENERATED_PATH, 'utf8')
    );
  });
});
