import Foundation

/// A vector committed under `clients/ios/Contracts/` and asserted from both
/// languages.
///
/// These files live outside every package because the BFM asserts against the
/// same bytes and neither side may own a private copy. They are found by
/// walking the filesystem rather than shipped as SPM resources for that same
/// reason: a resource *is* a private copy, which is the thing they exist to
/// prevent.
///
/// The direction of ownership differs per file and is not this protocol's
/// business — `Contracts/device-signature-v1.json` is generated here and
/// vendored by the BFM, `Contracts/refresh-message-v1.json` is generated by the
/// BFM and vendored here. Either way this side reads a path inside its own
/// unit, which is what ADR-043 asks for.
internal protocol ContractsFixture: Decodable {
    /// Where the CI guards name this file, relative to `clients/ios/`.
    static var relativePath: String { get }
}

extension ContractsFixture {
    /// Walks up from the calling source file until the fixture appears, rather
    /// than counting directory levels — moving a test file would otherwise
    /// break the lookup with a "no such file" that says nothing about why.
    internal static func url(from sourceFile: String = #filePath) -> URL {
        var directory = URL(fileURLWithPath: sourceFile).deletingLastPathComponent()
        while directory.path != "/" {
            let candidate = directory.appendingPathComponent(relativePath)
            if FileManager.default.fileExists(atPath: candidate.path) { return candidate }
            directory.deleteLastPathComponent()
        }
        fatalError("no \(relativePath) above \(sourceFile)")
    }

    internal static func load(from sourceFile: String = #filePath) throws -> Self {
        try JSONDecoder().decode(Self.self, from: Data(contentsOf: url(from: sourceFile)))
    }

    /// A base64 field, decoded. Unparseable means the committed file is broken
    /// rather than that a test's expectation is wrong, so it stops the run
    /// naming the file instead of failing one assertion.
    internal static func decodeBase64(_ base64: String) -> Data {
        guard let data = Data(base64Encoded: base64) else {
            fatalError("a base64 field of \(relativePath) is not valid base64 — regenerate it")
        }
        return data
    }
}
