/**
 * Helpers for the per-module migration runner that handle the "schema
 * already has this" case. Split out of `per-module-migrations.ts` so the
 * runner stays at a reviewable size.
 *
 * Context: drizzle-style migrations are not idempotent — a second run
 * crashes on `CREATE TABLE X` when the table already exists. Production
 * DBs that pre-date `__drizzle_migrations` (or were bootstrapped via
 * `initializeSchema(db)`) have schema state without a matching hash row,
 * so the runner re-attempts those migrations on every boot. The fix
 * is to detect the additive-DDL "already applied" errors and treat
 * them as no-ops, recording the hash so subsequent boots short-circuit.
 *
 * Inverse errors (`no such table`, `no such column`) are intentionally
 * NOT in scope: they signal that the migration's precondition is not met
 * and need operator attention. SQLite has no `DROP COLUMN IF EXISTS`, so
 * migrations needing idempotent drops must encode the existence check
 * themselves.
 */

/**
 * SQLite error messages that indicate a DDL statement's effect is
 * already present in the schema. Matched against the error `message`
 * because better-sqlite3 surfaces SQLite's text verbatim.
 */
const ALREADY_APPLIED_PATTERNS = [
  /^table .+ already exists$/i,
  /^index .+ already exists$/i,
  /^trigger .+ already exists$/i,
  /^view .+ already exists$/i,
  /^there is already another table or index with this name/i,
  /^duplicate column name:/i,
];

export function isAlreadyAppliedError(err: unknown): boolean {
  if (!(err instanceof Error)) return false;
  return ALREADY_APPLIED_PATTERNS.some((p) => p.test(err.message));
}

/**
 * Statement-breakpoint splitter — drizzle splits multi-statement SQL files
 * with the marker `--> statement-breakpoint` and runs each chunk separately.
 * We mirror the same convention so files generated by `drizzle-kit` work
 * identically through this runner.
 */
export function splitStatements(sql: string): string[] {
  return sql
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}
